### ISSUE TITLE
Error is true but it supposed to be True?

### ISSUE THREAD

**Issue by just-Bri** [rmotr-curriculum/base-python-curriculum-questions#100]
# Complete the following operations
pro_in_programming = "programming"
print('pro' in pro_in_programming)
w_in_bridge = "bridge"
print('w' in w_in_bridge)

Gives me the following:
def test_in_or_out():
    assert pro_in_programming is True
    assert w_in_bridge is False
tests.py:28: in test_in_or_out
    assert pro_in_programming is True
E   AssertionError: assert 'programming' is True

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/in-or-out

**User code**:
```python

```

Turns out the correct code is different than the examples given.
pro_in_programming = 'pro' in 'programming'
w_in_bridge = 'w' in "bridge"

**Comment by just-Bri** [comment]
When I just run the code I get True / False which is expected and working.
Still fails when I submit.

**Comment by jsymons** [comment]
You should not be printing but setting the value of `pro_in_programming` to your True/False statement.
