### ISSUE TITLE
Tasking

### ISSUE THREAD

**Issue by kufopi** [rmotr-curriculum/base-python-curriculum-questions#103]
This got me really thinking  because i wanted this code to be intuitive. Any suggestions on how to make it better

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/sum-of-dict-values

**User code**:
```python

def sum_of_dict_values(d1, d2, d3):
    diction = {}
    summer=0
    
    for item,val in d1.items():
        if isinstance(val,int):
            summer =val
            if item in d2 and isinstance(d2[item],int):
                summer += d2[item]

                if item in d3 and isinstance(d3[item], int):
                    summer += d3[item]

                else:
                    summer = None
                    diction[item] = None
                    diction.update({item: None})
                    


            else:
                summer = None
                diction[item]= None
                diction.update({item:None})
                
        else:
            summer = None
            diction.update({item:None})
          
            
        diction[item]=summer
        summer=0
    return diction




```

**Comment by santiagobasulto** [comment]
I think the [solution proposed](https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-18-quiz-week-2/lesson-3-sum-of-dict-values/solutions/solution_multiple_functions.py) is good enough. The key here was to break the problem in smaller pieces.

"Divide and conquer", right ;) Makes sense?

**Comment by calebmackdavenport** [comment]
Kufopi, I came up with the following. It's cleaner, but would be harder to break apart without comments if you came back to this after a while.

```
def sum_of_dict_values(d1, d2, d3):
    sums = dict()
    for (k1,v1), (k2,v2), (k3, v3) in zip(d1.items(), d2.items(), d3.items()):
        if(type(v1) is int and type(v2) is int and type(v3) is int):
            sums.update({k1: (v1 + v2 + v3)})
        else:
            sums.update({k1: None})
    return sums
```

**Comment by bbookman** [comment]
@smebdi can you explain how the code "sums" for k2 and k3?  I am not understanding how the code above works.  I looked up "zip" and think I get it - however I am just not following.  Seems like someplace k2 and k3 would need sums.

**Comment by calebmackdavenport** [comment]
@bbookman I messaged you on the RMOTR slack if you'd like me to assist further. 

This makes the assumption that all of the dictionaries have the same keys, but different values of the same type. If they were different types, you would need to handle accordingly with type conversions in the addition portion `(v1 + v2 + v3)`. I would assume the end result if k2 and k3 had different keys would just be an error or something not as expected because the key:value pairs would not align. So in my example, you can just use k1 because k1=k2=k3.
