### ISSUE TITLE
Unsure of the way Reduce details work

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#105]
I am unsure of what the variables represent in the given class solution.  Does reduce iterate through the list?  Reduce is confusing :D 

**Assignment**: http://learn.rmotr.com/python/base-python-track/functional-programming/comma-code

**User code**:
```python
#Unsure what x and y represent. 

return reduce(lambda x, y: x + ", " + y if y != a_list[len(a_list)-1] else x + " and " + y, a_list)
```

**Comment by jsymons** [comment]
Basically reduce iterates through the list, and applies the function(in this case the lambda) along the way, as far as the lambda is concerned `x` is accumulative result so far of the function returns and `y` is the current element in the iterable. An example of how reduce is functioning can be found here: https://docs.python.org/2/library/functions.html#reduce

Hope that clears things up.
