### ISSUE TITLE
Would you be able to clarify the details of the Reduce function?

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#106]
reduce(lambda acc, x: acc * x, l, 1) 

What does acc stand for?  x?  how do they interact with the 'l' and '1' ?

**Assignment**: http://learn.rmotr.com/python/base-python-track/functional-programming/map-filter-and-reduce

**Comment by jsymons** [comment]
Take a look at my response in https://github.com/rmotr-curriculum/base-python-curriculum-questions/issues/105 if that doesn't clear things up let me know.
