### ISSUE TITLE
In the given class solution: 

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#107]
What does this line represent? If, for example, a_number was '3', wouldnt list(range()) convert to [0, 1, 2, 3, 4]?  How would you account for the 0?  

Lastly I dont understand the role of the 'or 1, 0, -1' 

Convoluted I know but thank you for your time!

**Assignment**: http://learn.rmotr.com/python/base-python-track/functional-programming/function-factorial

**User code**:
```python
return list(range(a_number or 1, 0, -1))
```

**Comment by jsymons** [comment]
So the way `range` works is like so: 
```python
range([start], stop, [step])
```
(parameters contained within `[]` are optional)
So `start` is where the range starts at, defaults to 0, `stop` is where the range goes up to but not including, and `step` is the increment for each number.

For example, `list(range(5, 0, -1))` would give us `[5, 4, 3, 2, 1]`.

So now that we know that let's dissect the range statement we have:
```python
range(a_number or 1, 0, -1)
```
The `a_number or 1` part tells us for the `start` to use `a_number` assuming it is not a *falsey* value (like `0` for example) if it **is** a falsey value, use 1 instead.
Then we are using `0` as the `stop`, and finally we are using `-1` for the step, meaning each new number is going to be one less than the previous.

Hope this clears things up.

**Comment by AndyDeNike** [comment]
excellent explanation, very thorough!
