### ISSUE TITLE
What is the reason for including 'r' as a parameter in open() ? 

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#108]
In the given github solution, 'r' is included as a parameter.  If we are using the 'with' setup, is the inclusion of the 'r' necessary?  What is the difference?  

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/first-line-from-file

**User code**:
```python
def read_first_line(path):
    with open(path) as fp:
        return fp.readline()
        
#VS 

def read_first_line(path):
    with open(path, 'r') as fp:
return fp.readline()
```

**Comment by jsymons** [comment]
The `'r'` means we are opening the file read only, now `'r'` is also the default mode so it's not technically needed but it makes things more explicit to the reader.

**Comment by AndyDeNike** [comment]
Quick question, are we able to write to the file without specifying 'w' ?  Does 'with open(path) as ... give default access to r, w, a, r+   ?

**Comment by jsymons** [comment]
No, if you don't specify a mode it defaults to r. You must explicitly specify other modes.
