### ISSUE TITLE
Are readline() / readlines() the standard for python file manipulation?  

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#109]
If so, it might be worth including the functinal definition of readlines() in the cheat sheet (you included readline() but not readlines() ) 
:D

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/intro-to-file-management

**Comment by santiagobasulto** [comment]
@AndyDeNike thanks for the suggestion! I'd argue that `readlines` is kind of dangerous, but might also be useful for people starting. I'll add it with a "warning" note saying "make sure you're not doing `readlines` in a 4TB file 😬.

**Comment by santiagobasulto** [comment]
Fixed btw: https://github.com/rmotr-curriculum/base-python-curriculum/commit/e3ec2c423a7a59dcecac18d2a3ea5ec4b5b68e81

**Comment by AndyDeNike** [comment]
@santiagobasulto just to clarify, when we use <file>.readlines(), does this return a list with each line of the file contained as an item in that list?  Does '**_seek(0)_**' behave differently? 
is there a better alternative to readlines() when we need to capture the contents of a file ?

**Comment by santiagobasulto** [comment]
hey Andy! `readlines()` parses **the entire file** and pulls each line and stores them in a list. If you have a file that's 4GB in size, it'll try to put all that in memory (good luck with that right? 😂). `seek` and `tell` are methods that don't require memory space, they just do "pointer operations". Moving the pointer or telling you the position of the pointer.

A better alternative to readlines() is just `readline` or just the iterator, reading 1 by 1. That makes sure to use a buffer and never use too much memory. Namely:

This is good:
```python
for line in f:
    # do something with the line
    print(line)
```

This is bad:
```python
lines = f.readlines()  # all in memory
for line in lines:
    # do something with the line
    print(line)
```

**Comment by AndyDeNike** [comment]
@santiagobasulto Thank you for the clear differentiation; I noticed most of the github solutions for the problems used readlines(), is there any reason for this?  I figured maybe because we were working with a small amount of lines in given text for the problems.  Anyway, thanks again!

**Comment by santiagobasulto** [comment]
Yes, usually to keep it simple and because we know we're using small files. Solutions involving `read` and buffers are usually more complicated 😔 .
