### ISSUE TITLE
I'm not sure why this is failing the first "Test with Boolean'

### ISSUE THREAD

**Issue by databaseadmins** [rmotr-curriculum/base-python-curriculum-questions#11]
Code below.  When I run the code it seems to be ok.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/is-numeric

**User code**:
```python
def is_numeric(a_number):
    if isinstance(a_number, int) == True:
        return True
    elif isinstance(a_number, float) == True:
        return True
    else:
        return False
    
        
print(is_numeric('f'))        
print(is_numeric(1))      
print(is_numeric(1.1))      
```

**Comment by martinzugnoni** [comment]
If you try running your code with this test, it will return an invalid response:
`print(is_numeric(False))`

So, try to also cover the "boolean" case.

**Comment by martinzugnoni** [comment]
You can run tests individually on the left bar, to see which one is failing. Hit the "RUN TEST" link.
