### ISSUE TITLE
Is there anyway to accomplish this solution without readlines() ? 

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#111]
Based on the test, is there anyway we could solve this without readlines()? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/sort-lines-in-text-file

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
This is a great question! And really interesting. It'd be **extremely** hard to sort a file without loading entirely into memory. The technique is known as [External sorting](https://en.wikipedia.org/wiki/External_sorting). It's an iterative, and not really efficient process. you're sorting small "chunks" of the file in other files, and then combining. It can be really time consuming if not implemented correctly.

**Comment by santiagobasulto** [comment]
So, just as a reference, `readlines` is good here.
