### ISSUE TITLE
What is happneing in the following lines? 

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#112]
In the RMOTR github solution, I am unsure of functionality of lines 2, 3, 4, 5.  
-  What does 'LIMIT' do within the confines of a query statement?
- What is the functionality of the second parameter of db.execute, {'limit':limit} do?  

**Assignment**: http://learn.rmotr.com/python/base-python-track/database-handling/get-movies-and-directors

**User code**:
```python
def get_movies_and_directors(db, limit=5):
    query = 'SELECT title, director FROM marvel LIMIT :limit'
    cursor = db.execute(query, {
        'limit': limit
    })
return cursor.fetchall()


```

**Comment by santiagobasulto** [comment]
Hey Andrew! `LIMIT` "limits" (😅) the results returned. Example:
```sql
SELECT * FROM Movies;
-- returns all the movies in the database, example: 1000

SELECT * FROM Movies LIMIT 1;
-- returns only 1 movie (the "first one" in the list).
```

It's commonly used to get the max value of a column without using the `MAX` function. You order by that column and then do Limit 1:

```sql
SELECT * FROM Movies ORDER BY rating LIMIT 1;
-- returns the movie with highest rating
```

The second parameter of `db.execute` is passing the actual values. For example, if you want to run the query: `SELECT * FROM Movies where title = "The Godfather"`, you do:

```python
query = 'SELECT * FROM Movies where title = :movie_title'
db.execute(query, {
    'movie_title': 'The Godfather'
})
```

Makes sense?

**Comment by AndyDeNike** [comment]
Yes, excellent explanation, the LIMIT would give you a controlled quantifiable output of data on whatever column you're sorting.  As for the second parameter, this would be considered the 'named parameters'.  Follow up question coming in the next excercise, get ready!
