### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by calebmackdavenport** [rmotr-curriculum/base-python-curriculum-questions#113]
Messed this one up a few times before I realized it was not expecting a string literal presenting the values such as '(87 - 11)' but expects the final value of the mathematical calculation.

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/subtract-reversed

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
hey @smebdi! You suggest we make it more clear or change the tests?

**Comment by calebmackdavenport** [comment]
I think the test is perfect! Just slightly more clear so that anyone would know the expected value is a single integer rather than a string. I see now where 

# Result: 8 (18 - 7 - 3)

Alludes to this. However, it just stumped me on a number of tries as I thought I was supposed to return (18 - 7 - 3) looking at the test cases. Could just be me being dumb lol

**Comment by santiagobasulto** [comment]
Yes, like this maybe? https://github.com/rmotr-curriculum/base-python-curriculum/commit/2e7b347443c1b72201e0e94a2c48e154dcb84e5d

**Comment by calebmackdavenport** [comment]
I think that looks much more readable

**Comment by santiagobasulto** [comment]
👍 thanks!
