### ISSUE TITLE
No Idea what is wanted here 

### ISSUE THREAD

**Issue by mattmm41286** [rmotr-curriculum/base-python-curriculum-questions#114]
Is the Test case what I am modeling after?  I've tried a variety of different ways and always get errors.  Are there other examples?  

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/he-did-the-math

**User code**:
```python
# Basic Math Operations
def test_the_math():
one_plus_one = 1+1
ten_minus_three = 10-3
four_times_five = 4*5
nine_divided_by_three = 9/3

# Modulus (% operator) 
# This gets the remainder from a division problem
five_mod_two = 5/2

# Exponent (** operator)
three_to_fifth_power = 3^5
```

**Comment by santiagobasulto** [comment]
hey @mattmm41286! You're in the right direction. A few notes. You **DON'T** need a function, so remove `def test_...`.

`five_mod_two = 5/2` should be `5%2`, as it's asking for the modulus operator. And `three_to_fifth_power = 3^5` should be `3**5`, as you can see in the comments above the lines.

Let us know how it goes!
