### ISSUE TITLE
How do I create an empty string without getting an error?

### ISSUE THREAD

**Issue by nimoes** [rmotr-curriculum/base-python-curriculum-questions#118]
When I create an empty string assigned to a variable, I get “Invalid character in identifier” error.. how do I avoid this?

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/no-uppercase-allowed

**User code**:
```python
stringy = “”
```

**Comment by santiagobasulto** [comment]
Hello @nimoes! You're using invalid quote characters. You should use double quotes (`"`) or single quotes (`'`). Usually an issue of keyboard/language configuration.
