### ISSUE TITLE
Why doesn't my last def of the function work?  The first two do, but I don't understand why the last one doesn't

### ISSUE THREAD

**Issue by jonathanhle** [rmotr-curriculum/base-python-curriculum-questions#119]
First two example def's work for me and pass the tests.  I tried to do the 3rd example below first and I get a syntax error.  I can't do a return and have x evaluate with an increment operator at the same time? Just wondering. Thanks ahead!

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-functions/increment-parameter-by-one

**User code**:
```python
# Your code here:
# This works
# def increment_parameter_by_one(x):
#     return x + 1

# This works too
# def increment_parameter_by_one(x):
#     x += 1
#     return x
    
# This doesn't work - why? I get an error on this one.
def increment_parameter_by_one(x):
    return x += 1
```

**Comment by santiagobasulto** [comment]
Hey Jonathan! No, the third option isn't valid. And there's a really good explanation for that, and kind of an important "programming concept" that will be useful for other languages as well.

In programming we have "statements" and "expressions". The difference is simple: **expressions generate a new value**. You can say they have a new value. Example of expressions:

```python
3 + 1  # 4
x + 1
do_something()
```

There's always a "result" after each one of those expressions. A statement is, in contrast, something that doesn't produce a new value. Examples:

```python
x = 3  # (1)
if x < 9:  # (2)
    pass

x += 1  # (3)
```

In this case, both `(1)` and `(2)` don't "return/produce/generate" new values. What's the "result" of creating a new variable (like in `(1)`): **nothing!**, we could say it's "void".

A great test to differentiate expressions from statements is: "expressions CAN be printed". You can do `print(x + 1)`. You can't do `print(if x == 3: pass)`.

Finally, answering your question. A `return` statement must ALWAYS be followed by an expression. That's they error you're getting. If you try printing `x += 1` you'll also get a syntax error.

Makes sense?

**Comment by jonathanhle** [comment]
:thumbsup: - thanks for the explanation.
