### ISSUE TITLE
Why is this producing errors when it works ok in my ide

### ISSUE THREAD

**Issue by kufopi** [rmotr-curriculum/base-python-curriculum-questions#120]
Seen your suggested answer but looks high there, but would like to know what's particularly wrong with mine.{ i'm guessing it's my cache variable ;>) }Thanks for your usual prompt reply

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-oop/cached-calculator

**User code**:
```python
class Calculator(object):
    cache = {'add':[], 'subtract':[]}
    sap = []

    def add(self, a, b):
        if (a, b, a + b) in self.cache['add']:
            return (a, b, a + b)[2]
        else:
            tot = a + b
            self.cache['add'].append((a, b, tot))
            return tot

    def subtract(self, c, d):
        if (c, d, c - d) in self.cache['subtract']:
            return (c, d, c - d)[2]
        else:
            subt = c - d
            self.cache['subtract'].append((c, d, subt))
            return subt

```

**Comment by santiagobasulto** [comment]
Hey @kufopi ! The point of this assignment is NOT to perform the computation if you've already done so. I want you to think that the operation `a + b` (or `a-b`) is INCREDIBLY expensive. It takes 30 minutes to run. In your `add` method you're doing it 3 times. The idea is to check if it's cached, and if it is, just return the result from the cache. If it's not, compute it only **once**, store it in the cache and then return it.
