### ISSUE TITLE
Not sure about lines 5 or 6

### ISSUE THREAD

**Issue by mattmm41286** [rmotr-curriculum/base-python-curriculum-questions#121]
I am getting errors on lines 5 and 6.  Not sure exactly how to structure these.  Any suggestions?  

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/even-or-odd

**User code**:
```python
def even_or_odd(a_number):
    if a_number % 2==0:
        return 'even'
        return 'odd'
    print (even_or_odd(42))=='even'
    print (even_or_odd(17))== 'odd'
```

**Comment by santiagobasulto** [comment]
Hey @mattmm41286! You have two returns at the same level. Remember that Python is ALL ABOUT indentation. Your code will work if you just un-indent the second return one level:

```python
def even_or_odd(a_number):
    if a_number % 2==0:
        return 'even'
    return 'odd'
```

Also, the print statements should probably be **outside** the function, so also un-indent them one level. Final form: 

```python
def even_or_odd(a_number):
    if a_number % 2==0:
        return 'even'
    return 'odd'

print (even_or_odd(42))=='even'
print (even_or_odd(17))== 'odd'
```
