### ISSUE TITLE
Print line

### ISSUE THREAD

**Issue by mattmm41286** [rmotr-curriculum/base-python-curriculum-questions#122]
I am confused why line 10 is getting "invalid syntax". It's the same as line 9 besides being the first "True"  line.  Does everything else look right?  

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/all-strings

**User code**:
```python
def all_strings(a, b, c):
    if type (a)==str and type (b)==str and type (c)==str:
        return True
    else:
        return False


# Run Code test. You can remove this:
        print(all_strings('hello', None, 'Python')==False
        print(all_strings('','rmotr','Python')==True
        print(all_strings(123, 'rmotr','Python')==False
        print(all_strings('j','rmotr','Python')==True
```

**Comment by santiagobasulto** [comment]
Same as before @mattmm41286! It's all about indentation. Un-indent them all. Also, you're missing a parenthesis. Count how many parenthesis you're opening and how many you're closing:

```python
print(all_strings('hello', None, 'Python')==False
     ^open       ^open                   ^ close
```
