### ISSUE TITLE
Invalid Syntax in Print

### ISSUE THREAD

**Issue by mattmm41286** [rmotr-curriculum/base-python-curriculum-questions#123]
I am getting invalid syntax in the print section and have tried just about everything.  I don't think it is indention problem this time.  Suggestions?  

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/traffic-light

**User code**:
```python
def traffic_light(color):
    if color=='red':
        return 'stop'
    elif color=='yellow':
        return 'slow down'
    elif color=='green':
        return 'go'
    print traffic_light('red')=='stop'
    print traffic_light('yellow')=='slow down'
    print traffic_light('green')=='go'
  
  
```

**Comment by jsymons** [comment]
Assuming you're using Python 3.x, parentheses are required when using `print`:
```python
print("Hello there!")
```

**Comment by mattmm41286** [comment]
print (traffic_light ('red'))=='stop'
    print (traffic_light ('yellow'))=='slow down'
    print (traffic_light ('green'))=='go'

When I change it to this, it returns nothing.  What am I missing?

**Comment by mattmm41286** [comment]
Nevermind, just figured it out.  It was an indention problem again.

**Comment by jsymons** [comment]
`print(traffic_light('red') == 'stop')`
