### ISSUE TITLE
Getting same number for all three

### ISSUE THREAD

**Issue by mattmm41286** [rmotr-curriculum/base-python-curriculum-questions#124]
I am getting 31 for all three print statements.  Not sure why.  I am not sure that the "or" use is correct.  Where am I off?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/how-many-days-in-a-month

**User code**:
```python
def how_many_days_in(a_month):
    if a_month=='January' or 'March' or 'May' or 'July' or'August' or 'October' or 'December':
        return 31
    if a_month=='September'or'June'or 'April'or 'November':
        return 30
    else:
        return 28
print(how_many_days_in('June'))==30
print(how_many_days_in('December'))==31
print(how_many_days_in('February'))==28
```

**Comment by jsymons** [comment]
It's your user of `or`. It needs to be like:
```python
if a_month == 'January' or a_month == 'March'
```
The == does not carry across or statements.

**Comment by ajakaiye33** [comment]
cant it be done by importing the date module?
