### ISSUE TITLE
Python notebook

### ISSUE THREAD

**Issue by AshutoshAhmadAlexandar** [rmotr-curriculum/base-python-curriculum-questions#125]
Hi, Is the python notebook used in the videos are available for download?

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/string-indexing

**Comment by santiagobasulto** [comment]
Yep, here are both of them! I'll add them to the lecture right now. Thanks for asking!

https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-6-strings/lesson-2-string-indexing/Indexing%20and%20Slicing%20Practice.ipynb

https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-6-strings/lesson-2-string-indexing/String%20Indexing%20and%20Slicing%20Examples.ipynb
