### ISSUE TITLE
Iteration of the string

### ISSUE THREAD

**Issue by AshutoshAhmadAlexandar** [rmotr-curriculum/base-python-curriculum-questions#126]
How to use for loop to iterate till half length or .75 length of the string

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/looping-over-strings

**Comment by santiagobasulto** [comment]
Hey @AshutoshAhmadAlexandar! Good question. You could use slicing for that:

```python
a_string = "A very long string"
half_length = int(len(a_string) / 2)

for char in a_string[:half_length]:
  print(char)
```

Just make sure to use integer numbers.
