### ISSUE TITLE
problem with the console

### ISSUE THREAD

**Issue by BJohnAmbrose** [rmotr-curriculum/base-python-curriculum-questions#127]
I sent this via the debug link already. The console to run the code is not working. It just indicates that it is in process of running the code and never does anything. Thanks!

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-data-types/concatenate-strings

**User code**:
```python
hello = "Hello"
world = "World"

# Final text should be:
# "Hello World"
text = ?

print(text)  # Use the Run Code button to try it on your own
```

**Comment by santiagobasulto** [comment]
Hey @BJohnAmbrose! It worked finally, right? Let me know if you have any other issue.
