### ISSUE TITLE
Base case?

### ISSUE THREAD

**Issue by rruss2** [rmotr-curriculum/base-python-curriculum-questions#129]
My code passes the last two test but not the first test.  What am I doing wrong?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/the-power-of-while-loops

**User code**:
```python
def feel_the_power(initial_number, power):
    counter = 1
    while counter < power:
        initial_number *= power
        counter += 1 
    return initial_number
```

**Comment by santiagobasulto** [comment]
Hey Robert! It's just the special case of any number, to the power of 0 should be `1`.

So, `3^1 = 3`, `3^2 = 9` but `3^0 = 1`. You can either check for that special case at the beginning of your function, or refactor it a little bit more. Btw, there are LIVE Mentors available right now in case you want to discuss it in a videocall.

**Comment by mattmm41286** [comment]
def feel_the_power(initial_number, power):
    counter=1
    while counter<=power:
        initial_number=initial_number**power
        counter+=1
        return initial_number
print(feel_the_power(3,0))
print(feel_the_power(3,1))
print(feel_the_power(3,3))

I am having the same issue as Robert.  Returning the last two but not the first.  I am getting none.  Any hints on the direction to go?

**Comment by mattmm41286** [comment]
Nevermind, I changed counter to =0 and it worked.  Hopefully that is the best way to do it.
