### ISSUE TITLE
Should there be a video here?  

### ISSUE THREAD

**Issue by useraddmario** [rmotr-curriculum/base-python-curriculum-questions#13]
I don't see anything but a white screen on this page and when I press the next question there is a "programming session".

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/arithmetic-operators

**Comment by santiagobasulto** [comment]
There's a reading detail @useraddmario, and you can access the notebook here: https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-3-operators/lesson-2-arithmetic-operators/Arithmetic%20Operators.ipynb
