### ISSUE TITLE
Python notebook

### ISSUE THREAD

**Issue by AshutoshAhmadAlexandar** [rmotr-curriculum/base-python-curriculum-questions#130]
Can you provide the python notebook used in this video?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-1/growing-lists

**Comment by santiagobasulto** [comment]
Sure thing! Here it is: https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-7-collections-part-1/lesson-8-growing-lists/Growing%20Lists.ipynb

Thanks again.
