### ISSUE TITLE
remove all occurences

### ISSUE THREAD

**Issue by AshutoshAhmadAlexandar** [rmotr-curriculum/base-python-curriculum-questions#131]
How can we remove all the occurrences of an element?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-1/removing-elements

**Comment by santiagobasulto** [comment]
Hello @AshutoshAhmadAlexandar! This is a **REALLY** good question. When managing data, you'll start to see that solutions tend to be immutable and the `remove` method is not so popular. Instead, we usually employ "transformation functions" that would create a new collection with a given criteria. In this case "all elements but X". We'll learn more about immutability and list comprehensions in our 6th week. So, to answer your question, we could do:

```python
l = ['a', 'b', 'c', 'a', 'd', 'a']

new_l = [c for c in l if c != 'a']
print(new_l)
```
