### ISSUE TITLE
Nothing is passed on the parameter

### ISSUE THREAD

**Issue by AshutoshAhmadAlexandar** [rmotr-curriculum/base-python-curriculum-questions#135]
The function defined doesn't have any argument passed to it. How am I supposed to get the original dict. Below is the code provided by the question:
def invert_dict():
    pass

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/dictionary-keys-and-values

**User code**:
```python
def invert_dict():
    pass
```

**Comment by jsymons** [comment]
You need to change the function definition so that it takes a parameter.
