### ISSUE TITLE
TypeError: slice indices must be integers or None?

### ISSUE THREAD

**Issue by rruss2** [rmotr-curriculum/base-python-curriculum-questions#136]
I am trying to slice the strings to return the first half for even case and odd case add the middle letter.  I am not sure where I am going wrong.  Are there other approaches than if statements? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/first-half

**User code**:
```python
def first_half(a_string):
    if int(len(a_string[:int(len(a_string))/2])) % 2 == 0:
        return a_string[:int(len(a_string))/2]
    elif (len(a_string[:len(a_string)/2])) % 2 == 1:
        return a_string[:(len(a_string)/2) + 1]
    
```

**Comment by santiagobasulto** [comment]
Hey Robert! It's probably because slices **ONLY** take integers, not floats. This fails for example:

```python
s = "abcdefg"
print(s[:3.0])  # should be s[:3]
```

One simple way to fix it is just by casting it into an integer before with the `int` function:

```python
s = "abcdefg"
index = 3.0
print(s[:int(index)])
```

**Comment by rruss2** [comment]
I do not understand what you are saying.  Is there anyway you can explain
it?
Thanks,
Robert Russ

**Comment by jsymons** [comment]
So here's the thing, division in python 3.x defaults to *floating point* division, as in there's a decimal place.
If I do `4 / 2` I'm going to get `2.0` back which is a `float`. However when slicing the number you pass in **must** be an `int`
So by doing `int(len(a_string))/2` the result is going to be a `float` to force it to be an int you need to do `int(len(a_string)/2)` *note the difference in the parentheses*. You're also going to need to make sure you're converting to `int` on each of the slices you're doing division on.

Let me know if you're still having trouble.
