### ISSUE TITLE
Getting started with is_prime(n)?

### ISSUE THREAD

**Issue by rruss2** [rmotr-curriculum/base-python-curriculum-questions#137]
I am not sure how to get started with this function.  I understand I need to find out if n is divisible by 1 and itself.  I am not sure how to translate that to code.  Also, are there any tips on how to train your mind to translate problems into code?  Are there any mind exercises, websites, etc... to help my mind translate?  I have been doing math for so long I try to write programs as though I am doing a math problem.  It doesn't work very well.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def reverse_str(s):
    # Please don't change me
    return s[::-1]

# Try it on your own by uncommenting the following lines and hitting "Run Code"
# print(reverse_str('abc'))
# print(reverse_str('123'))
# print(reverse_str('121'))

def is_palindromic(n):
    return str(n) == reverse_str(str(n))

def is_prime(n):
     
    
def next_palindromic_prime(n):
    pass
```

**Comment by jsymons** [comment]
First off for figuring out prime numbers it's not that you need do find out if n is divisible by 1 and itself, it's that those are the *only* numbers that it's divisible by. So you basically need to check to make sure that it's not divisible by any number between 1 and itself. (To make it a little faster you can first check if it's divisible by 2 and then start from 3 only checking odd numbers)

For practicing turning math problems into code check out https://projecteuler.net/

Hope this helps.
