### ISSUE TITLE
N elements in a_list?

### ISSUE THREAD

**Issue by rruss2** [rmotr-curriculum/base-python-curriculum-questions#139]
I might be complicating this problem.  Are we asked to insert in an element no matter how elements in the a_list?  The test only has three elements and adds one more element.  I am confused on how to translate position string to n element index.  I checked the answer, and it was written for four elements' indices.  Please help.  

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-1/first-second-third-last

**User code**:
```python
def insert_human(a_list, position, elem):
    
    a_list.insert(a_list.index(position, elem))
    return a_list
```

**Comment by jsymons** [comment]
It's hard-coded to **up to**  4 element lists. You have to remember that `position` is going to be `'first'`, `'second'`, `'third'`, or `'last'`. We could technically make it work with n element lists but that would make things much more complicated and outside the scope of this exercise.
