### ISSUE TITLE
I have no progress showing since the beginning.

### ISSUE THREAD

**Issue by useraddmario** [rmotr-curriculum/base-python-curriculum-questions#14]
Progress is not updated.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-functions/intro-to-functions

**Comment by santiagobasulto** [comment]
Thanks for reporting @useraddmario, can you please check if it works correctly now?

**Comment by useraddmario** [comment]
It gives me a check mark when I complete something new, but it doesn't do two thing.

1. Show progress on the Dashboard.  I have completed all lessons leading up to the first class, but no progress is shown.
2.  It doesn't advance me to another section, the Next button just says Done and I am trapped on the same page.  It was advancing me before this, but now I am using the dashboard to manually open the next lesson.
