### ISSUE TITLE
How to get middle character

### ISSUE THREAD

**Issue by mattmm41286** [rmotr-curriculum/base-python-curriculum-questions#143]
I am able to get the first half, but when I try what I think is the correct code, it tells me slice indices must be integers.  Not sure exactly how to format it correctly to add that middle character.  

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/first-half

**User code**:
```python
def first_half(a_string):
    if len(a_string)%2!=0:
        return a_string[:len](a_string//2) +1
    return a_string[:len(a_string)//2]
print(first_half('abcdef'))
print(first_half('abcXdef'))
```

**Comment by jsymons** [comment]
So in Python 3.x division defaults to `float` division, but your slice indices need to be `int`. So to force the result to be an int you can do `int(3/4)` for example.

**Comment by mattmm41286** [comment]
How do I incorporate that into the first return?  I tried to add it in line 3, and I keep on getting the same error message?

**Comment by jsymons** [comment]
`a_string[:int(len(a_string)/2)]` or for odd `a_string[:int(len(a_string)/2) + 1]`

**Comment by mattmm41286** [comment]
Thanks!
