### ISSUE TITLE
 3. Find the most expensive item in a category

### ISSUE THREAD

**Issue by AshutoshAhmadAlexandar** [rmotr-curriculum/base-python-curriculum-questions#144]
Shouldn't it give a list of most expensive item in each category, instead the solution is creating a list of all items in weapon category

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/nested-collections

**Comment by AshutoshAhmadAlexandar** [comment]
Wrote a solution:

list_of_items = {}
total_cat = []
for product in products:
    cat = product['category']
    if cat not in total_cat:
        total_cat.append(cat)
for product in products:
    for item in total_cat:
        price = product['price']
        cat = product['category']
        if price >= list_of_items.get('price', 0) and cat == item :
            list_of_items[cat] = product
list_of_items

please let me know if it can be made better using other collection or fewer loops. 
Thanks

**Comment by santiagobasulto** [comment]
Hey @AshutoshAhmadAlexandar! I think it looks good. Can you please style it a little bit better? It's hard to read the indentation and where the ifs should be placed: https://guides.github.com/features/mastering-markdown/
