### ISSUE TITLE
Accessing Only Strftime

### ISSUE THREAD

**Issue by Brotosterone** [rmotr-curriculum/base-python-curriculum-questions#147]
How can you only access the strftime function?

I would have thought it was "from datetime import date.strftime" 

**Assignment**: http://learn.rmotr.com/python/base-python-track/modules-and-packages/celebrate-if-friday

**User code**:
```python

```

**Comment by jsymons** [comment]
Short answer you can't.
The datetime package isn't structured in a way to allow it. If it was you could do `from datetime.date import strftime`, however the thing to remember with imports is that even if you were to do an import just a single part of a file, python would still read and execute the entire thing, there's no performance gain to be had.

**Comment by santiagobasulto** [comment]
> there's no performance gain to be had.
☝️
