### ISSUE TITLE
Can't proceed to next question from here

### ISSUE THREAD

**Issue by databaseadmins** [rmotr-curriculum/base-python-curriculum-questions#15]
The button to move to the next question is gone and now I only have a "Done" 

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/help-a-string-get-lucky

**User code**:
```python
def get_lucky(poor_string, lucky_number):
    loopcounter = 0
    addthis = ''
    while loopcounter < lucky_number:
        addthis = addthis + '7'
        loopcounter += 1 
    return poor_string + addthis
    
    
print(get_lucky('foofoo', 5))
```

**Comment by martinzugnoni** [comment]
That's expected. You are not supposed to "jump" to the next question from here. That was causing problems, because you were landing at lessons not belonging to the career you are enrolled to. Please use the "bullets" in the dashboard to move to the next lesson.

**Comment by databaseadmins** [comment]
I can't speak for others but I certainly don't want to do that.  I have to go back on the browser -- find the next button -- and so forth.  That's a big UX no- no.
