### ISSUE TITLE
Code isn't passing tests 

### ISSUE THREAD

**Issue by ama4coding** [rmotr-curriculum/base-python-curriculum-questions#150]
The test for a single letter passes, but not any others.

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/max-character

**User code**:
```python
def max_char(a_string):
    maximum_letter = None
    for x in a_string:
        if x <= a_string or x == maximum_letter:
            return a_string
        
```

**Comment by jsymons** [comment]
Your return statement is breaking your for loop. When the code reaches a return it **immediately** returns stopping any further execution of the function. You should be returning *outside* the for loop.

**Comment by ama4coding** [comment]
Thank you!
