### ISSUE TITLE
Solved , but used "in"

### ISSUE THREAD

**Issue by ama4coding** [rmotr-curriculum/base-python-curriculum-questions#151]
I solved this lesson, but used "in" . Not neccesarily sure how to use a for loop without "in"

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/is-char-in-string

**User code**:
```python
def char_in_string(a_string, char_to_look_for):
    for char in a_string:
        if char_to_look_for in a_string:
            return True
        else: 
             return False
```

**Comment by santiagobasulto** [comment]
Hey Andre! It should be pretty much the same thing, but just check with the current char you're iterating:

```python
def char_in_string(a_string, char_to_look_for):
    for char in a_string:
        if char_to_look_for == char:
            return True
        else: 
             return False
```

**Comment by ama4coding** [comment]
Thank you Santiago!
