### ISSUE TITLE
Stack implementation: Appending at the start of the array

### ISSUE THREAD

**Issue by cpjain2007** [rmotr-curriculum/base-python-curriculum-questions#152]
Adding an element at the start of the array is expensive so is there any particular instance where this will be useful in stack implementation or we should always try to append it at the end? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-1/using-lists-as-stacks

**Comment by santiagobasulto** [comment]
Python `append` operations are usually the most recommended ones ([see this doc from Python wiki](https://wiki.python.org/moin/TimeComplexity?)). You can implement the stack using `append` and `pop`. See also [`deque`](https://docs.python.org/3/library/collections.html#collections.deque)
