### ISSUE TITLE
While loop doesnt keep going, it stops at the first try.

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/base-python-curriculum-questions#153]
def double_down(num, times_doubled):
    count = 0
    while (count < times_doubled):
        num *= 2
        count += 1
        return num
    else:
        return num
            
        This is my code. it doenst work when double_down (3,3) is called because it doesn't keep going in the loop.Please help.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/double-down

**User code**:
```python
def double_down(num, times_doubled):
    count = 0
    while (count < times_doubled):
        num *= 2
        count += 1
        return num
    else:
        return num
            
        
```

**Comment by jsymons** [comment]
The issue you're having is that you have your `return` statement inside the while loop. When the program reaches a return it **immediately** returns, stopping execution of the rest of the function, including breaking loops. You want to be returning *outside* your loop.

**Comment by ghost** [comment]
I'm also just getting this error: [cid:146fb78c-5870-42e8-b11b-deb74eaa60d0]



Sincerely,
Jennifer Arlene Payano
Bioinformatics and Computational Biology
WPI Class of 2019

Worcester Polytechnic Institute
100 Institute Road, Worcester MA  01609-2208

japayano@wpi.edu<https://wpi.edu/>
(781)346-5593 (M)


________________________________

**Comment by jsymons** [comment]
Going to need some more context than that. Is there anything else to the error message?

**Comment by ghost** [comment]
no it just shows behind the scene codes. It happened right after I asked the question

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by santiagobasulto** [comment]
Hey @Japayano! Your code looks great! I think this is just a "syntax" issue. We don't usually use `else` clauses in while loops. If I just take your `else` clause and leave the return:

```python
def double_down(num, times_doubled):
    count = 0
    while (count < times_doubled):
        num *= 2
        count += 1
    return num
```

your code works! 🎉

**Comment by santiagobasulto** [comment]
And just for reference. This is going to be common during these first couple of weeks. The "algorithm" was perfect in your head. The problem is just expressing it using Python's syntax.
