### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by cpjain2007** [rmotr-curriculum/base-python-curriculum-questions#154]
This is giving runtime error:
RuntimeError: dictionary changed size during iteration

Why this is throwing error here please?

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/censor-your-dictionary

**User code**:
```python
def censor_dictionary(unclean_dictionary, flagged_word):
    for k, v in unclean_dictionary.items():
        if flagged_word in v:
            unclean_dictionary.pop(k)
    return unclean_dictionary
```

**Comment by santiagobasulto** [comment]
Hey @cpjain2007. Great question! The answer is right there: 
> dictionary changed size during iteration

**DO NOT CHANGE YOUR COLLECTIONS WHILE YOU'RE ITERATING OVER THEM** 😬

It's a really important rule and it applies to every collection type.

Can you think of a way to refactor your code? An immutable version maybe?
