### ISSUE TITLE
Reason to use range rather than iterating through power

### ISSUE THREAD

**Issue by ama4coding** [rmotr-curriculum/base-python-curriculum-questions#158]
I am slightly lost on why to use range with this function. Please assist 

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/powers-of-2

**User code**:
```python
def powers_of_2(power):
    result = 1
    for i in power:
        result *= 2
    return result
```

**Comment by jsymons** [comment]
So doing `for i in power` doesn't work, we're going to assume that `power` is always an int, as we know that's what the tests are inputting. `int` objects are **not** iterable, thus you can't loop over them. What you instead want to do is use `range`.

If I do the following:
```python3
def print_hello_num_times(num):
    for i in range(num):
        print('hello')

print_hello_num_times(5)
```
I am going to get the following output:
```
hello
hello
hello
hello
hello
```

What `range(x)` is going to do is give an iterable that contains all the numbers from 0 up to but not including `x`. You can also do more advanced things with range as it takes up to three parameters: `range(start, stop, step)` `start` is the number to start at, `stop` is the number to stop before, and `step` is how much to advance each iteration. For example `range(2, 100, 2)` would give an iterable that starts at 2, stops before it reaches 100, and increases the number by 2 each time, in other words it's going to give us every even number under 100.
