### ISSUE TITLE
Not sure what the next step 

### ISSUE THREAD

**Issue by ama4coding** [rmotr-curriculum/base-python-curriculum-questions#159]
I know how to reverse the list, but not subtract

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/subtract-reversed

**User code**:
```python
def subtract_reversed(a_list):
    if len(a_list) == 0:
        return 0
    
    result = a_list[-1]
    
    while list_nums >= a_list:
        result += list_nums
    return result
```

**Comment by santiagobasulto** [comment]
Hey Andre! What is `list_nums` in your code?

**Comment by ama4coding** [comment]
Hi Santiago,

I did indeed forget to assign a variable in to list_nums, but am still unsure of what steps to take next. I will try during mentor hours.

**Comment by santiagobasulto** [comment]
Hey, great to know it worked Andre!
