### ISSUE TITLE
Why not elif?

### ISSUE THREAD

**Issue by qodetinker** [rmotr-curriculum/base-python-curriculum-questions#16]
For this challenge, could you explain why elif would not be the solution to use? Seemed logically that would be able to find which parameter was the greatest.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/greatest-parameter

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
I think an elif makes sense Philip, can you share the code you were thinking of?

**Comment by qodetinker** [comment]
It is pretty much the same as the solution, but with elifs. I used pythontutor.com to step through the code and it only returns 4 when I put in the parameters below.

```python
def greatest_parameter(a, b, c, d, e):
    highest = a
    
    if b > highest:
        highest = b
    elif c > highest:
        highest = c
    elif d > highest:
        highest = d
    elif e > highest:
        highest = e
    return highest
    
greatest_parameter(2, 4, 9, 1, 1)
```

**Comment by santiagobasulto** [comment]
Ah, I understand. The problem is that `elif` will "short circuit" and stop after it finds one of them evaluating to True.

if you do:

```python
if 4 > 2:
    # case 1
elif 9 > 4:
    # case 2
```

in this example, `case 2` is never executed, because the first one already evaluated to True. You just need to use regular `if` statements:

```python
def greatest_parameter(a, b, c, d, e):
    highest = a
    
    if b > highest:
        highest = b
    if c > highest:
        highest = c
    if d > highest:
        highest = d
    if e > highest:
        highest = e
    return highest
```
