### ISSUE TITLE
Correct answer

### ISSUE THREAD

**Issue by mattmm41286** [rmotr-curriculum/base-python-curriculum-questions#162]
Is this a fine way to do it, or should I be doing it like the solutions offered?  

**Assignment**: http://learn.rmotr.com/python/base-python-track/modules-and-packages/get-variance-from-list

**User code**:
```python
import statistics


def get_variance_from_list(a_list):
    return statistics.variance(a_list)
print(get_variance_from_list([1,3,8,4,22]))
```

**Comment by santiagobasulto** [comment]
It's fine Matt! Actually, quite clever. If you have a second try doing it manually, but just for the kicks of practicing.
