### ISSUE TITLE
What is wrong with my code?

### ISSUE THREAD

**Issue by mrbaker1917** [rmotr-curriculum/base-python-curriculum-questions#164]
Just cannot get my code to work. I keep getting a return of "None"

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/help-a-string-get-lucky

**User code**:
```python
def get_lucky(poor_string, lucky_number):
    x = 0
    while x < lucky_number:
        poor_string += "7"
        x += 1

print(get_lucky("dog", 5))
```

**Comment by santiagobasulto** [comment]
You're not explicitly returning anything in your function. You probably need to `return poor_string` after you're done appending `7`s.

**Comment by mrbaker1917** [comment]
Thanks, Santiago. I figured that out a few minutes after I sent the
question, but I could not figure out how to cancel the question.

Take care Mark

**Comment by santiagobasulto** [comment]
Hehe, no problem. Welcome to Github! I'll close the issue then.
