### ISSUE TITLE
Dividing len(string) by two

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/base-python-curriculum-questions#166]
I thought that using the division symbol '/' (forward slash) between two int values always gives you an int answer. Since when does it return a float value?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/first-half

**User code**:
```python
string = 'abcdefg'

len(string)/2

print(len(string/2))

#returns 3.5, not 3 as I expected.
```

**Comment by jsymons** [comment]
In Python 3.x `/` defaults to float division
