### ISSUE TITLE
Mutable & Immutable

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/base-python-curriculum-questions#167]
I find that the use of the two terms in the lessons is a bit different from some of the other readings where I've seen the terms used exclusively as properties of objects (e.g. tuples are immutable, lists and mutable). Can I please get clarification on this?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-1/other-list-operations

**Comment by santiagobasulto** [comment]
Yes, for sure! It is correct to refer to certain collections as mutable or immutable. That's kind of the most important trait of the collection. But it's also used when we evaluate different "solutions". For example, I have to build a sorting algorithm, I could create both, a mutable and an immutable solution:

```python
def sort_list_mutable(a_list):
    pass

def sort_list_immutable(a_list):
    pass
```

`sort_list_immutable` receives a list and returns a NEW list sorted (with the same elements of the original one. `sort_list_mutable` receives a list and sorts it in place, modifying the list passed.

Makes sense?

**Comment by jjk235** [comment]
Yes thank you! but still, I'm really not a fan of the way immutable & mutable solutions are differentiated here. it seems to cause more confusion than remove it, really. For example you said in one of your lessons that concatenation with just + would be considered immutable since you can do list3 = list1+list2, where list1 and list2 are unchanged and hence immutable. but in the example after, it's mentioned that list1+=list2 would be considered mutable. It's confusing that even for the same operator, a solution can be said to be mutable or immutable... perhaps it's best if the terms are reserved to describe properties of objects exclusively
