### ISSUE TITLE
Not sure why I am getting this error: 

### ISSUE THREAD

**Issue by DaiBando** [rmotr-curriculum/base-python-curriculum-questions#168]
I have written the below code as the answer to the assignment and it works ( having tried it out both in the class simulator as well as pythontutor.com) yet when I try and submit it as completed, the following Type error pops up:

tests.py:34: in test_with_large_string
    assert reverse_string('Python is Awesome') == 'emosewA si nohtyP'
E   TypeError: 'str' object is not callable

It as gives the same error for the other assignment submitted in the same test case, just a different tests.py:38 line.

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/reverse-a-string

**User code**:
```python
message = "Python is Awesome"
reverse_string = message [::-1]

    

message2 = 'Python'
reverse_string = message2 [::-1]
```

**Comment by jsymons** [comment]
You're supposed to write a *function*  `reverse_string` that is supposed to `return` the reversed string. What you're doing here is just reversing the string and assigning that value to the variable `reverse_string`

**Comment by DaiBando** [comment]
def test_with_large_string():


    message = "Python is Awesome"
        reverse_string = message [::-1]
        return reverse_string

    Hi Jason,
Here is the code I wrote. I believe I am on the right track however I keep getting an indentation error (copied below for your preview) that, no matter how I move the code, it continues to give me the same indentation error. I have moved the entire block of code back and forth, from the first line to four spaces, eight spaces and everywhere in between.

Thoughts?

=================

def test_with_short_string():
    
    message2 = 'Python'
        reverse_string = message2 [::-1]
        return reverse_string


/usr/local/lib/python3.6/site-packages/_pytest/python.py:408: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/local/lib/python3.6/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
E     File "/app/tests.py", line 24
E       reverse_string = message [::-1]
E       ^
E   IndentationError: unexpected indent

**Comment by jsymons** [comment]
You should be structuring it similar to something like this:

```python
def reverse_string(a_string):
    # do something
    return # something
```
