### ISSUE TITLE
import module

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/base-python-curriculum-questions#169]
I was wondering why a module that looks as important and useful as string and random have to be imported before being used. Why are they not just always readily available? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-1/iterating-lists

**Comment by jangeador** [comment]
Those are decisions made by the python development team. Only a few modules are built in to prevent python from loading unnecessary code. 

In the case of `string`, part of the module is built into python and in most cases you don't need to import it except when you need to use the string constants, such as, `string.digits` or `string.ascii_letters`.

The official python documentation has some really good information about builtin modules as well as methods to find out which modules are included. https://docs.python.org/3.3/tutorial/modules.html#tut-standardmodules
