### ISSUE TITLE
Returning the index position of a duplicate character in a string

### ISSUE THREAD

**Issue by VentusN** [rmotr-curriculum/base-python-curriculum-questions#17]
Is there a way to return the correct position of a duplicate character in a string? I am trying to see if the index of the char in a_string is such that I should add a dash, but for the char that repeats more than once in a_string, the index() method returns the position of the first char that it encounters.... (Line 5 of my code)

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/insert-dashes-every-3-characters

**User code**:
```python
def insert_dashes(a_string):
    dashed = ""  
    for char in a_string: #loop over the string
        dashed += char #add a character to the string as you loop over it
        if a_string.index(char) in range(2,len(a_string),3): #check if the index number is such that you should add a dash
            dashed += '-' 
    return dashed
```

**Comment by santiagobasulto** [comment]
No, it's actually tricky. You can start iterating the string, and splitting it in the places where you find that char. And then offsetting the position of the individual part.

**Comment by santiagobasulto** [comment]
Nevertheless, this should be a little bit easier to solve. For example, using enumerate and seeing if the current index is a multiple of 3
