### ISSUE TITLE
Why won't my tuple conversion work?

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/base-python-curriculum-questions#170]
I'm trying to add to the list with the list from a_dict.items() converted to tuples.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/dict-to-tuple

**User code**:
```python
def dict_to_tuple(a_dict):
    new_list = []
    if a_dict=={}:
        return new_list
    for c in a_dict.items():
        new_list+=tuple(c)
    return new_list

```

**Comment by santiagobasulto** [comment]
Hello @jjk235! the `.items()` method returns 2 values. Are you receiving an error that says something like "Impossible to unpack"?

You just need to change your for loop for  `for key, value in a_dict.items():` instead of just `c`. Try it out and let me know!

**Comment by santiagobasulto** [comment]
And one more thing, you won't be able to concatenate a list and a tuple. Try using the `new_list.append`method instead of `+=`.

**Comment by jsymons** [comment]
@santiagobasulto `items` pops out tuples as it is so no need to unpack. The issue here looks to be that they're using `+=` instead of `append`.

**Comment by santiagobasulto** [comment]
True that @jsymons. @jjk235 updates? The people wants to know.

**Comment by jjk235** [comment]
yeah thanks. it seems that += was adding elements from t he collection so it doesn't matter if i'm +=ing tuple, lsit or whatever, changing it to append worked.
