### ISSUE TITLE
Is this working because it's creating a separate list in memory?

### ISSUE THREAD

**Issue by chromengel** [rmotr-curriculum/base-python-curriculum-questions#171]
I was getting this error: RuntimeError: dictionary changed size during iteration
My solution works (and very simple), but is this an acceptable solution?

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/censor-your-dictionary

**User code**:
```python
def censor_dictionary(unclean_dictionary, flagged_word):
    for key in list(unclean_dictionary):
        if flagged_word in unclean_dictionary[key]:
            del unclean_dictionary[key]
    return unclean_dictionary
```

**Comment by santiagobasulto** [comment]
Hello @blackappy! Number one rule of iteration and collections: **NEVER MODIFY COLLECTIONS WHILE YOU'RE ITERATING OVER THEM** 😁. 

In this case you're iterating over `unclean_dictionary` and deleting its keys as you progress. You're creating an "intermediate" list that prevents errors, but it's still not recommended.

The solution is MUCH SIMPLER: just create a new collection and return that one:

```python
def censor_dictionary(unclean_dictionary, flagged_word):
    new_dict = {}
    for key, value in unclean_dictionary.items():
        if flagged_word not in value:
            new_dict[key] = value
    return new_dict
```

Please note I'm "inverting" your condition. If the key does NOT have that flagged word, I copy it over to the new dict.

Makes sense?

**Comment by chromengel** [comment]
It makes sense.  Thanks!
