### ISSUE TITLE
unable to understand the problem

### ISSUE THREAD

**Issue by geetha10816** [rmotr-curriculum/base-python-curriculum-questions#172]
Can you please explain the problem. why do the tests fail for what i wrote below

def double_down(num, times_doubled):
    while (times_doubled > 0) :
        num *= num
        times_doubled = times_doubled-1
    
    return num 

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/double-down

**User code**:
```python
    def double_down(num, times_doubled):
        while (times_doubled > 0) :
            num *= num
            times_doubled = times_doubled-1
        
        return num 
```

**Comment by santiagobasulto** [comment]
The code looks correct @geetha10816. The indentation looks a little bit off. Can you paste the error message you're receiving?

**Comment by jsymons** [comment]
You're squaring instead of doubling. You should be multiplying by 2, not `num`.
