### ISSUE TITLE
Efficiency

### ISSUE THREAD

**Issue by geetha10816** [rmotr-curriculum/base-python-curriculum-questions#173]
Is below code efficient?
def double_down(num, times_doubled):
    while (times_doubled > 0) :
        num = num * 2
        times_doubled = times_doubled-1
    return num 

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/double-down

**User code**:
```python
def double_down(num, times_doubled):
    while (times_doubled > 0) :
        num = num * 2
        times_doubled = times_doubled-1
    return num 
```

**Comment by santiagobasulto** [comment]
Yes, it is. But don't worry about efficiency too much now. Famous quote:

> Premature optimization is the root of all evil
Donald Knuth
