### ISSUE TITLE
Subset operations

### ISSUE THREAD

**Issue by victorbizpetrol** [rmotr-curriculum/base-python-curriculum-questions#174]
I initially tried using the set operators for this problem, but they did not work because they are not recognized.  Why won't python recognize the set operators (|, &, -, >)?   I had to end up using the .union(), .difference(), etc.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/common-values

**User code**:
```python
# def common_values(list_1, list_2):
#     new_list = list_1 & list_2
#     return new_list

# assert common_values((1,2,3,4),(4,5,6,7,8)) == {1,2,3,4,5,6,7,8}

set1 = {1,2,3,4}
set2 = {4,5,6}
set3 = {1,2}

print(set1.union(set2))
print(set1.intersection(set2))
print(set1.difference(set2))
print(set3.issubset(set1))
```

**Comment by santiagobasulto** [comment]
Hello Victor! It should work, what error are you receiving? I'm trying a union with the same sets you've defined:

![image](https://user-images.githubusercontent.com/872296/44151671-a1245856-a079-11e8-827a-4ac56cffaf18.png)

What's the error you see? Maybe I'm missing something.
