### ISSUE TITLE
Is it ok to be using list comprehension instead of nested for loops?

### ISSUE THREAD

**Issue by chromengel** [rmotr-curriculum/base-python-curriculum-questions#175]
No issue at all, it just seems like list comprehension is the way to work through this series of problems.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/random-numbers-matrix

**User code**:
```python
import random


def random_matrix(m, n):
    matrix = [[random.randint(x, 100) for x in range(n)] for y in range(m)]
    return matrix
```

**Comment by santiagobasulto** [comment]
😳it's perfectly fine, just a little bit more advanced than what's expected 😅.
