### ISSUE TITLE
The rationale for storing data in collections

### ISSUE THREAD

**Issue by victorbizpetrol** [rmotr-curriculum/base-python-curriculum-questions#176]
I am just wondering what the rationale is for storing data in collections and using python to access the data.  Wouldn't this data be stored in a database somewhere and you query the database with sql and then pass the results to someone, something, or a program?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/nested-collections

**Comment by jsymons** [comment]
There are many times that using a database is going to be either overkill or not make much sense. Plus when you get days out of a database it generally is going to be in a row which naturally fits into a collection.

Example where the data doesn't fit into retrieving from a database. User accesses website and submits a form, Python is handling the backend, that form data is going to come in in the form of a collection before you can even store it in a database.

Collections aren't permanent data storage the way a database is. There are many times when you need stuff in an easily accessible and iterable format and that's where collections come into play.

**Comment by santiagobasulto** [comment]
@victorbizpetrol great question. The difference between the usage of collections in Python and databases are the same as "Python vs Databases". 

Data is stored in databases for "long term" purposes, with some important goals in mind: consistency, integrity, durability. It is "harder" to manipulate or access the data within a database. For example, how can you check the cointegration of two assets having their prices stored in the database? There's probably some advanced database engine that provides those functions, but it's not so common.

The answer is, pull the data from the database, store it in numpy arrays (or python lists) and use statsmodels to measure cointegration. THERE is where you need Python collections. It's the intermediate "buffer" between, the data stored in the database and your final result or objectives expected.
