### ISSUE TITLE
What software is used in this video?

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/base-python-curriculum-questions#177]
It sort of went into an explanation for what to type in in order to create a new virtual environment without describing what this software is. Is it an IDE? Judging from the $ sign in the command prompt it seems to be the software used for the week 3 project but the readme for the project also doesn't describe where to put in those test commands with the $ sign.

**Assignment**: http://learn.rmotr.com/python/base-python-track/modules-and-packages/virtualenvs-and-3rd-party-modules

**Comment by santiagobasulto** [comment]
Hey @jjk235! To record this video we used [Cloud9 IDE](https://c9.io/). It's the same IDE we use during the class, starting the third week. It's an online IDE that gives you access to an Ubuntu (linux) machine on the cloud. We'll explain everything during class 😁
