### ISSUE TITLE
when using "while" and increment "index", how python knows index data type is integer and not a float

### ISSUE THREAD

**Issue by adilnaimi** [rmotr-curriculum/base-python-curriculum-questions#178]
while index < 5:
  

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/looping-over-strings

**Comment by santiagobasulto** [comment]
hey Adil! To be honest, it doesn't matter. the `< 5` condition works both with floats and integers. The long answer is that Python is a dynamic language, and types are assigned "on demand". If you initialized the variable as `index = 1`, python set it as an integer. If you keep adding integers to it `index += 4`, it'll keep the type. You can still add floats `index += 3.2`, and now index will contain a float. Makes sense?

**Comment by adilnaimi** [comment]
got it. 

thank you Santiago
