### ISSUE TITLE
Test not working: Test Only One Char In Even Positions 

### ISSUE THREAD

**Issue by VentusN** [rmotr-curriculum/base-python-curriculum-questions#18]
I am able to pass all tests, except for the "Test Only One Char In Even Positions". When I try to run it in Learn platform, all I get is the spinning wheel of death... I ran the code in the Python Tutor and repl.it and it works as expected so I am not sure what the issue is....

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/count-in-even-odd-positions

**User code**:
```python
def count_in_position(a_string, a_char, position_type):
    lis_even=[]
    lis_odd=[]
    count=0
    for i in range(0,len(a_string)):
        if  i % 2 ==0:
            lis_even += a_string[i]
        else:
            lis_odd +=a_string[i]
    if position_type is "even":
        count=lis_even.count(a_char) 
    else:
        count=lis_odd.count(a_char) 
    return count

assert count_in_position('abXXcdeXfX', 'X', 'even') == 1 
print("Hooraay, it works")
```

**Comment by santiagobasulto** [comment]
👍 @VentusN thanks, I'll check in a sec.

**Comment by martinzugnoni** [comment]
Ok, I found the issue. We had two test cases with the same name, which were making the build fail. @VentusN it seems to be fixed now. Can you please double check?
