### ISSUE TITLE
Cannot for the life of me figure out why this isn't working

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/base-python-curriculum-questions#180]
It's raising the error, just not passing the pytest. Help would be appreciated, thank you!

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/nice-moves

**User code**:
```python
class InvalidSymbolException(Exception):
    pass

:
    pass


def validate_tic_tac_toe_move(symbol, position_x, position_y):
    if symbol != 'X' or symbol != 'O':
        raise InvalidSymbolException()
    if (position_x != 1 and position_x != 2 and position_x !=0 and 
    position_y != 0 and position_y != 1 and position_y != 2):
        raise InvalidPositionException()
```

**Comment by santiagobasulto** [comment]
Hey @jjk235! Does the exception look like this?

```python
class InvalidSymbolException(Exception):
    pass

:
    pass

```
That might be an error. Also, you must define 2 exceptions: `InvalidPositionException` and `InvalidSymbolException `.

**Comment by jjk235** [comment]
Yeah that's weird that the code didn't copy paste properly... I did define both. Here's another attempt at copy pasting the code


class InvalidSymbolException(Exception):
    pass


class InvalidPositionException(Exception):
    pass


def validate_tic_tac_toe_move(symbol, position_x, position_y):
    if symbol != 'X' or symbol != 'O':
        raise InvalidSymbolException()
    if (position_x != 1 and position_x != 2 and position_x !=0 and 
    position_y != 0 and position_y != 1 and position_y != 2):
        raise InvalidPositionException()
   

# I can't make the indentation show up :(

**Comment by jjk235** [comment]
nvm my boolean statement is completely off... sorry bout that! I'll go hide under a rock now.
