### ISSUE TITLE
Exception vs Boolean | Change State

### ISSUE THREAD

**Issue by Jappandy** [rmotr-curriculum/base-python-curriculum-questions#182]
Is is better to use Exceptions over Booleans when triggering a change state?

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/custom-exceptions

**Comment by santiagobasulto** [comment]
Great question @Jappandy! It really depends. If you're in full charge of the project, you can use exceptions, and they're a great mechanism to ensure the robustness of your code. If there's any change of state that's not contemplated, the exception will expose it.

But you need to be working with people that really know what they're doing to handle it properly.

**Comment by Jappandy** [comment]
I see - very cool stuff.
