### ISSUE TITLE
wonder why my code doesn't work 

### ISSUE THREAD

**Issue by adilnaimi** [rmotr-curriculum/base-python-curriculum-questions#184]
```
def censor_dictionary(unclean_dictionary, flagged_word):
    copyOfDict = dict(unclean_dictionary)
    for key, value in copyOfDict.items():
        if flagged_word in value:
            del unclean_dictionary[key]
    return unclean_dictionary
```

when I run the code, it gives me memory address instead of data:
```
def censor_dictionary(unclean_dictionary, flagged_word):
    copyOfDict = dict(unclean_dictionary)
    for key, value in copyOfDict.items():
        if flagged_word in value:
            del unclean_dictionary[key]
    return unclean_dictionary
        
expressions = {
    "pumped": "I'm so darn excited!",
    "happy": "Yeehaw",
    "agreeable": "darn tootin!"
}

censor_dictionary(expressions, "darn")

print(censor_dictionary)
```

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/censor-your-dictionary

**User code**:
```python

```

**Comment by OneDevGuy** [comment]
Your print statement is after the function has already run.
when you call the function you can put it inside print like this.
`print(censor_dictionary(expressions, "darn"))`

**Comment by santiagobasulto** [comment]
Hey @adilnaimi! You're choosing the correct approach, but the "error" is probably related to deleting from the original dictionary. We try NOT to modify exiting datastructures. It's much better to create new ones instead. Something like: 

```python
def censor_dictionary(unclean_dictionary, flagged_word):
    result_dict = {}
    for key, value in unclean_dictionary.items():
        if flagged_word not in value:
            result_dict[key] = item
    return result_dict
```

It's pretty much the same result, with the inverted logic. If the flagged word is NOT present in the value, we add it to the new resulting dict. Makes sense?

**Comment by adilnaimi** [comment]
thanks @santiagobasulto I was trying to avoid iteration over the same dictionary and delete occurrence, as for the second iteration the dictionary number of items will change.
