### ISSUE TITLE
string formatting question

### ISSUE THREAD

**Issue by victorbizpetrol** [rmotr-curriculum/base-python-curriculum-questions#186]
For this problem, I could not figure out what formatting with {b:g} does.  I tried looking it up in the Python Standard Library but could not find it.  Can you explain?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-oop/points-and-lines

**User code**:
```python
# Define Point class here
class Point(object):
    def __init__(self, x, y):
        self.x = x
        self.y = y  

# Define Line class here
class Line(object):
    def __init__ (self, p1, p2):
        self.p1 = p1
        self.p2 = p2
    
    def slope(self):
        return (self.p2.y - self.p1.y) / (self.p2.x - self.p1.x)
    
    def y_intercept(self):
        m = self.slope()
        return self.p1.y - (m * self.p1.x)
    
    def formula(self):
        formula_string = 'y = {m}x + {b:g}'
        m = self.slope()
        if m == 1:
            m = ''
        return formula_string.format(m=m, b=self.y_intercept())
        
        return 

        
```

**Comment by santiagobasulto** [comment]
Great question Victor. Formatting is a world on its own. Specially useful for advanced reporting. The `g` modifier is useful to specify the precision to which you want to represent the numbers.

Here's an example: https://repl.it/@santiagobasulto/GrandTrimScience (as you can see, the default precision is 6 and extra 0s are deleted).

From [the docs](https://docs.python.org/3/library/string.html#format-specification-mini-language): 


> General format. For a given precision p >= 1, this rounds the number to psignificant digits and then formats the result in either fixed-point format or in scientific notation, depending on its magnitude.The precise rules are as follows: suppose that the result formatted with presentation type 'e' and precision p-1 would have exponent exp. Then if -4<= exp < p, the number is formatted with presentation type 'f' and precision p-1-exp. Otherwise, the number is formatted with presentation type 'e'and precision p-1. In both cases insignificant trailing zeros are removed from the significand, and the decimal point is also removed if there are no remaining digits following it.Positive and negative infinity, positive and negative zero, and nans, are formatted as inf, -inf, 0, -0 and nan respectively, regardless of the precision.A precision of 0 is treated as equivalent to a precision of 1. The default precision is 6.
