### ISSUE TITLE
p1 and p2 in Line's init

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/base-python-curriculum-questions#188]
What is the purpose of having p1 and p2 in Line's init list of parameters?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-oop/points-and-lines

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
It's the way a "line is constructed". A "Line object" exists only when you specify those two points. So then other methods, like `line.slope()` will use p1 and p2 to work.
