### ISSUE TITLE
I am lost

### ISSUE THREAD

**Issue by sswarowsky** [rmotr-curriculum/base-python-curriculum-questions#19]
I had to get this code from a friend because I was getting no where.... it still doesn't work and I am lost. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/first-half

**User code**:
```python
def first_half(a_string):
  if(len(a_string) % 2 == 0):
        return a_string[(int(len(a_string) / 2) - 1 )]
  else:
        return a_string[(int(len(a_string)/2))]


assert first_half('abcdef') == 'abc'
assert first_half('abcXdef') == 'abcX'


print ("It Worked")
```

**Comment by santiagobasulto** [comment]
Hey Sean! Let's walk it together and see if after simplifying it it makes sense. Given the following two strings:

```python
s1 = 'abcdef'
s2 = 'abcXdef'
```

How do you get `'abc'` for `s1` and `'abcX'` for `s2`? Just using numeric indexes, no variables.

**Comment by santiagobasulto** [comment]
Sean, just for reference, this is the way you'd do it:

```python
s1 = 'abcdef'
s2 = 'abcXdef'

print(s1[:len(s1) / 2])
print(s2[:(len(s2) / 2) + 1])
```

Do you see the pattern? If the string has an even number of chars, you use the solution for `s1`, if it's odd, you can use the on in `s2`.
