### ISSUE TITLE
other way of updating a DICT ?

### ISSUE THREAD

**Issue by mikoumed** [rmotr-curriculum/base-python-curriculum-questions#195]
Is there any other way to add 'Django Web Development' to courses list without retyping the hole list?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/updating-a-dictionary

**User code**:
```python
rmotr_dict = {
    'name': 'RMOTR',
    'courses': ['Intro to Python', 'Advanced Python'],
}

rmotr_dict.update({
    'name': 'rmotr.com',
    'email': 'questions@rmotr.com',
    'courses': ['Intro to Python', 'Advanced Python', 'Django Web Development']
})
```

**Comment by jsymons** [comment]
You can reference the list via `rmotr_dict['courses']` so to add to that list you can just do `rmotr_dict['courses'].append("Django Web Development")`
