### ISSUE TITLE
User of super in this exercise

### ISSUE THREAD

**Issue by victorbizpetrol** [rmotr-curriculum/base-python-curriculum-questions#196]
Why did you use super(Cow, self).__init__(name) in the solution when self.name = name works as well?

**Assignment**: http://learn.rmotr.com/python/base-python-track/oop-inheritance/cow-says-moo

**User code**:
```python
class Animal(object):
    def __init__(self, name):
        self.name = name

    def talk(self):
        return "{} says {}".format(self.name, self.sound)

class Cow(Animal):
    def __init__(self, name):
        self.name = name
        self.sound = "moo"


class Sheep(Animal):
    def __init__(self, name):
        self.name = name
        self.sound = "baaaaa"

class Fox(Animal):
    def __init__(self, name):
        self.name = name
        self.sound = "Ring-ding-ding-ding-dingeringeding"


cow = Cow('Bessie')
sheep = Sheep('Fuzzy')
fox = Fox('Red')

# print(cow.sound)
# print(sheep.sound)
# print(fox.sound)

# print(cow.talk())

assert isinstance(cow, Animal)
assert isinstance(sheep, Animal)
assert isinstance(fox, Animal)

assert cow.sound == "moo"
assert sheep.sound == "baaaaa"
assert fox.sound == "Ring-ding-ding-ding-dingeringeding"

# assert cow.talk() == "Bessie says moo"
# assert sheep.talk() == "Fuzzy says baaaaa"
# assert fox.talk() == "Red says Ring-ding-ding-ding-dingeringeding"
```

**Comment by jsymons** [comment]
That defeats the point of inheritance. For example if we wanted to change the behavior of how we treated the `name` parameter we would then have to make the change four times, once each in `Animal`, `Cow`, `Sheep`, and `Fox`. If we inherit properly using `super` that change would instead only have to be made once. The inherited classes should only implement things that *differ* from the base class, anything that is shared should be implemented in the base.
