### ISSUE TITLE
counting the element multiple times

### ISSUE THREAD

**Issue by mikoumed** [rmotr-curriculum/base-python-curriculum-questions#197]
Each time i am looking for a "a" I iterate over all the list even if the "a" is in the tail of the list and had already been counted. I mean when using python tutor i can see that after 108 iteration i had already the right result but the script had to continue.
I their any way to stop my code using useless calculations. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/count-occurrences

**User code**:
```python
def count_occurrences(a_list):
    result = {}
    for i in a_list:
        j = 0
        count = 0
        while j <= len(a_list)-1:
            if i == a_list[j]:
                count += 1
                j += 1
            else: 
                j += 1
        result[i] = count
    return result
```

**Comment by jsymons** [comment]
I think you may be overthinking things here. You can solve this with a single loop through the list.
```python
def count_occurrences(a_list):
    result = {}
    for i in a_list:
        result.setdefault(i, 0)
        result[i] += 1
    return result
```
If you're not familiar with `setdefault` it's extremely useful:
```python
my_dict = {}
my_dict.setdefault('my key', 'default value')
```
is the same as
```python
my_dict = {}
if 'my key' not in my_dict:
    my_dict['my key'] = 'default value'
```
