### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by sswarowsky** [rmotr-curriculum/base-python-curriculum-questions#20]
Need Help

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/how-many-times

**User code**:
```python
def how_many_times(a_string, a_word):
  return a_string().split().count(a_word)
  
  
  
   
    
assert how_many_times("Python is a great language.", "Ruby") == 0
#assert how_many_times(phrase, "Python") == 1
#assert how_many_times(phrase, "Python") == 2
```

**Comment by santiagobasulto** [comment]
Almost there! you don't need to split. Just do `a_string().count(a_word)`. Makes sense? please close the issue if resolved.

**Comment by hina-s** [comment]
def how_many_times(a_string, a_word):
total=0
    
    if a_word in a_string:
        total += 1

    return total
    

It doesn't work for the last test case.

**Comment by jsymons** [comment]
That's because `if a_word in a_string` is only going to ever trigger once, thus total will never be higher than 1, as stated above it's better to use `count`. Also it would be better if you opened a new issue instead of commenting on an old closed one.

**Comment by hina-s** [comment]
Thanks. I'm new to the rmotr website so didn't know where to post the question!
