### ISSUE TITLE
No dashes in result

### ISSUE THREAD

**Issue by yousafmufc** [rmotr-curriculum/base-python-curriculum-questions#201]
Hi why are no dashes appearing in my code even when count % 3 == 0? Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/insert-dashes-every-3-characters

**User code**:
```python
def insert_dashes(a_string):
    
    count = 0
    result = ''
    for c in a_string:
        if count + 1 % 3 == 0:
            result += c + "X"
        else:
            result += c
            
        count += 1
        
    return result
    
    

        
        
```

**Comment by santiagobasulto** [comment]
Hello @yousafmufc! There's just a REALLY tiny issue :) The order of operands. Try surrounding your if statement with parenthesis: `if (count + 1) % 3 == 0:`

**Comment by yousafmufc** [comment]
Thank you Santiago. I didn't think of that.
