### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by Jojo929** [rmotr-curriculum/base-python-curriculum-questions#202]
It gives a message as AttributeError saying 'Cookie' class does not has scarf_color&buttons_color. I understand they are not attributes in the class, but there are parameters pass from outside of the class. Why it doesn't work?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/class-and-instance-attributes

**User code**:
```python
class Cookie(object):
    DEFAULT_SCARF_COLOR = 'Green'
    DEFAULT_BUTTONS_COLOR = 'Blue'
    
    def __init__(self, scarf_color=None, buttons_color=None):
        if not scarf_color:
            self.scarf_color = self.DEFAULT_SCARF_COLOR
        if not buttons_color:
            self.buttons_color = self.DEFAULT_BUTTONS_COLOR
    pass
```

**Comment by santiagobasulto** [comment]
Hello Jojo! You should ALWAYS set the attribute, even if it's none (and you can remove the `pass`):

```python
def __init__(self, scarf_color=None, buttons_color=None):
        self.scarf_color = self.DEFAULT_SCARF_COLOR
        self.buttons_color = self.DEFAULT_BUTTONS_COLOR
 
```
