### ISSUE TITLE
Appending in return

### ISSUE THREAD

**Issue by yousafmufc** [rmotr-curriculum/base-python-curriculum-questions#203]
Why would append not work directly in the return line?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-1/append-to-list

**User code**:
```python
def append_to_list(hungry_list, data):
    
    return hungry_list.append(data)
```

**Comment by jsymons** [comment]
The append method does not return anything, thus putting it directly in the return statement means the return also doesn't return anything. The tests expect your function to return the list.

**Comment by yousafmufc** [comment]
Thank you. That makes sense.
