### ISSUE TITLE
Restate the problem

### ISSUE THREAD

**Issue by chromengel** [rmotr-curriculum/base-python-curriculum-questions#204]
I'm having a hard time understanding what the problem to be solved is.  Would it be possible to restate it?

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/count-lines-starting-with-each-letter

**User code**:
```python

```

**Comment by martinzugnoni** [comment]
Sure! You will have a file containing a single word per line. You need to count, how many lines start with each letter, and return a collection like this:

```
counter_by_letter('words.txt')  
# {
'a': 2,
'b': 10,
'c': 0,
...
'z': 1
}
```

That means, for example, that only 2 lines start with the letter "a".

You need to return the counter for each letter from a-z, even if the counter for one letter is 0.

Hope it makes sense.

**Comment by chromengel** [comment]
I'm an idiot.  The title says exactly what I was missing.  Lol.  Thanks.

**Comment by martinzugnoni** [comment]
Haha, no worries. You are welcome!
