### ISSUE TITLE
code contained in the solution

### ISSUE THREAD

**Issue by victorbizpetrol** [rmotr-curriculum/base-python-curriculum-questions#205]
I am trying to understand what is happening in this line of code:  "result[line[0]] += 1", which is line 8 below.

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/count-lines-starting-with-each-letter

**User code**:
```python
import string

def counter_by_letter(filepath):
    result = dict([(letter, 0) for letter in string.ascii_lowercase])
    with open(filepath) as fp:
        read_data = fp.readlines()
        for line in read_data:
            result[line[0]] += 1
        return result
```

**Comment by jsymons** [comment]
`line[0]` is going to be the first character in that line of the file, therefore it's going into `result` which we've already initialized with all the letters of the alphabet and increasing the count for that letter by one.

Hope this helps clear things up.
