### ISSUE TITLE
Why does this return 0 every time?

### ISSUE THREAD

**Issue by ColemanSWE** [rmotr-curriculum/base-python-curriculum-questions#208]
I'm having massive issues grasping for loops, it seems. I understand them simply but when I try to implement them myself, I'm often having to do tons of googling or flip to the suggested solution(s) to see where I'm going wrong. 
For some reason in this that I'm writing here, the variables don't seem to be incrementing as I want them to even though I'm telling them to when the met conditions are true. Do I just need to go back over for loops or is there more fundamentally wrong here?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/count-in-even-odd-positions

**User code**:
```python
def count_in_position(a_string, a_char, position_type):
    if position_type == "even":
        even_count = 0
        even_position = 0
        for even in a_string:
            if even == a_char and even_position != 0 and even_position % 2 == 0:
                even_count += 1
                even_position += 1
        return even_count
    if position_type == 'odd':
        odd_count = 0
        odd_position = 0
        for odd in a_string:
            if odd == a_char and odd_position != 0 and odd_position % 2 == 0:
                odd_count += 1
                odd_position += 1
        return odd_count
```

**Comment by jsymons** [comment]
Your if statements in your for loops contain either `even_position` or `odd_position` `!= 0` however you initialize both of those variables to 0 before you enter the for loops. Therefore your if statement never evaluates to true.

Hope that helps.
