### ISSUE TITLE
Help understanding the given solution

### ISSUE THREAD

**Issue by yousafmufc** [rmotr-curriculum/base-python-curriculum-questions#209]
I wrote the code below and it works. I am just having a hard time understanding how the code in the solution given solution works. Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/dictionary-keys-and-values

**User code**:
```python
def invert_dict(a_dict):
    
    new_dict = {}
    for key, value in a_dict.items():
        
        temp = key
        
        key = value
        
        value = temp
        
        new_dict[key] = value
        
    return new_dict
    
print(invert_dict({1: 'a'}))
```

**Comment by santiagobasulto** [comment]
You don't need all those variables, more clear it'd be:

```python
def invert_dict(a_dict):
    new_dict = {}
    for key, value in a_dict.items():
        new_dict[value] = key      
    return new_dict
```

just swaps keys for values 😬

**Comment by yousafmufc** [comment]
Thank you Santiago. bad habits from C language :D 

But can you help me understand the soluyion below:

def invert_dict(a_dict):
    return {value: key for key, value in a_dict.items()}

thanks.

**Comment by jsymons** [comment]
That's called a *comprehension*, we teach them later in the course so it probably shouldn't be listed as the solution. What's happening there is basically shorthand for:
```python
new_dict = {}
for key, value in a_dict.items():
    new_dict[value] = key
return new_dict
```
