### ISSUE TITLE
element 'none' in my lists

### ISSUE THREAD

**Issue by mikoumed** [rmotr-curriculum/base-python-curriculum-questions#210]
before using the     --> return get_element(used_elements) -------
is was using only get_element(used_elements) to recall the function. The problem is that in this case i was getting element none in my lists.  Can you explain please ? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/random-numbers-matrix

**User code**:
```python
import random

def get_element(used_elements):
    element = random.randint(0,100)
    if element in used_elements:
        return get_element(used_elements)
    return element
    
def random_matrix(m, n):
    
    result = []
    used_elements = []
   
    for vertical_element in range(m):
        intermediate_list = []
        for horizontal_element in range(n):
            new_element = get_element(used_elements)
            intermediate_list.append(new_element)
            used_elements.append(new_element)
        result.append(intermediate_list)
    return result
```

**Comment by jsymons** [comment]
Can you give us a full code block of what the `get_element` function looked like? From your description I'm not sure how you could have been getting `None` values in your lists.

**Comment by mikoumed** [comment]
With this code i am getting none elements, you may have to run it multiple times to get the none values

`import random

def get_element(used_elements):
      element = random.randint(0,100)
      if element not in used_elements:
             return element
      else:
             get_element(used_elements)
 
def random_matrix(m, n):
    result = []
    used_elements = []
    for vertical_element in range(m):
        intermediate_list = []
        for horizontal_element in range(n):
            new_element = get_element(used_elements)
            intermediate_list.append(new_element)
            used_elements.append(new_element)
        result.append(intermediate_list)
    return result

print(random_matrix(3,2))

**Comment by jsymons** [comment]
Ok, here's the problem with that, by just doing
```python
else:
    get_element(used_elements)
```
You're not actually doing anything with the result of that function, so since you're not returning anything your `get_element` function ultimately returns `None`, which is why you're getting `None` values in your matrix. Changing it to
```python
else:
    return get_element(used_elements)
```
Makes it return the result of the recursive `get_element`, eliminating the `None` results.
