### ISSUE TITLE
Why use 'range' or a 'for loop' at all?

### ISSUE THREAD

**Issue by lifeiswilde** [rmotr-curriculum/base-python-curriculum-questions#211]
Why use 'range' or a 'for loop' at all?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/powers-of-2

**User code**:
```python
def powers_of_2(power):
    return 2 ** power
```

**Comment by jsymons** [comment]
Yes using `**` is a better solution, however we're specifically trying to give people looping practice here.
