### ISSUE TITLE
Error: Dictionary changed size during iteration

### ISSUE THREAD

**Issue by yousafmufc** [rmotr-curriculum/base-python-curriculum-questions#213]
I don't understand why this is an issue. Need help please. Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/censor-your-dictionary

**User code**:
```python
def censor_dictionary(unclean_dictionary, flagged_word):
    
    clean_dictionary = {}
    
    for key, value in unclean_dictionary.items():
        
        if flagged_word in value:
            
            unclean_dictionary.pop(key)
            
 
    
    return unclean_dictionary
    
    
expressions = {
    "pumped": "I'm so darn excited!",
    "happy": "Yeehaw",
    "agreeable": "darn tootin!"
}

print(censor_dictionary(expressions, "darn"))
```

**Comment by jsymons** [comment]
You can't change the size of a dictionary (by calling `pop` for example) while iterating over it. Python doesn't let you and will throw an error if you try. I would instead look at building a new dictionary without the censored values. In general you should try to avoid mutating passed in parameters, it's better form to make a new copy and return that.
