### ISSUE TITLE
video_resources git

### ISSUE THREAD

**Issue by victorbizpetrol** [rmotr-curriculum/base-python-curriculum-questions#216]
the files contained in 2 - Cursor object to 5 - Insert, Delete, Update are not loading.  I tried loading it both from the RMOTR repo and the repo that I forked.  

**Assignment**: http://learn.rmotr.com/python/base-python-track/database-handling/python-and-sqlite

**Comment by santiagobasulto** [comment]
Github is terrible at parsing the HTML of notebooks :(, try these ones, I'll update the lessons: http://nbviewer.jupyter.org/github/rmotr-curriculum/intro-to-databases/tree/master/video_resources/
