### ISSUE TITLE
Can't figure this out....

### ISSUE THREAD

**Issue by chromengel** [rmotr-curriculum/base-python-curriculum-questions#218]
I tried to implement Andy's elegant solution, but I can't get past this error caused by :order_by.  When I hardcode DESC into the query, it works.  Thoughts?

**Assignment**: http://learn.rmotr.com/python/base-python-track/database-handling/get-best-and-worst-movies

**User code**:
```python
def get_best_and_worst_movies(db_connection, rating_type, order_dir, limit=5):

    cursor = db_connection.execute('SELECT title, :rating_type FROM marvel ORDER BY :rating_type :order_dir LIMIT :limit;', {
        'rating_type': rating_type,
        'limit': limit,
        'order_dir': order_dir
    })

    return cursor.fetchall()
```

**Comment by jsymons** [comment]
This shouldn't actually work even when hardcoding in ASC/DESC. Your use of `:rating_type` is going to break the code as that's going to be replaced with the `rating_type` passed into the function... *as a string* **complete with quotes around it**. The same thing goes for `:order_dir`
If I call this:
```python
get_best_and_worst_movies(db, 'tomatoes', 'ASC', limit=3)
```
This is the SQL that gets executed
```sql
SELECT title, 'tomatoes' FROM marvel ORDER BY 'tomatoes' 'ASC' LIMIT 3;'
```
This is **not** the same as
```sql
SELECT title, tomatoes FROM marvel ORDER BY tomatoes ASC LIMIT 3;
```
The quotes that get inserted break the SQL. Passing in parameters like that is meant to be used when supplying data for fields, it doesn't work like generic variables.
