### ISSUE TITLE
Why does my solution work locally but fails on rmotr?

### ISSUE THREAD

**Issue by lifeiswilde** [rmotr-curriculum/base-python-curriculum-questions#222]
**Interpreter Output**

```python
>>> def dict_to_tuple(a_dict):
...     return list(a_dict.items())
...
>>> dict_to_tuple({'a': 1, 'b': 2})
[('a', 1), ('b', 2)]
```

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/dict-to-tuple

**User code**:
```python
def dict_to_tuple(a_dict)
    return list(a_dict.items())
```

**Comment by jsymons** [comment]
The user code you've submitted is not the same as your interpreter output. You're missing the `:` at the end of your function definition which is causing a syntax error.

**Comment by lifeiswilde** [comment]
oops, thanks!
