### ISSUE TITLE
Why is this not passing? 

### ISSUE THREAD

**Issue by ColemanSWE** [rmotr-curriculum/base-python-curriculum-questions#224]
I have written and others way before finally checking the suggested solution to find that it's more or less identical. Why does this not pass?

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/nice-moves

**User code**:
```python
class InvalidSymbolException(Exception):
    pass

class InvalidPositionException(Exception):
    pass




def validate_tic_tac_toe_move(symbol, position_x, position_y):
    if symbol != 'X' or symbol != 'O':
        raise InvalidSymbolException()
    
    valid_positions = (0, 1, 2)
    if position_x not in valid_positions or position_y not in valid_positions:
        raise InvalidPositionException()
```

**Comment by jsymons** [comment]
So let's look at your first if statement:
```python
if symbol != 'X' or symbol != 'O':
    raise InvalidsymbolException()
```
This is **always** going to be true. If It's 'X' that means it's `!= 'O'`, if it's 'O' it's `!= 'X`'. To avoid this I would instead do something like `if symbol != 'X' and symbol != 'O':` or you could try `if symbol not in ('X', 'O'):`

If you need more clarification let me know.
