### ISSUE TITLE
Importing datetime as a whole

### ISSUE THREAD

**Issue by yousafmufc** [rmotr-curriculum/base-python-curriculum-questions#226]
Why does this not work if I'm just importing datetime library as a whole?

**Assignment**: http://learn.rmotr.com/python/base-python-track/modules-and-packages/counting-the-days

**User code**:
```python
# Import the library here!
import datetime

def counting_the_days(start_date, end_date):
    timedelta = end_date - start_date
    
    return datetime.timedelta.days
    


```

**Comment by jsymons** [comment]
A couple of things here, you need to look at the test to see why you can't just do `import datetime`.
```python
def test_counting_the_days():
    assert counting_the_days(date(1987, 9, 29), date(2017, 9, 29)) == 10958
```
It's expecting to be able to access `datetime.date` by just doing `date`. So if doing `import datetime` you  would have to do something like this:
```python
import datetime
date = datetime.date
```
It's cleaner however to just do:
```python
from datetime import date
```
As for your `return` statement you only need `return timedelta.days`, not `return datetime.timedelta.days`. When you subtract two `date`s you automatically get a timedelta object, you don't need to reference the class at `datetime.timedelta`.
