### ISSUE TITLE
the solution proposed has more code 

### ISSUE THREAD

**Issue by mikoumed** [rmotr-curriculum/base-python-curriculum-questions#227]
is my solution ok?
when finishing the exercice I looked at the proposed solution, it looks more complicated. Am I missing something in my solution?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-oop/cached-calculator

**User code**:
```python
class Calculator(object):
    
    def __init__(self):
        self.cache = {}
        
    def add(self, x, y):
        res = x + y
        tuple_result = (x, y ,res)
        if 'add' not in self.cache or tuple_result not in self.cache['add']:
            (self.cache.setdefault('add', [])).append(tuple_result)
        return res
        
    def subtract(self, x, y):
        res = x - y
        tuple_result = (x, y ,res)
        if 'subtract' not in self.cache or tuple_result not in self.cache['subtract']:
            (self.cache.setdefault('subtract', [])).append(tuple_result)
        return res
```

**Comment by jsymons** [comment]
Technically you're not really using the cache, you're just writing to it. The idea of having a cache is that once you perform an operation you don't have to do it again, you can just look up your previous result. It's not a big deal when you're just doing simple addition/subtraction, but say your operation took 5 minutes or even longer to do, you wouldn't want to do the full operation every time when you can just do it once instead.

If you need more clarification let me know.

**Comment by mikoumed** [comment]
got you, Thank youuu
