### ISSUE TITLE
Algorithm issues on finding a Prime and the next prime?

### ISSUE THREAD

**Issue by DataDogXIII** [rmotr-curriculum/base-python-curriculum-questions#228]
Tried to create my own algorithm to find a prime number but doesn't seem to work? I am not sure if I can stack conditions the way that I have and if it is considered clean.
Also the last algorithm I took from the answers and I am not sure how the computer is understanding the syntax .... "while true" ... what condition is true? Also, what is the purpose of the first "n+=1"?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python

# Try it on your own by uncommenting the following lines and hitting "Run Code"
# print(reverse_str('abc'))
# print(reverse_str('123'))
# print(reverse_str('121'))

def is_palindromic(n):
    return int(str(n)[::-1])== n
    
def is_prime(n):
     if n == (2 and 3 and 5):
        return True
     else:
        return (n % 5 and 3 and 2)!= 0 and n!=1

def next_palindromic_prime(n):
    n += 1
    #while not is_palindromic(n) and not is_prime(n):
    while True:
        if is_palindromic(n) and is_prime(n):
            return n
        n += 1
```

**Comment by santiagobasulto** [comment]
Hey @ReapsXIII! This is a really common issue. When you're using comparison operators, you need to explicitly state every comparison. For example, the following doesn't work:

```python
x = 10
if x < 5 and 9:
    pass
```
We'd read this "humanly" as _"if x is less than 5 and 9, then..."_. But Python needs the explicit comparisons in every place, in this way:

```python
x = 10
if x < 5 and x < 9:
    pass
```

Your line `return (n % 5 and 3 and 2)!= 0 and n!=1` is having this issue.

Also, to find the primes you'll probably need iterating.

**Comment by DataDogXIII** [comment]
is_prime in the solutions did not exclude 1, FYI.
