### ISSUE TITLE
Video not available for Indexing and Slicing

### ISSUE THREAD

**Issue by useraddmario** [rmotr-curriculum/base-python-curriculum-questions#23]
Video is not working

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-1/indexing-and-slicing

**Comment by martinzugnoni** [comment]
Thanks for pointing it out, Mario. We will fix it soon.

**Comment by martinzugnoni** [comment]
@useraddmario it seems that the video works now, but the preview img is still not loading. Seems to be just YouTube taking long to process the videos. We will keep an eye on them. Thanks for reporting.
