### ISSUE TITLE
Using With Open

### ISSUE THREAD

**Issue by ama4coding** [rmotr-curriculum/base-python-curriculum-questions#234]
So , should we always use <with open> rather than just <open> with files to avoid errors such as the inability to close a file? Or only for particular occasions?

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/the-with-context-manager

**Comment by jsymons** [comment]
Use `with` whenever you can. There are occasions when it just won't work because of what you're trying to do, but when you can use it your code will generally be cleaner if you do use it.
