### ISSUE TITLE
Logic of Anser

### ISSUE THREAD

**Issue by katanadxh49** [rmotr-curriculum/base-python-curriculum-questions#235]
Why are these answers wrong. In order to make the conditions match the assertion the below is correct.

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/valid-passwords

**User code**:
```python
# #### Don't change these passwords #### #
password_1 = 'Jhx85a'
password_2 = 'ajd2819adkBjld'
password_3 = '81$br&j#'
password_4 = 'kp03%$Ji19Br!rdV'
# #### Don't change these passwords #### #

# == Your Code Below == ##

## Is Long Enough
# Has at least 12 chars
is_long_enough_pwd_1 = len(password_1) >= 12  # False
is_long_enough_pwd_2 = len(password_2) >= 12  # True
is_long_enough_pwd_3 = len(password_3) <= 12  # True
is_long_enough_pwd_4 = len(password_4) >= 12  # True
```

**Comment by jsymons** [comment]
You're using `<=` instead of `>=` when checking `password_3`.

**Comment by katanadxh49** [comment]
The password_3 is not greater or equal to 12. The string is only 8 characters. Why is that not a true statement.

**Comment by katanadxh49** [comment]
The password_3 is not greater or equal to 12. The string is only 8 characters. Why is that not a true statement?

**Comment by jsymons** [comment]
As I said, the code you posted is checking if password 3 is less than or equal to 12 characters instead of greater than or equal to. The test expects the password 3 check to return `False` as we are checking if all the passwords are at least 12 characters.
