### ISSUE TITLE
Sound should be a class attribute or instance attribute? 

### ISSUE THREAD

**Issue by rdemint** [rmotr-curriculum/base-python-curriculum-questions#236]
My intuition was to make sound a class attribute.  To me this makes for more readable code compared to the solution provided, and they both pass (since the class attribute can be accessed from each instance with the same syntax).  

Are there drawbacks to the approach of using a class attribute?  Did you user super() because of those drawbacks or was the assignment just trying to get us to practice with super()?

**Assignment**: http://learn.rmotr.com/python/base-python-track/oop-inheritance/cow-says-moo

**User code**:
```python

```

**Comment by martinzugnoni** [comment]
The question you have to make yourself is "do I need to access any instance-level attributes inside the method?". In this case, you will need to access the Animal `name` attribute, that's why an instance method would be the correct way in this case.

Something like:
```
    def talk(self):
        return "{name} says {sound}".format(name=self.name, sound=self.sound)
```
