### ISSUE TITLE
'cls' in front of Cookies in line# 8

### ISSUE THREAD

**Issue by yousafmufc** [rmotr-curriculum/base-python-curriculum-questions#238]
Why doesn;t this code work with the way I have the line#8 defined. It starts with "cls". Don't we do something similar when initializing classes in general where we precede with "self"?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/cookie-factory

**User code**:
```python
class Cookie():
    
    @classmethod
    def create_cookies(cls, amount):
        Cookies = []
        
        for num in range(amount):
            cls.Cookies.append(cls())
        return Cookies
            
```

**Comment by jsymons** [comment]
Your append statement should instead be `Cookies.append(cls())` by putting the cls in front of it you were trying to refer to a class attribute instead of the `Cookies` variable you created.

**Comment by yousafmufc** [comment]
Oh I see that now. Thank you.
