### ISSUE TITLE
A comment.  The 'Comparison Operator' video has very poor resolution, it's not readable.

### ISSUE THREAD

**Issue by bluelou** [rmotr-curriculum/base-python-curriculum-questions#24]
A comment.  The 'Comparison Operator' video has very poor resolution, it's not readable.

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/comparison-operators

**Comment by santiagobasulto** [comment]
Hey Lou! Did you set the resolution in the player? I see it correctly:

![image](https://user-images.githubusercontent.com/872296/36067624-5893fa5e-0e9f-11e8-88e1-6425f09c058c.png)

Maybe if YouTube detects some latency in your collection, it defaults to 360 which SUUUUCKS.

**Comment by bluelou** [comment]
Santiago,
Maybe it was latency.  I was using satellite internet which has a ping of
around 900 ms.  But, this was the only video that wasn't readable.   Just
out of curiosity I'll give it a try on a fast internet connection on
Monday.  Thx.

**Comment by martinzugnoni** [comment]
I've tried watching it again, just in case, and the resolution looks great. It's actually displayed as HD. It was probably connectivity issues.
