### ISSUE TITLE
Cannot Complete exercise

### ISSUE THREAD

**Issue by kauaicrusier** [rmotr-curriculum/base-python-curriculum-questions#240]
The DONE button does not work so I cannot move on from this lesson showing it is complete.

**Assignment**: http://learn.rmotr.com/python/base-python-track/getting-started/your-first-python-test

**User code**:
```python
your_name = "David"
course = "RMOTR Python"

greeting_message = "Welcome {} to the {} course!".format(your_name, course)
print(greeting_message)

def test_name_is_long_enough():
    assert len(your_name) > 3, "Your name must have more than 3 characters"
    
def test_name_is_not_blank():
    assert your_name != '', "Your Name can't be blank!"
```

**Comment by jelenagav** [comment]
I'm encountering the same issue, did you find a solution?

**Comment by santiagobasulto** [comment]
What issue are you having @jelenagav ?

**Comment by F0R6E** [comment]
I am also having this issue. Has there been a resolution?

**Comment by martinzugnoni** [comment]
Hello @F0R6E, did you try going back to your student dashboard and opening the next task there? Not sure if I'm getting your problem correctly.

**Comment by F0R6E** [comment]
Hi Martin, the issue was when I clicked the "Done" button, nothing happened. I guess I expected it to move to the next lesson or something. You're correct though, if I return to my dashboard and refresh it shows as completed. Thanks!

**Comment by LeonithaF** [comment]
I'm having the same issue. The Done button isn't marking my assignment as complete.
