### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by jfricano** [rmotr-curriculum/base-python-curriculum-questions#241]
Where are the notes?

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/string-formatting

**Comment by thesophietran** [comment]
Here, you can find it on the github repo of the course:
https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-6-strings/lesson-3-string-formatting/String%20Formatting.ipynb
