### ISSUE TITLE
Is this solution ok or overkill?

### ISSUE THREAD

**Issue by yousafmufc** [rmotr-curriculum/base-python-curriculum-questions#244]
Hi I attempted this problem the following way. I saw the solution but is my method overkill or is it okay?

Also I'm not following what dict([(letter, 0) for letter in string.ascii_lowercase]) is doing. Can you please explain? is this list comprehension?

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/count-lines-starting-with-each-letter

**User code**:
```python
import string

dict_alph = {}

for char in string.ascii_lowercase:
    
    dict_alph[char] = 0
    


def counter_by_letter(filepath):
    

    with open(filepath) as fp:
        
        for line in fp.readlines():
            
            if line[0] in dict_alph.keys():
                dict_alph[line[0]] += 1
                
    return dict_alph
```

**Comment by jsymons** [comment]
This is actually very similar to the given solution, the dict_alph for loop is essentially a different method of writing the comprehension that's used in the solution, however it should be done *inside* of your function instead of outside.
