### ISSUE TITLE
Breakdown?

### ISSUE THREAD

**Issue by raghureddyram** [rmotr-curriculum/base-python-curriculum-questions#245]
Would someone  mind translating this from the list comprehension part to a nested for loop? I'm having trouble mapping this solution to what I would normally try to code

**Assignment**: http://learn.rmotr.com/python/base-python-track/functional-programming/divisible-numbers-comprehension-with-multiple-terms

**User code**:
```python
def divisible_numbers(a_list, a_list_of_terms):
    return [e for e in a_list if all([e % t == 0 for t in a_list_of_terms])]
    
# I think I would normally code the below, and try to turn that into a list comprehension. Having some trouble seeing where I would start with the list comp.
results = []
for e in a_list:
    for t in a_list_of_terms:
        results.append(e % t)
if all(res == 0 for res in results)

Is this how one would normally go about solving this, and then translating into the list comprehension?
```

**Comment by jsymons** [comment]
```python
results = []
for e in a_list:
    all_divisible = true
    for t in a_list_of_terms:
        if e % t != 0:
            all_divisible = false
            break
    if all_divisible:
        results.append(e)
return results
```
This more closely mimics the comprehension as if breaks the nested loop if there is any value that isn't `true`, which is how `all` is going to perform. What the comprehension is doing is for each `e` in `a_list` it is checking if `all` the terms(`t`) in `a_list_of_terms` divides evenly into `e`. If they do then `e` is added to the list that the comprehension outputs.
