### ISSUE TITLE
if given_name and given_name not in animal['given_name']

### ISSUE THREAD

**Issue by DataDogXIII** [rmotr-curriculum/base-python-curriculum-questions#246]
In the if statement why does given_name need to be used twice?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-functions/multi-search

**User code**:
```python

```

**Comment by jsymons** [comment]
I'm assuming you're referring to our posted solution:
```python3
if given_name and given_name not in animal['given_name']:
            continue
```
The first `given_name` is taking advantage of "falsely" values and is basically checking to make sure that `given_name` is not `None` before completing the rest of the if statement.
