### ISSUE TITLE
Invalid parameters in BOTH testcases

### ISSUE THREAD

**Issue by FredericoSol** [rmotr-curriculum/base-python-curriculum-questions#247]
I´m using the same system I used for the traffic lights exercise and it worked for me just fine, but in this one it doesnt seem it works. It just returns me 'invalid parameters' wheter I put integers in a and b or not. What is wrong?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/only-integers

**User code**:
```python
def add_only_integers(a, b):
    if type(a) == int and type(b) == int:
        return sum(a, b)
    else:
        return 'invalid parameters'
```

**Comment by martinzugnoni** [comment]
The built-in `sum` function is expecting to receive a list of numeric values. You should change your code to something like: `sum([a, b])`. Let me know if this works.

**Comment by FredericoSol** [comment]
Yeap, it was exactly that! Thanks :D
