### ISSUE TITLE
I tried this and it worked

### ISSUE THREAD

**Issue by Akataya** [rmotr-curriculum/base-python-curriculum-questions#248]
Is this an acceptable solution? It passed the tests and seem to work, but wasn't included in the suggested solutions, so I wonder if there are any hidden caveats.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/common-values

**User code**:
```python
def common_values(tuple_1, tuple_2):
    return set(tuple_1 + tuple_2)
```

**Comment by santiagobasulto** [comment]
Hello @Akataya! Yes, and it's a great solution, congrats! We do the explicit for-loops to make it clear how the process works, but your solution is more readable and pythonic.
