### ISSUE TITLE
My solution doesn't pass the tests

### ISSUE THREAD

**Issue by Akataya** [rmotr-curriculum/base-python-curriculum-questions#249]
It does seem to work, but not sure what to do to make it pass the tests. Please help 😭

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/create-empty-box

**User code**:
```python
def create_empty_box(height, width, char):
    box = ""

    if height < 3 or width < 3:
        return "Invalid box dimensions"
        
    for i in range(1):
        row = ""
        row += char * width
            
        for i in range(1):
            row += '\n'
            for i in range(height-2):
                row += char + (" " * (width-2)) + char
                row += '\n'

        row += char * width
        box += row 
    return box
```

**Comment by santiagobasulto** [comment]
Hey @Akataya! Why are you doing `for i in range(1)` so many times? I'd recommend refactoring the solution and building your box in 3 parts: top line, middle part (the empty part) and bottom line. Can you try that?

**Comment by Akataya** [comment]
Thank you! After looking at the code with fresh eyes, realized that range(1) loop was absolutely unnecessary  😅 Refactored the solution and it went through, thanks for help!
