### ISSUE TITLE
format of the function

### ISSUE THREAD

**Issue by itoffensedefense** [rmotr-curriculum/base-python-curriculum-questions#25]
I figured out type('str') == type('str')

however i'm having trouble figuring out how to tailor the if elif and else with the all_strings('string', 'string', 'string')

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/all-strings

**User code**:
```python
def all_strings(a, b, c):
    if all_strings == type('str') , type('str') , type('str')
    
a = 'hello'
#b = None
c = "Python"

```

**Comment by santiagobasulto** [comment]
hey! It's rather simple, but verbose. You'll have to check each variable separately:

```python
if type(a) == str and type(b) == str and type(c) == str:
    pass
```
