### ISSUE TITLE
Does "second item" mean item[1] or item[2]  :)

### ISSUE THREAD

**Issue by bbookman** [rmotr-curriculum/base-python-curriculum-questions#252]
Does "second item" mean item[1] or item[2]  :)

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/list-challenge

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
Hey @bbookman 👋! Second item is `collection[1]`, because we start counting from `0`.
