### ISSUE TITLE
I ran my code on pythontutor and got the intended result but still got assertion error

### ISSUE THREAD

**Issue by poomkhor** [rmotr-curriculum/base-python-curriculum-questions#253]
I ran the test and got the assertion error below. Can you help explain what causes the results to be different? what is the plus and minus sign in the front?

tests.py:60: in test_one_occurrence_third_word
    assert positions(phrase, 'Javscript', 'Ruby', 'Wise') == "-,-,26"
E   AssertionError: assert '-,-,26,' == '-,-,26'
E     - -,-,26,
E     ?       -
E     + -,-,26

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/positions

**User code**:
```python
def positions(a_string, first_word, second_word, third_word):
    
    position = ''

    if first_word in a_string:
        position += str(a_string.index(first_word)) + ','
    else:
        position += '-' + ','
    if second_word in a_string:
        position += str(a_string.index(second_word)) + ','
    else:
        position += '-' + ','
    if third_word in a_string:
        position += str(a_string.index(third_word)) + ','
    else:
        position += '-' + ','
    
    return position   
```

**Comment by jsymons** [comment]
Your code is producing a trailing comma after the position of the third word when there shouldn't be one.

**Comment by poomkhor** [comment]
I wanna smack my head. thank you so much.
