### ISSUE TITLE
Search clarification

### ISSUE THREAD

**Issue by bbookman** [rmotr-curriculum/base-python-curriculum-questions#255]
"The goal is to be able to search this list of animals by the animal's given_name and/or the animal_type, for each of those combinations."

Does this mean the code should handle the following conditions?
given_name = None, animal_type = None
given_name = "some value", animal_type = None
given_name = "some value", animal_type = "some value"
given_name =None, animal_type = "some value"

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-functions/multi-search

**User code**:
```python

```

**Comment by martinzugnoni** [comment]
Exactly. The function must receive three arguments, and the last two ones have to be optional, like this:

```python
def search_animals(list_of_animals, given_name=None, animal_type=None):
    # your code here
