### ISSUE TITLE
For method, do we have to have return in another line?

### ISSUE THREAD

**Issue by poomkhor** [rmotr-curriculum/base-python-curriculum-questions#256]
I tried doing it this way like in operation. it return None instead. Can you help explain the logic behind this? Why can't we return the append method in one line and does this apply to other method as well?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-1/append-to-list

**User code**:
```python
def append_to_list(hungry_list, data):
    return hungry_list.append(data)
```

**Comment by jsymons** [comment]
The problem is that`my_list.append(something)` doesn't return anything, it merely in place modifies `my_list` in place. As a result of this, doing `return my_list.append(something)` is *also* going to return `None` instead of the modified list.

**Comment by poomkhor** [comment]
thank you so much for the help clarification on mentor session!
