### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by CipherSanctum** [rmotr-curriculum/base-python-curriculum-questions#257]
I already know the answer. Just telling you that you made a typo..

This:   ["a", "b", "c", "a", "a," "b"]

Should be this:   ["a", "b", "c", "a", "a", "b"]

If you want get the right answer. Otherwise you get a character called "a,b", instead of proper values being added to 'a' and 'b'

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/count-occurrences

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
Thanks! Fixed: https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-9-collections-part-2/lesson-16-count-occurrences/README.md
