### ISSUE TITLE
Check my solution please

### ISSUE THREAD

**Issue by JaizWaheed** [rmotr-curriculum/base-python-curriculum-questions#258]
My code is pretty different from the 2 solutions.  It works with the asserts but am I missing anything?  Please check.

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/sum-of-dict-values

**User code**:
```python
def sum_of_dict_values(d1, d2, d3):
    d4 = {}
    for key, val in d1.items():
        d4.setdefault(key, 0)
        if type(d1[key]) is not int or type(d2[key]) is not int or type(d3[key]) is not int:
            d4[key] = None
        else:
            d4[key] = d1[key] + d2[key] + d3[key]
        print(d4[key])
    return d4
```

**Comment by jsymons** [comment]
Just a couple of quick notes:
- Since you're never referencing `val` you don't need to use `.items()`, you can just iterate over the keys
- Since in both branches of your `if` you're using `d4[key] =` the earlier `setdefault` is unnecessary.
