### ISSUE TITLE
Why items()?

### ISSUE THREAD

**Issue by JaizWaheed** [rmotr-curriculum/base-python-curriculum-questions#261]
Why does the solution include items()? Couldn't we get the same result with just values()? It doesn't seem like we are using keys anywhere.

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/saving-the-largest-value

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
@JaizWaheed you're completely right, we could have used `values`. At these "early" stages we prefer to use items to make it more natural, but `values` would be more appropriate for sure.

**Comment by santiagobasulto** [comment]
@JaizWaheed can you post your solution, I can include it the original list of solutions.
