### ISSUE TITLE
Why does the method "drive" only need (self) and not the variable being used in the method?

### ISSUE THREAD

**Issue by StevenVallarsa** [rmotr-curriculum/base-python-curriculum-questions#262]
I'm curious as to why the method "drive" only needs self? Is it because the __init__ has already "imported and defined" the variable "electric"?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-oop/make-a-car-that-can-drive

**User code**:
```python

```

**Comment by jsymons** [comment]
Yes, when a new object is instantiated, the __init__ method gets called, which is creating the property (`electric`) so th at we can reference it later.
