### ISSUE TITLE
Why define the sound method in each sub-class

### ISSUE THREAD

**Issue by Akataya** [rmotr-curriculum/base-python-curriculum-questions#263]
Is there another way of implementing the sound method? Do we have to define it in each sub-class? Can we just define the sound method once in the parent class with a placeholder for sound and then create the sound constants in the sub-classes?

**Assignment**: http://learn.rmotr.com/python/base-python-track/oop-inheritance/polymorphism

**Comment by santiagobasulto** [comment]
That could be possible @Akataya. This is just an example to show how different methods would respond to polymorphism, but it's entirely possible to do it as you suggested.
