### ISSUE TITLE
Code assumes a 'naked' employee is never created?

### ISSUE THREAD

**Issue by bbookman** [rmotr-curriculum/base-python-curriculum-questions#265]
Seems this design is not the best..  or is it common practice?  If there was ever a need to create an Employee object, the code would fail.

Traceback (most recent call last):
  File "main.py", line 42, in <module>
    print(emp1)
  File "main.py", line 22, in __str__
    return '{name} makes {income} annually'.format(name = self.name, income = self.calculate_annual_income())
AttributeError: 'Employee' object has no attribute 'calculate_annual_income'

**Assignment**: http://learn.rmotr.com/python/base-python-track/oop-inheritance/payroll

**User code**:
```python
class Employee(object):
    
    def __init__(self, name):
        self.name = name
        
    def __str__(self):
        return '{name} makes {income} annually'.format(name = self.name, income = self.calculate_annual_income())
```

**Comment by santiagobasulto** [comment]
It is actually a "design constraint". If there's an attribute which is EXTREMELY important, and doesn't even make sense to have an object without it, then you enforce it at creation time.

It's pretty common practice.
