### ISSUE TITLE
Should the error this is testing for be a ZeroDivisionError

### ISSUE THREAD

**Issue by rengler33** [rmotr-curriculum/base-python-curriculum-questions#266]
I'm having lots of trouble because I get a ZeroDivisionError with my try/except but the test you've written is for ValueError which appears to not mean the same thing

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/breaking-math

**User code**:
```python
def divide(a, b):
    try:
        result = a / b
    except ZeroDivisionError:
        print ("divide by zero!")
    else:
        return result
```

**Comment by santiagobasulto** [comment]
@rengler33, the solution can be to catch the `ZeroDivisionError` and re-raise a `ValueError`. Example:

```python
try:
    result = a/b
    return result
except ZeroDivisionError:
    raise ValueError()
```
