### ISSUE TITLE
Always append

### ISSUE THREAD

**Issue by bbookman** [rmotr-curriculum/base-python-curriculum-questions#267]
Seems like a good rule of thumb would be that if you want to write, you always append.  Even if you think the file has nothing in it.  Yes, there will be cases where a write or a r+ makes more sense, however append seems a good safe bet

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/writing-files

**Comment by santiagobasulto** [comment]
Yes Bruce, exactly. It's actually pretty hard to write to files without appending, as you've seen it overwrites the previous content. Something that's also done is "replacing" the whole content, if you can load it in memory all at once.
