### ISSUE TITLE
Why open and not 'with open?'

### ISSUE THREAD

**Issue by bbookman** [rmotr-curriculum/base-python-curriculum-questions#268]
Last lesson showed how the context manager was helpful, and this lesson you are doing just 'open'.  Why?

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/csv-old-school

**Comment by santiagobasulto** [comment]
In this particular case I needed to keep the file open so I could show multiple examples and keep it in memory. The recommendation of the context manager still applies, whenever possible, it is preferred without a doubt.
