### ISSUE TITLE
Less fancy, more readable code not using lambda

### ISSUE THREAD

**Issue by bbookman** [rmotr-curriculum/base-python-curriculum-questions#269]
I found this code a little easier to read by not using lamda

**Assignment**: http://learn.rmotr.com/python/base-python-track/functional-programming/temperature-conversion-using-list-comprehensions

**User code**:
```python
def to_fahrenheit(a_list):
    return [(n*9/5) + 32 for n in a_list]  
```

**Comment by santiagobasulto** [comment]
I agree 100% Bruce. It's much cleaner to use your syntax and avoid lambdas as much as possible. The exercise is asking for it just to make students practice it.

My only recommendation would be to space out the operators for better readability:

```python
def to_fahrenheit(a_list):
    return [(n * 9 / 5) + 32 for n in a_list]
```
