### ISSUE TITLE
While Loop in function

### ISSUE THREAD

**Issue by itoffensedefense** [rmotr-curriculum/base-python-curriculum-questions#27]
I understand the use of the while, but including it in a function has me confused about variable placement.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/knock-3-times

**User code**:
```python
def knock_three_times(x):
    while x > 0:
        print ('Knock Knock')
        x -= 1
        
knock_three_times(3)
```

**Comment by jsymons** [comment]
As per discussion in slack, the errors were from tests not expecting function to take a parameter.

**Comment by santiagobasulto** [comment]
👍 awesome, can I close this one? Thanks @jsymons

**Comment by itoffensedefense** [comment]
Yes, thank you!
