### ISSUE TITLE
Suggestion, reword the task

### ISSUE THREAD

**Issue by bbookman** [rmotr-curriculum/base-python-curriculum-questions#271]
This part seems to imply that one must handle the case where the target file IS empty.  For example, only overwrite IF the file is NOT empty.

"overwriting the content of the second
file if it's not empty."

I think the solution code would overwrite regardless of the contents of the target

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/copy-content-from-one-file-to-another

**User code**:
```python

```

**Comment by jsymons** [comment]
I think this is a matter of semantics. "Write a function that receives a path to two text files as parameters and copies
the content of the first file into the second, overwriting the content of the second
file if it's not empty." << Implies that if there are contents in the second file you overwrite them, if the file is empty there's nothing to worry about overwriting and you just write to the file.
