### ISSUE TITLE
I suggest a tiny bit more specificity in the problem description

### ISSUE THREAD

**Issue by bbookman** [rmotr-curriculum/base-python-curriculum-questions#272]
Yes, the tests tell the story.  In this case, it is a little bit trickier than usual to understand from the tests what the output / result must be.  Am I supposed to create a new file, return something, or overwrite the existing file, or what?

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/sort-lines-in-text-file

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
Just made a few changes Bruce, here's the source code of it: https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-21-file-management/lesson-14-sort-lines-in-text-file/README.md
