### ISSUE TITLE
What is happening here to get the string values?

### ISSUE THREAD

**Issue by rengler33** [rmotr-curriculum/base-python-curriculum-questions#274]
cookies.append(cls(
                scarf_color or cls.DEFAULT_SCARF_COLOR,
                buttons_color or cls.DEFAULT_BUTTON_COLOR))

it seems like 'scarf_color or cls.DEFAULT_SCARF_COLOR' would end up passing a boolean instead of a string value.  but I guess it passes the string value instead?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/cookie-factory-with-default-values

**User code**:
```python

```

**Comment by jsymons** [comment]
What it's doing is first checking `scarf_color` and if that's not a *falsey* value it uses it, otherwise it uses `cls.DEFAULT_SCARF_COLOR`

**Comment by rengler33** [comment]
wow, i always thought that doing something like "if scarf_color or cls.DEFAULT_SCARF_COLOR' was simply evaluating to a True or False.  it's pretty cool you can actually get the value this way
