### ISSUE TITLE
I knew the answer, but I'm curious on your test case syntax

### ISSUE THREAD

**Issue by CipherSanctum** [rmotr-curriculum/base-python-curriculum-questions#276]
Are your test cases using some module to run them that allows you to write them the way you are with the strings after the assert?? Because when I do that same thing in a shell I get an AssertionError (assert 1 == 2, 'nope'). It looks to me like whoever wrote it just made some typo's after working all day.

All good, happens to me too. But just asking.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-oop/make-a-car-with-attributes

**User code**:
```python

```

**Comment by jsymons** [comment]
These are written using pytest syntax and thus are for use with the pytest package. https://docs.pytest.org/en/latest/assert.html#asserting-with-the-assert-statement
