### ISSUE TITLE
Could you use the class name instead of cls()?

### ISSUE THREAD

**Issue by gitdownagain** [rmotr-curriculum/base-python-curriculum-questions#278]
Can you use the class name?  And is it just convention to use cls() instead of the class name to make multiple objects of the class?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/cookie-factory

**User code**:
```python

```

**Comment by jsymons** [comment]
Using `cls` instead of the class name protects us from error if we ever decide to rename the class.
