### ISSUE TITLE
Test case fails

### ISSUE THREAD

**Issue by hina-s** [rmotr-curriculum/base-python-curriculum-questions#281]
Hi,
My code runs and displays output correctly. But the test cases fail showing assertion error and " output lines truncated". What does it mean?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/format-board

**User code**:
```python
# Example. Use it as a base to build your own template.
BOARD_TEMPLATE = """
X  -  O  -  X
--------------
X  -  X  -  O
--------------
O  -  X  -  O
"""


def format_tic_tac_toe_board(first_row, second_row, third_row):
    return BOARD_TEMPLATE.format(
        first_row[0], first_row[1], first_row[2],
        second_row[0], second_row[1], second_row[2],
        third_row[0], third_row[1], third_row[2])
        
first_row = 'XOX'
second_row = '0X0'
third_row = '00X'

print(format_tic_tac_toe_board(first_row, second_row, third_row))
```

**Comment by jsymons** [comment]
You don't have any `{}` in your template for `format` to work with, thus it's always going to output the same thing. Remember `format` works like so: `'{}, {}'.format("Hello", "there")` will produce `"Hello there"`. Without the `{}` format won't replace anything.
