### ISSUE TITLE
help on "if not"

### ISSUE THREAD

**Issue by cmoore1** [rmotr-curriculum/base-python-curriculum-questions#283]
The below code worked after I reviewed the solution. However, I am still unclear on why that would work instead of what I was doing before? When I read this it feels like a "truthy" "falsey" statement and reading the supplied solution is very much more efficient however, I like writing out some things for general readability such as the commented section. Could someone provide context?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/sum-if-list-only-contains-integers

**User code**:
```python
def sum_if_list_of_ints(a_list):
    for x in a_list:
        if not isinstance(x, int):
            return 'not an int'
    
    return sum(a_list)
    
'''
def sum_if_list_of_ints(a_list):
    for x in a_list:
        if x != isinstance(x, int):
            return 'not an int'
'''
```

**Comment by martinzugnoni** [comment]
`isinstance(...)` function returns either True or False. In the second implementation, `if x != isinstance(x, int):` will probably enter in all cases, as `x` will always be different to the result of the function.

Makes sense?
