### ISSUE TITLE
Doesn't give correct output

### ISSUE THREAD

**Issue by hina-s** [rmotr-curriculum/base-python-curriculum-questions#287]
It gives me the same original list. What's wrong?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/dictionary-keys-and-values

**User code**:
```python
def invert_dict(a_dict):
    new_dict = {}
    for key, value in a_dict.items():
        new_dict[value] = key
        #new_dict[key] = value
        
    return new_dict
    
updated_dict = {
    1 : 'a',
    2 : 'b'
}    

invert_dict(updated_dict)
print(updated_dict)
```

**Comment by jsymons** [comment]
You're printing your original dictionary, not the one your function is returning. Try `print(invert_dict(updated_dict))` instead.
