### ISSUE TITLE
Is the extra condition needed? from the recommended example.

### ISSUE THREAD

**Issue by atmc612** [rmotr-curriculum/base-python-curriculum-questions#288]
In the recommended soltuion (#1), theres an extra condition result[letter] is not None. What's the purpose of that condition? The code passes all the assert tests without that condition in place.

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/sum-of-dict-values

**User code**:
```python
def sum_of_dict_values(d1, d2, d3):
    result = {}
    
    for letter, count in d1.items():
        result.setdefault(letter,0)
        if type(count) is int:
            result[letter] += count 
        else:
            result[letter] = None
    
    for letter, count in d2.items():
        result.setdefault(letter,0)
        if type(count) is int:
            result[letter] += count 
        else:
            result[letter] = None
    
    for letter, count in d3.items():
        result.setdefault(letter,0)
        if type(count) is int:
            result[letter] += count 
        else:
            result[letter] = None
    
    return result
    
    
    
    
d1 = {
    'a': 10,
    'b': 30,
    'c': 5
}

d2 = {
    'a': 7,
    'b': 22,
    'c': 90
}

d3 = {
    'a': 5,
    'b': 1,
    'c': 'hello'
}


print(sum_of_dict_values(d1, d2, d3))
```

**Comment by santiagobasulto** [comment]
`result[letter] is not None` is used to handle the case of for example `{'c': None}`. Your condition is actually handling it properly because `if type(count) is int` already checks that `count` is NOT a None. The first solution is just a really explicit option, with multiple checks and repeititons; the second solution is the "preferred" one.
