### ISSUE TITLE
Can't pass the last test. 

### ISSUE THREAD

**Issue by Cwade9** [rmotr-curriculum/base-python-curriculum-questions#289]
I can't seem to get the last test to pass. Not sure what is wrong with my code. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/max-character

**User code**:
```python
def max_char(a_string):
    if a_string == '':
        return ''
    else:
        for maximum in a_string:
                 return max(maximum.lower())
    
```

**Comment by jsymons** [comment]
So you don't need to combine max and a for loop. By combining them you're getting the max from the first character in your string. Also return statements inside for loops will break the loop as soon as it comes across the return. When a return is encountered all execution of the function stops and the return immediately happens.
