### ISSUE TITLE
Please explain import of reduce function

### ISSUE THREAD

**Issue by JaizWaheed** [rmotr-curriculum/base-python-curriculum-questions#291]
Why do we need this error before we import reduce function?

try:
    reduce
except NameError:
    from functools import reduce

**Assignment**: http://learn.rmotr.com/python/base-python-track/functional-programming/comma-code

**User code**:
```python

```

**Comment by jsymons** [comment]
This is Python 2/3 compatibility code. In Python 3 `reduce` was moved to the `functools` package. So if we get an error calling reduce we then import it from functools so that our code that calls reduce later works.
