### ISSUE TITLE
3. Find the most expensive item per category

### ISSUE THREAD

**Issue by Vuntsova** [rmotr-curriculum/base-python-curriculum-questions#293]
Didn't understand the solution here. Was that the final solution? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/nested-collections

**Comment by Vuntsova** [comment]
This is my approach. Can you please take a look and let me know why it is not adding "Shields" to most_expensive_item_per_category list:

most_expensive_item_per_category = []
new_set = set()
for product in products:
    new_set.add(product['category'])
    for cat in new_set:
        if product['category'] ==cat:
            if product['category'] == cat and most_expensive_weapon.get("price",0)<= product['price']:
                most_expensive_item_per_category.append(product)
most_expensive_item_per_category

Thanks!

**Comment by santiagobasulto** [comment]
Hey @Vuntsova! Can you improve the formatting a little bit to show spaces and indentation of the code? Here's a guide: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by santiagobasulto** [comment]
@Vuntsova You're well past this stage of the course :) I'll close this issue, if you have any other question about it, please re-open it.
