### ISSUE TITLE
solution code running

### ISSUE THREAD

**Issue by moose241986** [rmotr-curriculum/base-python-curriculum-questions#296]
Code is able to pass the test but still showing error and not able to execute.
Error Message: Traceback (most recent call last):
  File "main.py", line 9, in <module>
    print(format_date(a_date))
  File "main.py", line 7, in format_date
    return a_date.strftime("%A, %B %d %Y")
AttributeError: 'tuple' object has no attribute 'strftime'

**Assignment**: http://learn.rmotr.com/python/base-python-track/modules-and-packages/nice-looking-date

**User code**:
```python
# Import the library here!
from datetime import date
a_date = (1987, 9, 29)


def format_date(a_date):
    return a_date.strftime("%A, %B %d %Y")
    
print(format_date(a_date))


```

**Comment by santiagobasulto** [comment]
Hey @moose241986! 

> Code is able to pass the test

The problem is right there in the error message; with time you guys will get more familiar and you'll learn how to read them. In this case it says:

> AttributeError: 'tuple' object has no attribute 'strftime'

In your `print` statement, you're defining a_date as a tuple. Remove `a_date = (1987, 9, 29)` and the print line and it should work.

**Comment by moose241986** [comment]
If I remove a_date = (1987, 9, 29) and print it gives me a different error "TypeError: format_date() missing 1 required positional argument: 'a_date'" I misunderstood what you meant. 

# Import the library here!
from datetime import date
#a_date = (1964, 7, 31)
def format_date(a_date):
    return a_date.strftime("%A, %B %d %Y")
    
print(format_date((1964, 7, 31)))
