### ISSUE TITLE
Reading materials

### ISSUE THREAD

**Issue by jonny-voelx** [rmotr-curriculum/base-python-curriculum-questions#300]
Around the 2:20 mark there was a mention made of "reading materials" being attached somewhere. Where can I go to find the reading materials, and are there such materials associated with each of the videos? Thanks!

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/intro-to-operators

**Comment by santiagobasulto** [comment]
Thanks @jonny-voelx! Somehow we forgot to add that link, here it is: https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-3-operators/lesson-1-intro-to-operators/Intro%20to%20Operators.ipynb

We'll also add it below the video for future reference.
