### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by hina-s** [rmotr-curriculum/base-python-curriculum-questions#302]
I'm not able to use raise ValueError with except clause. This below code gives me error.

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/breaking-math

**User code**:
```python
def divide(a, b):
    
    try:
      return a / b
    
    except ValueError:
          print('Dividend is 0')
      
 
divide(3,0)
```

**Comment by jsymons** [comment]
This is because dividing by zero doesn't raise a `ValueError`, it raises a `ZeroDivisionError`. We want your function to instead raise a `ValueError`.

**Comment by hina-s** [comment]
I'm still lost. Is this the correct way of raising an error or does it have to be with an if statement only?

def divide(a, b):
    
     try:
       return a / b
    
     except ValueError:
       pass

     raise ValueError("Invalid number")

**Comment by jsymons** [comment]
The way you're raising the error has nothing to do with the issue you're having. The moment you try to divide by zero python will throw a `ZeroDivisionError`. You aren't catching that error so it raises straight up and causes the test to fail as it's an unexpected error.
