### ISSUE TITLE
When to use if - raise vs. try - except...

### ISSUE THREAD

**Issue by atmc612** [rmotr-curriculum/base-python-curriculum-questions#303]
From this lesson's notebook, I can see that calling the add_coin function returns the error we expect to see based on the input value. 

Is it really necessary to add that additional "try-except" in addition to what the function already does? It seems like the result format from try-except is just a little less scary... 

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/custom-exceptions

**Comment by santiagobasulto** [comment]
The try-except  block is just to show how to capture exceptions that are raised. If we don't include try-except, the program errors and finishes completely. It'll will stop with an error.
