### ISSUE TITLE
Failing valid key use case

### ISSUE THREAD

**Issue by F0R6E** [rmotr-curriculum/base-python-curriculum-questions#304]
Passing all tests except the valid key use case. Not too sure why this isn't passing, it seems to be working correctly on PythonTutor...

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/reimplement-pop

**User code**:
```python
def pop(dictionary, key, default_value=None):
    try:
        if key in dictionary:
            return key
            del key
        else:
            if default_value:
                return default_value
            else:
                raise KeyError('Key error')
    except KeyError:
        raise KeyError('Key error')
```

**Comment by jsymons** [comment]
Couple of things:

1. You're returning the key, not the value associated with that key
2. You're trying to just del the key, you need to in fact delete it when related to the dictionary: `del dictionary[key]`
3. You're returning before you try to do the deletion, when a return statement occurs all further execution is stopped and the return immediately happens, thus anything after the return will never execute.
