### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#306]
Unable to understand as to where I'm going wrong with my code

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/double-down

**User code**:
```python
def double_down(num, times_doubled):
    a=0
    
    while(a<=times_doubled):
        num=num*2
        a+= 1
        
    return num       
        
```

**Comment by jsymons** [comment]
You should be using `a < times_doubled`, not `a <= times_doubled` if you're starting `a` at `0`. You would use `<=` if you started `a` at `1`.
