### ISSUE TITLE
What is wrong with this?

### ISSUE THREAD

**Issue by findalexli** [rmotr-curriculum/base-python-curriculum-questions#308]
I can't see any error

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/return-the-type-of-value

**User code**:
```python
def which_type(val):
    if isinstance(val,int):
        return 'integer'
    elif isinstance(val,str):
        return 'string'
    elif isinstance(val,bool):
        return 'boolean'
    elif isinstance(val,float):
        return 'float'
```

**Comment by santiagobasulto** [comment]
This is a common mistake with this problem, here's some more details for it: https://blog.rmotr.com/those-tricky-python-booleans-2100d5df92c

**Comment by findalexli** [comment]
Thank you so much!
