### ISSUE TITLE
FYI: directions say to use a for loop; example solution does not use a for loop. 

### ISSUE THREAD

**Issue by JessLars** [rmotr-curriculum/base-python-curriculum-questions#31]
FYI: directions say to use a for loop; example solution does not use a for loop. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/is-char-in-string

**User code**:
```python
def char_in_string(a_string, char_to_look_for):
    pass
```

**Comment by santiagobasulto** [comment]
Thanks @JessLars! I've already added it: https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-6-strings/lesson-10-is-char-in-string/solutions/solution_for_loop.py
