### ISSUE TITLE
Can we use init method?

### ISSUE THREAD

**Issue by hina-s** [rmotr-curriculum/base-python-curriculum-questions#311]
Can we implement this using init method? The solution doesn't use __init__().

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-oop/calculator-method

**User code**:
```python

```

**Comment by jsymons** [comment]
Init isn't really applicable here, we aren't initializing the calculator class with any parameters. You could in theory implement the add and subtract methods as lambdas and declare them in the init, but it would be an overcomplicated solution.
