### ISSUE TITLE
Pythonic approach to is_prime() function

### ISSUE THREAD

**Issue by vchau76** [rmotr-curriculum/base-python-curriculum-questions#312]
This is my code for determining if a number is a prime or not.  It works but after writing this, I checked out other ways of determining if a number is a prime or not and it seems my code is a little dense.  Can you tell me if/why my code may not be the best method?  I want to make sure my coding foundation is solid and would welcome any input on this code.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def is_prime(prime):
    count = 1
    while count < prime:
        count += 1
        if count != prime and count != 0:
            calc = (prime / count)
            if calc == 2 or calc == 3 or calc == 5 or calc == 7:
                return False #Non-Prime Number
                break
        else:
            return True #Prime Number
```

**Comment by santiagobasulto** [comment]
Sure! So, `count = 0` is something that will NEVER happen, cause you're initializing it in `1`, and always incrementing `1`.

This is a problem `if calc == 2 or calc == 3 or calc == 5 or calc == 7:`: From this line, what happens if the number is divisible by 11, but not by the rest? For example, the number 121.

The usual procedure is to check all the numbers to find divisors:

```python
def is_prime(n):
    if n in (2, 3):
        return True
    if n % 2 == 0:
        return False

    i = 3
    while i < n-1:
        if n % i == 0:
            return False
        i += 2
    return True
```

**Comment by jsymons** [comment]
If you're looking for a more efficient method than just brute forcing it you can take a look at [The Sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes), however for the purposes of this project brute forcing is fine.
