### ISSUE TITLE
example used :why is it not "while valid:"?

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#313]
valid=False
In while loop, why have you given 'while not valid' before the 'If' condition that checks if password>8 and has '$' symbol. 
'While not valid' means ;'while not false' which is 'while true'

Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/while-vs-for-loops

**Comment by jsymons** [comment]
Because ultimately we want to loop (and therefore prompt for a new password) as long as the password isn't valid. Once they've entered a valid password the if/else marks the password as valid and breaks the loop.
