### ISSUE TITLE
couple of questions on this exercise 

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#315]
2nd test fails for code 
def char_in_string(a_string, char_to_look_for):
    for i in a_string:
        if char_to_look_for==i:
            return True
        else:
            return False

Why is it so?

Also for loop for i in a_string means for each index in the string, right?
so if I give if char_to_look_for==a_string[i], I get an error, why is it so?

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/is-char-in-string

**User code**:
```python
def char_in_string(a_string, char_to_look_for):
    for i in a_string:
        if char_to_look_for==i:
            return True
        else:
            return False
```

**Comment by jsymons** [comment]
So when a return statement is encountered the return **immediately** occurs, stopping all further execution of the function. This is a common stumbling block when it comes to loops as the return statement breaks the loop (this is sometimes what you actually want to happen). So what's happening is your loop will ultimately only ever check the first character of the string and then return whether that character matches or not. What you want to do is have your return *after* your loop, which means you'll need to have a boolean flag to keep track of whether or not he character was found.

As for your second question, `i` will **not** be the index in the string, it will be the actual character.
