### ISSUE TITLE
why is my code not working?

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#317]
Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/characters-in-even-positions

**User code**:
```python
def chars_in_even_positions(a_string):
    new=''
    counter=1 
    for i in a_string:
        if counter % 2 == 0:
            new+=i
            counter+=1
        
    return new
            
        
```

**Comment by jsymons** [comment]
You're only increasing the counter *inside* your if statement. However because of this the if statement never evaluates to True because counter is always equal to 1. You need to move `counter += 1` to outside the if statement.

**Comment by santiagobasulto** [comment]
And to add to @jsymons , outside the **and BEFORE** the if statement.
