### ISSUE TITLE
Can you please correct my code

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#318]
Hi Jason, You corrected my previous code- I tried rewriting it and have run into an issue towards the end. Where am I going wrong?
def insert_dashes(a_string):
    i=1 
    
    new=''
    while i<=len(a_string):
        if i%3==0 and i !=0:
            new+='-'
            new+=a_string[i]
                 
        else:
            new+=a_string[i]
        i+=1
    return new

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/insert-dashes-every-3-characters

**User code**:
```python
def insert_dashes(a_string):
    i=1 
    
    new=''
    while i<=len(a_string):
        if i%3==0 and i !=0:
            new+='-'
            new+=a_string[i]
                 
        else:
            new+=a_string[i]
        i+=1
    return new

```

**Comment by jsymons** [comment]
Take a look at the tests, they're looking for the dash *after* the third character. So you should be adding `a_string[i]` *before* you add the dash.
