### ISSUE TITLE
My code works but I like the recommended solution better! 

### ISSUE THREAD

**Issue by atmc612** [rmotr-curriculum/base-python-curriculum-questions#319]
As mentioned, my code obviously passes the test but i'd like to understand how the recommended answer works... 

If you don't pass a parameter, how does the recommended solution know not to set the instance attribute to 'None'? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/class-and-instance-attributes

**User code**:
```python
class Cookie(object):
    DEFAULT_BUTTON_COLOR = 'Blue'
    DEFAULT_SCARF_COLOR = 'Green'
    
    def __init__(self, scarf_color=None, buttons_color=None):
        if not scarf_color:
            self.scarf_color = self.DEFAULT_SCARF_COLOR
        self.scarf_color = scarf_color
        
        if not buttons_color:
            self.buttons_color = self.DEFAULT_SCARF_COLOR
        self.buttons_color = buttons_color
```

**Comment by jsymons** [comment]
For reference I'm going to paste the solution you're referring to here:
```python
class Cookie(object):
    DEFAULT_SCARF_COLOR = 'Green'
    DEFAULT_BUTTON_COLOR = 'Blue'

    def __init__(self, scarf_color=None, buttons_color=None):
        self.scarf_color = scarf_color or self.DEFAULT_SCARF_COLOR
        self.buttons_color = buttons_color or self.DEFAULT_BUTTON_COLOR
```
So when we do `self.scarf_color = scarf_color or self.DEFAULT_SCARF_COLOR` it checks to see if `scarf_color` is "truthy", if it is it assigns that value to `self.scarf_color` if it is instead "falsey" it will instead assign `self.DEFAULT_SCARF_COLOR`'s value to `self.scarf_color`. Hope that clears things up.

**Comment by atmc612** [comment]
Thanks, I think that does. Can this syntax be used when we set variables that are not class attributes?

**Comment by jsymons** [comment]
Yes it can.
