### ISSUE TITLE
Can we use the max() function?

### ISSUE THREAD

**Issue by cucuy1** [rmotr-curriculum/base-python-curriculum-questions#32]
Just wondering, can we just use the max() function? Shall we solve this with if and elifs?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/greatest-parameter

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
@SavvasTheodorou you're definitively right, `max` would be ideal for this situation. We're just "forcing" students to think about operators. Here's the proposed solution: https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-5-intro-to-control-flow/lesson-22-greatest-parameter/solutions/solution_.py

But yeah, just `max([a, b, c..])` would be much better
