### ISSUE TITLE
Why does this work?

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/base-python-curriculum-questions#320]
Why does "while True" work here? What is that actually saying? Doesn't a WHILE statement need to define a variable? How does it know when to end?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def next_palindromic_prime(n):
    
    n += 1
    
    while True:
        if is_palindromic(n) and is_prime(n):
            return n 
        n += 1
```

**Comment by jsymons** [comment]
So if we didn't have the `return` statement (or in the case that the if statement would never evaluate to True) this would in fact be an infinite loop. However, we need to remember that when a `return` is encountered the code **immediately** stops execution and returns. This means that when the return happens it breaks out of the loop.
