### ISSUE TITLE
I don't understand 

### ISSUE THREAD

**Issue by EchoTCharlie** [rmotr-curriculum/base-python-curriculum-questions#322]
Are you saying a "number" to the 2nd power?? or multiplying by 2 getting a sum and multiplying by 2 again? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/powers-of-2

**User code**:
```python

```

**Comment by jsymons** [comment]
We're saying 2 to the power of a number. As in 2<sup>n</sup> where n is the number being passed in as a parameter to the function.
