### ISSUE TITLE
Want to understand pros/cons between my solution and given solution.

### ISSUE THREAD

**Issue by jonny-voelx** [rmotr-curriculum/base-python-curriculum-questions#326]
Sometimes my response is practically identical to the given solution(s), but obviously not always, and I'm curious as to whether or not there might be a potential pitfall with what I've come up with that I just can't see. What could go wrong by concatenating the "oo" to each character in the original string (see line 5) and then adding them to the new string, as opposed to adding the character, the adding the "oo" after the character in the new string (see lines 12 and 13)? Thanks!

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/convert-pirate-to-dog

**User code**:
```python
# my solution
def convert_pirate_to_dog(pirate_saying):
    result = ""
    for char in pirate_saying:
        result += char + "oo"
    return result

# given solution
def convert_pirate_to_dog(pirate_saying):
    result_in_dog_speak = ""
    for letter in pirate_saying:
        result_in_dog_speak += letter
        result_in_dog_speak += "oo"
    return result_in_dog_speak
```

**Comment by jsymons** [comment]
These will produce the same output, the given solution is just more verbose. Technically your way is going to be slightly faster as result gets larger. (Only concat'ing to the large string once vs twice)
