### ISSUE TITLE
Placement of variables

### ISSUE THREAD

**Issue by jonny-voelx** [rmotr-curriculum/base-python-curriculum-questions#327]
I only have a basic understanding of where to place a variable in a simple block of code (and an even weaker understanding of how it may affect other code elsewhere in a program...),  but of the two functions below, what should I be aware of specifically regarding where I placed the variable "piratization" (lines 3 and 11)? Thanks!

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/convert-pirate-to-dog

**User code**:
```python
def convert_pirate_to_dog(pirate_saying):
    result = ""
    piratization = "oo"
    for char in pirate_saying:
        result += char + piratization
    return result

def convert_pirate_to_dog(pirate_saying):
    result = ""
    for char in pirate_saying:
        piratization = "oo"
        result += char + piratization
    return result
```

**Comment by jsymons** [comment]
Placing it inside of the loop means it is going to re-set the value of `piratization` every iteration of the loop, doing it outside means it only has to set it once.
