### ISSUE TITLE
Why does this work?

### ISSUE THREAD

**Issue by atmc612** [rmotr-curriculum/base-python-curriculum-questions#328]
It seems like __iadd__ is utilizing the __add__ magic method from the previous lines of code? But how does it know to use __add__ given that method is in a different scope? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/currency-my-way-out

**User code**:
```python
    def __add__(self, other):
        self_usd = self.convert(self.BASE_UNIT)
        other_usd = other.convert(self.BASE_UNIT)
        return Currency(self_usd.value + other_usd.value, self.BASE_UNIT)

    def __iadd__(self, other):
        total_usd = self + other
        total_self_unit = total_usd.convert(self.unit)
        return Currency(total_self_unit.value, self.unit)
```

**Comment by jsymons** [comment]
When you call `something + something_else` python is internally automatically going to go and do `something.__add__(something_else)`, that's just how the operators work. If `__add__` hasn't been defined for `something` then it will throw an error.
