### ISSUE TITLE
Sorry Jason- still unable to get it. Didnt understand.

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#329]
def positions(a_string, first_word):
    
    name=a_string.split()
   
    for first_word in name: 
        if first_word in name:
        
           return name.index(first_word) 
        
    
    else:
        index = str('-')
        return index

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/positions

**User code**:
```python
def positions(a_string, first_word, second_word, third_word):
    pass
```

**Comment by jsymons** [comment]
I responded to your original issue in https://github.com/rmotr-curriculum/base-python-curriculum-questions/issues/325
