### ISSUE TITLE
How do I mark as complete?

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#33]
I am watching the videos but they don't seem to indicate that I've completed the task

**Assignment**: http://learn.rmotr.com/python/base-python-track/getting-started/python-overview

**Comment by jsymons** [comment]
After watching the video you need to click the arrow icon (also looks like a paper airplane)

**Comment by santiagobasulto** [comment]
@branhoff can you close this one if it's resolved? Thanks!

**Comment by SoniaBuckley** [comment]
I am also having trouble with this.  I have clicked the paper airplane for all prep work 1 videos and submitted code for each one but it is not marked as completed.
![code done](https://user-images.githubusercontent.com/14284157/50767918-50cfcc00-12ca-11e9-8a93-29e464d8c02d.PNG)
![0 percent](https://user-images.githubusercontent.com/14284157/50767920-53322600-12ca-11e9-87dd-30a48dc2bba9.PNG)
![done](https://user-images.githubusercontent.com/14284157/50767923-55948000-12ca-11e9-97d6-6f26e1e2f077.PNG)

**Comment by martinzugnoni** [comment]
@SoniaBuckley can you please try refreshing the page to see if the progress gets updated? I see you have 64% done in the Tutorial unit.

**Comment by SoniaBuckley** [comment]
It's updated. Thanks!
