### ISSUE TITLE
Confused...

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#331]
Not sure how to continue with this. Wrote basic code - Understand even positions are where i%2==0 and odd positions are i %2 !=0 , then we count even and odd positions. Unsure how to write it in code. Anyway is my understanding correct and I'm on the right track?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/count-in-even-odd-positions

**User code**:
```python
a_string='abcXXiX'
a_char='X'    
a_string.split()
count=0
for i,name in enumerate(a_string):
    if name==a_char:
        if i%2==0:
           count+=1           
print(count)
            
            
```

**Comment by jsymons** [comment]
That's fine for counting even, but you need to be able to handle counting odd as well, which would be the opposite of your current if statement. Then you have to also remember that you have to return the appropriate value depending if `'even'` or `'odd'` was passed in for `position_type`
