### ISSUE TITLE
 __repr__ = __str__ doesn't work

### ISSUE THREAD

**Issue by hina-s** [rmotr-curriculum/base-python-curriculum-questions#332]
Why doesn't  __repr__ = __str__ work? I need to specifically type in the method for  repr to run the test.

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/horse-representation

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
Because `__repr__` is used in consoles and IDLEs, and `__str__` is used when "printing". So they're actually different methods. You have to implement both, and **they are different**.
