### ISSUE TITLE
Why does {} not work here?

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/base-python-curriculum-questions#334]
Line 6

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/get-positions-of-char

**User code**:
```python
def get_positions_of_char(another_string, char_being_searched_for):
    result = ""
    
    for pos, char in another_string:
        if char == char_being_searched_for:
            result += "{},".format(str(pos))
            
    return result
```

**Comment by jsymons** [comment]
The `{}` works fine, you're getting an error from your for loop `for pos, char in another_string:` it's saying there's not enough values to unpack. To get both the position and char from a string you need to use `enumerate()` like this:
```python
for pos, char in enumerate(another_string):
```
