### ISSUE TITLE
Use of total variable?

### ISSUE THREAD

**Issue by hina-s** [rmotr-curriculum/base-python-curriculum-questions#337]
Where is the total variable being used at all in the program? Only the hourly_wage is being used to calculate annual income. Can you pls demonstrate usage of total with the employee_list having some values. Thanks.

**Assignment**: http://learn.rmotr.com/python/base-python-track/oop-inheritance/payroll

**User code**:
```python
class Payroll(object):
    pass


class Employee(object):
    pass
```

**Comment by hina-s** [comment]
Can we call the get_annual_payroll_cost method in the main?

**Comment by jsymons** [comment]
I'm going to make the assumption that you're talking about the variables from our solution. Both of those variables *are* being used in the tests. When we call `get_annual_payroll_cost` (which we do in the Test Payroll test), `total` is what gets returned. `employee_list` is updated whenever `add_employee` is called, which we also do in the Test Payroll test.

**Comment by hina-s** [comment]
Where is the value of total being returned to? I can't figure it out.

**Comment by jsymons** [comment]
Look at the tests along the left side of the window on the Learn platform, here is the Test Payroll test I mentioned:
```python
def test_payroll():
    emp1 = SalariedEmployee("Bill", 60000)
    emp2 = HourlyEmployee("Ted", 25)
    
    payroll = Payroll("Excellent Adventures")
    assert payroll.company == "Excellent Adventures"

    payroll.add_employee(emp1)
    payroll.add_employee(emp2)
    assert payroll.get_annual_payroll_cost() == 112000

```
Pay special attention to the last line:
```python
assert payroll.get_annual_payroll_cost() == 112000
```
This would be the same as:
```python
this_is_where_total_returns_to = payroll.get_annual_payroll_cost()
assert this_is_where_total_returns_to == 112000
```

**Comment by hina-s** [comment]
Got it jason! Thanks!
