### ISSUE TITLE
Getting return value as "None" when list has a string value say 'a'

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#339]
doesn't work when list has a non int value

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/sum-if-list-only-contains-integers

**User code**:
```python
def sum_if_list_of_ints(a_list):
    sum=0
    for i in a_list:
        if not i==int(i):
           return "not an int"
        
        else:
           sum+=i 
            
            
    return sum
    
            
```

**Comment by jsymons** [comment]
You shouldn't be using `not i == int(i)` to test if something is an integer, it would pass if we passed in a float (`1.5`) which it shouldn't, and it will crash if something cannot be converted to an int which is what is happening when the test runs. You should instead be comparing using `type()` [relevant python documentation](https://docs.python.org/3/library/functions.html#type)

Normally we would encourage the usage of `istinstance()` over `type()` however this would give you false positives when checking if a boolean is an integer.
