### ISSUE TITLE
How can I invert the boolean of an inequality on a single line?

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#34]
How can I invert the boolean of an inequality on a single line?

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/inverting-booleans

**User code**:
```python
burger = False

# Flip this burger using not
burger_flipped = not burger


number = 5

# Create an inequality checking if number is greater than 3, then invert the result (all on one line)!
result = number > 3 = not number

assert burger_flipped is True
"assert result is False"

print(result)


```

**Comment by martinzugnoni** [comment]
Just by prefixing the `not` again. Like this.
```python
result = not number > 3
```

**Comment by jsymons** [comment]
If we have an expression that evaluates to a boolean we can invert it by applying not to that expression: 
`will_be_true = 1 == 1`
becomes
`will_not_be_true = not (1 == 1)`

That clear things up a little?
