### ISSUE TITLE
Double parentheses?

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/base-python-curriculum-questions#340]
Why does the append method require double parentheses here?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/dict-to-tuple

**User code**:
```python
def dict_to_tuple(a_dict):
    result = []
    
    for k, v in a_dict.items():
        result.append((k,v))
    return result
```

**Comment by jsymons** [comment]
The double parentheses are there because we are ultimately appending a tuple. We could just as easily do:
```python
t = (k, v)
result.append(t)
```
