### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#341]
Can you pls let me know where I'm going wrong?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/string-positions

**User code**:
```python
def get_string_positions(the_string):
    for position,character in enumerate(the_string):
        return str(position) + '- '+ character+'\n'
```

**Comment by jsymons** [comment]
When Python encounters a `return` it immediately stops execution and returns, this means that it will break out of loops on finding one, sometimes this is what you want, however that is not the case here.
