### ISSUE TITLE
Files to large

### ISSUE THREAD

**Issue by SoniaBuckley** [rmotr-curriculum/base-python-curriculum-questions#345]
You mentioned that if a file is too large it will try to copy to the OS which is not good.  What should we go if a csv file is too large?  Are there any best practices? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/intro-to-file-management

**Comment by santiagobasulto** [comment]
Hey Sonia! This is a very interesting question. Do you have any particular example, or you're asking generally?
