### ISSUE TITLE
Confused with dictionaries and this exercise

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#346]
Can you please help?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/banana-dictionary

**User code**:
```python
def banana_dict(num):
    new={}
    counter=0
    
    while num>0:
        new['banana' * num]
        counter+=1
    return new
    
        
```

**Comment by jsymons** [comment]
You're defining a key without setting a corresponding value. Should look like this:
```python
my_dict["my_key"] = my_value
```
