### ISSUE TITLE
Can we use or to check if a number is an int or float?

### ISSUE THREAD

**Issue by selmabensaid** [rmotr-curriculum/base-python-curriculum-questions#347]
i used if type (a_number)== (int or float) but it didn't pass the float test.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/is-numeric

**User code**:
```python
def is_numeric(a_number):
   if type(a_number)== int : 
        return True
   if type(a_number)== float : 
        return True
   return False

```

**Comment by jsymons** [comment]
You could do one if two things to accomplish what you want:
This accomplishes it using or:
```python
if type(a_number) == int or type(a_number) == float:
```
However I think this is more along the lines of what you're after:
```python
if type(a_number) in (int, float):
```
