### ISSUE TITLE
assertions 1 and 2 failing

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#349]
Can you please help?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/count-occurrences

**User code**:
```python
def count_occurrences(a_list):
    new={}
    count=0
    
    for i in a_list:
        if i in new.keys():
            count+=1 
            new[i]=count
        else:
            new[i]=1 
    return new
        


```

**Comment by jsymons** [comment]
You should drop the count variable. Instead do `new[i] += 1`.
The reason why count is causing you issues is that ray we have the following list: `["a", "b", "c", "a", "a", "b"]` here's how things play out in the for loop:
```
first iteration: i = 'a', count = 0, new ={'a': 1}
second: i = 'b', count = 0, new = {'a': 1, 'b': 1}
third: i = 'c', count = 0, new = {'a': 1, 'b': 1, 'c': 1}
fourth: i = 'a', count = 1, new = {'a': 1, 'b': 1, 'c': 1}
fifth: i = 'a', count = 2, new = {'a': 2, 'b': 1, 'c': 1}
sixth: i = 'b', count = 3, new = {'a': 2, 'b': 3, 'c': 1}
```
`count` doesn't end up representing how many times a particular letter has been counted, it ends up representing how many times *any* letter has shown up past the first time.
