### ISSUE TITLE
code doesnt work

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#350]
set has no items

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/search-keys-for-value

**User code**:
```python
def search_keys_for_value(a_dictionary, search_term):
    s=set()
    for i in a_dictionary.keys():
        if search_term==a_dictionary.values():
            s+=i
    return s
```

**Comment by jsymons** [comment]
A couple of issues:
- We add to a set using `my_set.add(elem)`, not `my_set += elem`
- `search_term == a_dictionary.values()` checks if the search term is equal to the values in the dictionary, not a specific value, but **all** the values, so you're going to want to change that.
