### ISSUE TITLE
Why is len() needed in the for loop?

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/base-python-curriculum-questions#351]
Wouldn't "for i in collection_a:" be sufficient since it would iterate of the number of items in that collection?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/zip-two-collections

**User code**:
```python
def rmotr_zip(collection_a, collection_b):
    if len(collection_a) != len(collection_b):
        return None
    result = []

    for i in range(len(collection_a)):
       result.append((collection_a[i], collection_b[i]))
       
    return result
```

**Comment by jsymons** [comment]
`for i in collection_a` would iterate over the elements of `collection_a`, not the number of items.
example:
```python
my_list = ['a', 'b', 'c']
for i in my_list:
    print(i)
```
Would give us this output:
```
a
b
c
```
