### ISSUE TITLE
If 'customers'?

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/base-python-curriculum-questions#352]
Does "if customers:" just result to true if there are values associated with the key?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/number-of-customers-per-state

**User code**:
```python
def number_of_customers_per_state(customers_dict):
    results = {}
    for state, customers in customers_dict.items():
        if customers:
            results[state] = len(customers)
        else:
            results[state] = 0
    return results
```

**Comment by jsymons** [comment]
If there are 'truthy' values. Values like `None`, `0`, `""`, and `False` would all result as a `False`.
