### ISSUE TITLE
Error in Solution 2

### ISSUE THREAD

**Issue by vchau76** [rmotr-curriculum/base-python-curriculum-questions#353]
I believe there is an error in solution 2.  On line 5 (if type(value) is int:).  This returns the following error if there is already a 'None' value in the key:value pair.

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

I believe it should also check to see if the key already contains this value as follows:

if type(value) is int and agg_dict[key] != None:

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/sum-of-dict-values

**User code**:
```python

```

**Comment by jsymons** [comment]
You're correct, I've put in a PR to correct this. Thanks!
