### ISSUE TITLE
using max function and doesnt work

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#356]
I'm using dict.values() and trying to get the max value and then trying to finc the key associated with the max value. doesn't work

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/saving-the-largest-value

**User code**:
```python
def get_largest_numbers(d1):
    result_1={}
  
    
    for val1 in d1.values():
        if isinstance(val1,int):
          result_1.get(key(max(val1)))
          result_1[key]=val1
    return result_1  
```

**Comment by jsymons** [comment]
You've completely changed the function signature and thus how it's supposed to work. `get_largest_numbers` is supposed to take **three** dictionaries that have the same keys and calculate the largest number **for each key**.
