### ISSUE TITLE
Need for a while loop?

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#359]
Is there a reason we couldn't just define the function like below - initial_number**power?

What is the use case for the while loop?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/the-power-of-while-loops

**User code**:
```python
def feel_the_power(initial_number, power):
    return initial_number**power
```

**Comment by jsymons** [comment]
Yes you can do it that way and normally that's the way you should do it. However we're using this as an example to help people understand how while loops work.
