### ISSUE TITLE
How do I convert an int to a string?

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#36]
In my code, I need to take an integer and make it print like a string, but I don't remember learning how to do that.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/help-a-string-get-lucky

**User code**:
```python
def get_lucky(poor_string, lucky_number):
    output = poor_string + lucky_number
    while len(poor_string) + len(lucky_number) < output:
        poor_string += lucky_number
    pass

print(get_lucky('kind of', 3))
```

**Comment by jsymons** [comment]
`integer_as_string = str(my_int)`
You can also do something like:
`"My integer will appear here: {}".format(my_int)`
And `format` will handle converting it to a string.
