### ISSUE TITLE
Finding prime numbers - how to keep the loop going

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#360]
In the below code, I can find the prime numbers correctly if I omit the "else" statement but then can't return the boolean in the case of a prime number. How can I incorporate the "else" statement while letting the loop run through the range?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
#works
def is_prime(n):
    if n>0:
        for i in range(2,n):
            if (n%i)==0:
                return False

#doesn't work
def is_prime_2(n):
    if n>0:
        for i in range(2,n):
            if (n%i)==0:
                return False
            else:
                return True
```

**Comment by jsymons** [comment]
You need to let the loop run through the range otherwise you won't know if the number is prime.

**Comment by gmrkss** [comment]
just omit the else?

how would I return True if I don't have an else?

**Comment by gmrkss** [comment]
I return None if I don't have a true somewhere

**Comment by jsymons** [comment]
Return True **after** your for loop completes.
