### ISSUE TITLE
Way to make code more concise

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#361]
Able to find prime numbers with the below code and return the appropriate boolean, however, was wondering, is there an easier way to make this code more concise?

Do I need two if statements within the for loop?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def is_prime(n):
    if n>0:
        for i in range(2,n):
            if (n%i)==0:
                x=False
                if x==False:
                    return False
                else:
                    return True
```

**Comment by jsymons** [comment]
```python
def is_prime(n):
    if n > 0:
        for i in range(2, n):
            if n % i == 0:
                return False
        return True
```
However note that both this and your solution will return incorrect values for n = 1, as n = 1 should return False.
