### ISSUE TITLE
Unsure if logic is correct

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#363]
Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/nested-pyramids

**User code**:
```python
def nested_pyramid(height, char):
    row=1 
    column=1 
    pyramid=''
    for row in range(1,height):
        for column in range(row+1 ):
            pyramid+=char
            
    return pyramid
    
```

**Comment by santiagobasulto** [comment]
hello @vidsjai! You're not adding the new line characters to each newline in the pyramid, check this out:

![image](https://user-images.githubusercontent.com/872296/53736616-00f42800-3e69-11e9-9b34-99d40ed62642.png)

Adding a newline char `'\n'`, after you create each row would fix it.
