### ISSUE TITLE
Palindromic but not prime - failing test case for 160

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#364]
Hi, having trouble with the test case 160 for my next_palindromic_prime function. I can see when debugging that for n=161, x evaluates to True (is palindromic) and y evaluates to False (not prime) and then returns n outside the while loop.

I want to keep running the while loop unless both conditions are satisfied, any thoughts?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def reverse_str(s):
    # Please don't change me
    return s[::-1]

# Try it on your own by uncommenting the following lines and hitting "Run Code"
# print(reverse_str('abc'))
# print(reverse_str('123'))
# print(reverse_str('121'))

def is_palindromic(n):
    str(n)
    if str(n)==reverse_str(str(n)):
        return True
    else:
        return False

def is_prime(n):
    if n > 0:
        if n==2 or n==3:
            return True
        elif n==1:
            return False
        else:
            for i in range(2,n):
                if n%i==0:
                    return False
            return True
                
def next_palindromic_prime(n):
    n+=1
    x = is_palindromic(n)
    y = is_prime(n)
    while (x!=True and y!=True) :
        n+=1
    return n
    
```

**Comment by jsymons** [comment]
Use `or` instead of `and`. That way the while only breaks if both of those statements evaluate false.
