### ISSUE TITLE
Assertion failing for Descending solution

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#367]
Also confused with the assertion in description. A Pyramid with 3 levels DESC , function attribute says 5 instead of 3.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/advanced-nested-pyramids

**User code**:
```python
def advanced_nested_pyramid(height, char, order):
    row=1 
    column=1 
    pyramid=''
    if order=='ASC':
        for row in range(height):
            for column in range(row+1):
                pyramid+=char
            pyramid+='\n'
            
    if order=='DESC':
        for row in range(height+1,0,-1):
            for column in range(row-1):
                pyramid+=char
            pyramid+='\n'
    
    return pyramid
           
            
```

**Comment by jsymons** [comment]
Your `DESC` case is looping one too many times. Instead of `range(height+1, 0, -1)` you need to do `range(height+1, 1, -1)`. The extra loop through is adding an extra blank line to your output which is what is causing the test to fail.
