### ISSUE TITLE
Palindromic Primes

### ISSUE THREAD

**Issue by mizjane07** [rmotr-curriculum/base-python-curriculum-questions#368]
I cannot figure out how to write checking for a  prime number.  I know that a prime number is only divisible by itself and 1 and also includes the numbers 2 and 3.  However, I don't know how to think about that in pythonic context.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def reverse_str(s):
    # Please don't change me
    return s[::-1]

# Try it on your own by uncommenting the following lines and hitting "Run Code"
# print(reverse_str('abc'))
# print(reverse_str('123'))
# print(reverse_str('121'))

def is_palindromic(n):
    return str(n) = reverse_str(str(n))

def is_prime(n):
    pass

def next_palindromic_prime(n):
    pass
```

**Comment by jsymons** [comment]
So while it's not the most effecient way, at this level we only expect you to brute force check to see if a number is prime, or in other words check all the numbers between 2 and n and see if they divide evenly into the number. Remember you can check if y divides evenly into x by doing `x % y == 0`
You could speed things up a bit if you first check if the number is even w/ `n % 2 == 0` and then you could just check the odd numbers, skipping all the even. If you want to get fancy you could look at implementing a [prime sieve](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)
