### ISSUE TITLE
More efficient way to write code

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#369]
Hi, I am able to pass both tests with the below code, but was wondering if there was a more efficient way to achieve the same result. I am not sure I need a while loop, and in addition I felt like the last if statement was a bit of a hack. Any thoughts?

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/no-uppercase-allowed

**User code**:
```python
def neutralize_uppercase(stringy):
    i=0
    while i<len(stringy):
        lowbrow=''
        for a in stringy:
            i+=1
            if a.islower()==True:
                lowbrow+=a
            else:
                lowbrow=''
        if lowbrow!=stringy:
            return ''
        else:
            return stringy
```

**Comment by jsymons** [comment]
So first off, when we mean to use a while loop to solve this it means to the exclusion of a for loop. The while loop isn't really doing anything here as it always only iterates once, and all the work is being done by your for loop.

What we would be looking for is something more like:
```python
def neutralize_uppercase(stringy):
    i = 0
    while i < len(stringy):
        if stringy[i].isupper():
            return ""
        i += 1
    return stringy
```
