### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#37]
I'm having trouble with line 6 and Line 7. Any hints as to what I'm doing wrong?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/string-of-numbers

**User code**:
```python
def string_of_numbers(length):
    output = str(1)
    sequence = 1
    while len(output) < length:
        output = output + (str(sequence + 1)
        sequence = sequence + 1
    return output
    pass

print(string_of_numbers(3))
```

**Comment by santiagobasulto** [comment]
@branhoff great attempt! I think it's just a missing parenthesis in the line `output = output + (str(sequence + 1)`. It should be `output = output + (str(sequence + 1) )`: https://repl.it/@santiagobasulto/PrudentWirySourcecode

**Comment by santiagobasulto** [comment]
@branhoff please close the issue if you think it's resolved.

**Comment by branhoff** [comment]
![image](https://user-images.githubusercontent.com/36856538/36984319-3e6f21cc-205a-11e8-94d2-02ddcad21854.png)

**Comment by branhoff** [comment]
@santiagobasulto Thanks for responding! I'm still having trouble with line 6 unfortunately, and I haven't the foggiest why.
