### ISSUE TITLE
Do not know how to do this

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#371]
Hi Jason,

Getting lost here and unable to come up with code.Did not go to solution. Can you please help?
Regards

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/identity-matrix

**User code**:
```python
def identity_matrix(size):
    pass
```

**Comment by santiagobasulto** [comment]
Hello @vidsjai! Have you tried anything to get started? As a hit, you should have a few nested for loops:

```python
for row in range(5):
    for column in range(5):
        # ...
```

**Comment by vidsjai** [comment]
Thanks Santiago. I did manage to get some part of it correct.Then used the solution given to arrive. at the code. I'm a bit confused still as to why there is a row =[] inside the for loop.

**Comment by jsymons** [comment]
There needs to be a row = [] in the for loop so that we generate a *new* row each iteration. If we did it outside the for loop all rows would be using the same list.
