### ISSUE TITLE
Having issues with the final output. Doesnt match expected result

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#373]
import random

def random_matrix(m, n):
    new_matrix=[]
    row_matrix=[]
    
    for row in range(m):
        number=random.randint(0,100)
        
        for column in range(n):
            if number not in row_matrix:
               row_matrix.append(number)
        new_matrix.append(row_matrix)
    
    return new_matrix

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/random-numbers-matrix

**User code**:
```python
import random

def random_matrix(m, n):
    new_matrix=[]
    number.random.randint(0,100)
    for row in range(m):
        row_matrix=[]
        for column in range(n):
            if number not in row_matrix:
               row_matrix.append(number)
        new_matrix.append(row_matrix)
    
    return new_matrix
            
```

**Comment by jsymons** [comment]
A couple of things, you're not generating your random number deep enough into your code, where it is now you're generating a single number per row. Secondly you're only adding a number if it's not in the row, you should be checking that it's not in *any* of the rows. Lastly if the number has already been used you need to keep generating new numbers until you get one that hasn't been used(a `while` loop would be useful for this), you can't skip doing the append or you're not going to get a properly sized matrix.
