### ISSUE TITLE
Having issues with the format function

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#374]
Hi, thew way I am approaching this problem is trying to take each row, format that appropriately, then bring it all together. I am getting stuck on the format function for the X/O strings.

I get the error "IndexError: tuple index out of range", which makes sense because the list has only one item ["O","O","X"].  I am trying to reference the index and format accordingly.

Any suggestions?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/format-board

**User code**:
```python
first_row='OOX'

s1="{0}  |  {2}  |  {3}"
print(s1.format(list(first_row)))
```

**Comment by jsymons** [comment]
`format` is going to treat `list(first_row)` as a *single* element, not the individual elements of that list.
Thus if your string has placeholders for 3 disparate values, and you're passing format a single parameter, it's going to give you an error. What you need to do is **unpack** your list.

Here's a quick example on how unpacking works:
```python
my_parameters = ('a', 'b', 'c')
my_function(*my_parameters)
```
is functionally the same as
```python
my_function('a', 'b', 'c')
```
