### ISSUE TITLE
throwing an error with first half code

### ISSUE THREAD

**Issue by mizjane07** [rmotr-curriculum/base-python-curriculum-questions#375]
Initially, I was throwing a float error, so I changed half_length = len(los //2).  Now, I'm throwing with the following line.

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/first-half

**User code**:
```python
def first_half(a_string):
    los = len(a_string)
    half_length = (len(los // 2)
    if los % 2 == 0:
        return a_string[half_length]
    else:
        return a_string[half_length + 1]
```

**Comment by jsymons** [comment]
You're almost there. 
```python
half_length = (len(los // 2)
```
should instead read
```python
half_length = los // 2
```
Then you're just missing your `:` in your return statements to indicate a slice, for example:
```python
return a_string[:half_length]
```
Without the `:` you're going to just return the char at `half_length` instead of all the chars up to `half_length`
