### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by selmabensaid** [rmotr-curriculum/base-python-curriculum-questions#377]
I don't understand why the code below returns a syntax error on the if statement.

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/subtract-reversed

**User code**:
```python
def subtract_reversed(a_list):
    If len(a_list)>0:
        last=a_list.pop()
        for n in a_list:
            last-=n 
        return last   
    else return 0    
        
```

**Comment by jsymons** [comment]
Python is case sensitive, your `If` needs to be `if`. Also you can't `else return 0`, it should be :
```python
else:
    return 0
```
