### ISSUE TITLE
Passing but correct?

### ISSUE THREAD

**Issue by msingh060** [rmotr-curriculum/base-python-curriculum-questions#378]
I know the assignment hinted at a while loop but if we are returning the power of two integers is it cleaner to use the power function (**) with the one exception if it is 0?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/the-power-of-while-loops

**User code**:
```python
def feel_the_power(initial_number, power):
    if power == 0:
        return 1
    else:
        return initial_number ** power


```

**Comment by jsymons** [comment]
`x ** 0` will still give you 1. But yes normally we would use `**` instead of looping, however we're explicitly using this for looping practice, thus the requirement to use a while loop.
