### ISSUE TITLE
assertion 1 and 4 failing

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#379]
assertion 1 failure

 Jai Dhandapani
 Log out
DESCRIPTION
QUESTIONS (4)
SOLUTIONS
Multi-search
Write a function search_animals that receives 3 parameters:
a required parameter called list_of_animals that receives a list of animal dictionaries
an optional parameter called given_name that will be used as an optional search term
* an optional parameter called animal_type that will be used as an optional search term

First, take a good look at the structure of the example animal list.

animals = [
        {
            "animal_type": "Raccoon",
            "street_name": "Trash Panda",
            "given_name":  "Gizmo"
        },
        {
            "animal_type": "Snake",
            "street_name": "Danger Noodle",
            "given_name":  "Spaghetti"
        },
        {
            "animal_type": "Snake",
            "street_name": "Danger Noodle",
            "given_name":  "Nope"
        },
        {
            "animal_type": "Penguin",
            "street_name": "Formal Chicken",
            "given_name":  "Mclovin"
        },
        {
            "animal_type": "Sting ray",
            "street_name": "Sea Pancake",
            "given_name":  "Flap Flap"
        },
        {
            "animal_type": "Guinea Pig",
            "street_name": "Furry Potato",
            "given_name":  "Alf"
        },
        {
            "animal_type": "Platypus",
            "street_name": "Duck Puppy",
            "given_name":  "Bill"
        },
        {
            "animal_type": "Seagull",
            "street_name": "Beach Chicken",
            "given_name":  "Santiago"
        },
        {
            "animal_type": "Ferret",
            "street_name": "Cat Snake",
            "given_name":  "Will Ferret"
        }
]
The goal is to be able to search this list of animals by the animal's given_name and/or the animal_type, for each of those combinations.

Optional arguments enable you to have these types of search combinations.

If they enter a given_name search term, you'll want to check all the animals in the list and see if the search term is in their value associated with the key given_name.

There could be multiple matches, so we want to store our matching animal dictionaries in a list.

Do the same thing for animal_type search term, but for that check if the search term is in either the value associated with the key animal_type OR street_name. Hope you remembered your operators lessons :)

Your default values here should be set to None by default so it is easy to check what kind of search the user is doing based on which of the optional arguments aren't None.

Best of luck!

search_animals(animals, given_name="Will Ferret") == [
        {
            "animal_type": "Ferret",
            "street_name": "Cat Snake",
            "given_name":  "Will Ferret"
        }]
Test Cases
 Test Search Animal Type - RUN TEST
expected_animal_types = [{
    'animal_type': 'Penguin',
    'given_name': 'Mclovin',
    'street_name': 'Formal Chicken'
}, {
    'animal_type': 'Seagull',
    'given_name': 'Santiago',
    'street_name': 'Beach Chicken'}
]

def test_search_animal_type():
    assert search_animals(animals, animal_type="Chicken") == expected_animal_types

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-functions/multi-search

**User code**:
```python
# Write your function here!
def search_animals(animals,given_name=None,animal_type=None):
    
    given_name_list=[]
    animal_type_list=[]
    for animal in animals:
        if given_name==animal["given_name"]:
           given_name_list.append(animal)
    return given_name_list
        
    for anitype in animals:
        if animal["animal_type"]==anitype or animal["street_name"]==anitype:
            animal_type_list.append(anitype)
    return animal_type_list 

# Please keep this list of animals here (don't change it or remove it):
animals = [
    {
        "animal_type": "Raccoon",
        "street_name": "Trash Panda",
        "given_name": "Gizmo"
    },
    {
        "animal_type": "Snake",
        "street_name": "Danger Noodle",
        "given_name": "Spaghetti"
    },
    {
        "animal_type": "Snake",
        "street_name": "Danger Noodle",
        "given_name": "Nope"
    },
    {
        "animal_type": "Penguin",
        "street_name": "Formal Chicken",
        "given_name": "Mclovin"
    },
    {
        "animal_type": "Sting ray",
        "street_name": "Sea Pancake",
        "given_name": "Flap Flap"
    },
    {
        "animal_type": "Guinea Pig",
        "street_name": "Furry Potato",
        "given_name": "Alf"
    },
    {
        "animal_type": "Platypus",
        "street_name": "Duck Puppy",
        "given_name": "Bill"
    },
    {
        "animal_type": "Seagull",
        "street_name": "Beach Chicken",
        "given_name": "Santiago"
    },
    {
        "animal_type": "Ferret",
        "street_name": "Cat Snake",
        "given_name": "Will Ferret"
    }
]
# Please keep this list of animals here
```

**Comment by jsymons** [comment]
Again, between reading tests and reading the error messages you are getting you can usually figure out what is wrong with your code. Let's take the first test and see what error we're getting:
```
tests.py:97: in test_search_animal_type
    assert search_animals(animals, animal_type="Chicken") == expected_animal_types
E   AssertionError: assert [] == [{'animal_type': 'Penguin', ...eet_name': 'Beach Chicken'}]
E     Right contains more items, first extra item: {'animal_type': 'Penguin', 'given_name': 'Mclovin', 'street_name': 'Formal Chicken'}
E     Full diff:
E     - []
E     + [{'animal_type': 'Penguin',
E     +   'given_name': 'Mclovin',
E     +   'street_name': 'Formal Chicken'},
E     +  {'animal_type': 'Seagull',...
E     
E     ...Full output truncated (3 lines hidden), use '-vv' to show
```
So let's look deeper into this:
```
    assert search_animals(animals, animal_type="Chicken") == expected_animal_types
E   AssertionError: assert [] == [{'animal_type': 'Penguin', ...eet_name': 'Beach Chicken'}]
E     Right contains more items, first extra item: {'animal_type': 'Penguin', 'given_name': 'Mclovin', 'street_name': 'Formal Chicken'}
```
So the test is expecting the return from `search_animals(animals, animal_type="Chicken")` to be equal to `expected_animal_types` supplied by the test. For reference this is `expected_animal_types`:
```python
expected_animal_types = [{
    'animal_type': 'Penguin',
    'given_name': 'Mclovin',
    'street_name': 'Formal Chicken'
}, {
    'animal_type': 'Seagull',
    'given_name': 'Santiago',
    'street_name': 'Beach Chicken'}
]
```
Now let's look what we're getting:
```
E   AssertionError: assert [] == [{'animal_type': 'Penguin', ...eet_name': 'Beach Chicken'}]
```
This tells us that our function is returning an empty list, which is of course not what we want, so let's look at our code:
```python
def search_animals(animals,given_name=None,animal_type=None):
    
    given_name_list=[]
    animal_type_list=[]
```
So above we're initializing two empty lists, one of these is probably what's getting returned. Let's continue...
```python
    for animal in animals:
        if given_name==animal["given_name"]:
           given_name_list.append(animal)
```
In this test we're not supplying `given_name` so it will be `None` so the if statement never triggers so we can basically ignore what is happening in this loop. Let's continue...
```python
    return given_name_list
```
Here's our problem. We're returning `given_name_list` which is currently empty. We have to remember when we encounter a `return` it *immediately* executes and further execution of the function stops, so the code further down in the function is never going to be executed. So to fix this we have to do all our determination if an animal matches the search terms **before** we return anything.
