### ISSUE TITLE
Where are the strings documented?

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#38]
In the video he references a source for documented strings. Is there a link posted somewhere?

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/python-strings

**Comment by santiagobasulto** [comment]
Hey Brandon! I should add them to the lesson, thanks for the reminder. Here they're, just in case:

* [Py 2 docs](https://docs.python.org/2/library/string.html)
* [Py 3 docs](https://docs.python.org/3/library/string.html)
* [String formatting](https://pyformat.info/)
