### ISSUE TITLE
Comparing two lists

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#382]
Hi, in the code below, I create a new list using a helper function with only unique values from the first list. I am having issues comparing the two and counting the number of repetitions.

Essentially, I want a counter per letter. If I don't know the list values in advance, I am not sure how to make if statements that would increase the counters appropriately. I could hard code the unique list values in the test cases and pass the tests but would rather make the code more dynamic for different data types and or long lists.

Is there a better way to approach this than the way I have? I am avoiding looking at the solution until I figure this out haha

Would appreciate any guidance, thanks.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/count-occurrences

**User code**:
```python
def find_keys(a_list):
    comper=[]
    for y in a_list:
        if y not in comper:
            comper.append(y)
    return comper


def count_occurrences(a_list):
    comp=find_keys(a_list)
    counter=0
    for x in comp:
        if x in a_list:
            counter+=1
        else:
            comp.append(x)
    return counter, a_list, comp

y=count_occurrences(["a", "b", "c", "a", "a", "b"])
print(y)
```

**Comment by jsymons** [comment]
I think you're way overcomplicating this.
Dictionaries have a method called `setdefault` that allows you to ensure a key exists in a dictionary. It basically works like this:
```python
my_dict.setdefault(my_key, default_value)
```
which is functionally equivalent to:
```python
if my_key not in my_dict:
    my_dict[my_key] = default_value
```
Using that will simplify things greatly, you can just iterate over the items in the list, `setdefault` to make sure your counter for that letter exists, and increment that counter.
