### ISSUE TITLE
Getting syntax error

### ISSUE THREAD

**Issue by mizjane07** [rmotr-curriculum/base-python-curriculum-questions#384]
I'm forgetting the proper order of the conditional statement.  should else come before the return statement?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/subtract-reversed

**User code**:
```python
def subtract_reversed(a_list):
  
    if len(a_list) > 0:
        last = a_list.pop()
        for n in a_list:
            last -= n 
    return last  
    
    else:
        return 0
```

**Comment by jsymons** [comment]
The `return` should be indented further so it's inside the if statement.
