### ISSUE TITLE
Last loop

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#385]
Hi, having trouble with my last loop, adding the sums to the keys a, b and c. I want to reference the appropriate index value of the "added" list for a, b and c, which is 0, 1 and 2, respectively and update appropriately.

Any thoughts?

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/sum-of-dict-values

**User code**:
```python
def sum_of_dict_values(d1, d2, d3):
    l1=[]
    l2=[]
    l3=[]
    for x, y, z in d1.values(), d2.values(), d3.values():
        if type(x)==int:
            l1.append(x)
        else:
            l1.append(None)
        if type(y)==int:
            l2.append(y)
        else:
            l2.append(None)
        if type(z)==int:
            l3.append(z)
        else:
            l3.append(None)
    added=[]
    for b in l1,l2,l3:
        if None not in b:
            added.append(sum(b))
        else:
            added.append(None)
        
    sum_dict={
        'a':None,
        'b':None,
        'c':None
             }
    
    for key,value in sum_dict.items():
        for i in range(len(added)):
            sum_dict[key]=added[i]
    return sum_dict
```

**Comment by jsymons** [comment]
I think you've overcomplicated things here.
First, we can assume that the keys among all the dictionaries are the same, which means we just need to iterate over the keys of one of them:
```python
for key in d1:
```
We can then check if all the values across those dictionaries are integers:
```python
if type(d1[key]) == int and type(d2[key]) == int and type(d3[key]) == int:
```
If it's true we can sum those values and store it in our return dictionary, if it's not we can set the value in the return dictionary for that key to `None`.
If you need further assistance on this please let me know.
