### ISSUE TITLE
strings in strings

### ISSUE THREAD

**Issue by msingh060** [rmotr-curriculum/base-python-curriculum-questions#386]
Not sure where I am getting stuck here although I know it is different from the solution provided. In the given solution though can you walk through how it would add more than 1 to the total if, for example, s1 occurred more than once?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/all-in-string

**User code**:
```python
def all_in_string(a_string, s1, s2, s3):
    count = 0 
    if s1 in a_string:
        count = a_string.count(s1)
    elif s2 in a_string:
        count += a_string.count(s2)
    elif s3 in a_string:
        count += a_string.count(s3)
    
    return count    
```

**Comment by jsymons** [comment]
If you look at the tests we aren't looking for you to increase the return value for each occurrence. Count should only be increased once if s1 is present (regardless how many times), same for s2 and s3. So the return value should **never** be higher than 3, no matter how many times s1, s2 or s3 occur in a_string.
