### ISSUE TITLE
All assertions failing

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#387]
Can you please help?Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/reimplement-pop

**User code**:
```python
def pop(dictionary, key, default_value=None):
    
    try:
        for keydict,val in dictionary.items():
           if key==keydict:
              del dictionary[keydict]
           return dictionary
     
    except KeyError:
         if default_value !=None:
             raise KeyError("Key Error")
         else:
            return default_value
```

**Comment by jsymons** [comment]
You can't change the size of a dictionary (by deleting items in it for example) while iterating over it, Python throws an error when you try. Even if that wasn't happening, you're returning inside your for loop, which will break your loop as soon as it hits the return statement.
