### ISSUE TITLE
indexing in for loop

### ISSUE THREAD

**Issue by msingh060** [rmotr-curriculum/base-python-curriculum-questions#389]
I know I can get to the right answer this way but not sure I really understand fundamentally how reassigning C to the total variable is able to sum the various values in a list. From our earlier understanding isn't the variable c in the for loop keeping track of the index of the string/list, and therefore in the final loop c would just be reassigned to the sum of the indices corresponding to the characters or items in a list? Am I just confusing the use of the for loop with a string vs a list?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/get-average

**User code**:
```python
def get_average(list_of_numbers):
    total = 0 
    for c in list_of_numbers:
        total += c
    return (total / len(list_of_numbers))

```

**Comment by jsymons** [comment]
`c` here is not the index but the actual elements so if I were iterating over `[3, 6, 9]` on the first iteration `c` would be `3`, on the second it would be `6`, and on the third it would be `9`.
