### ISSUE TITLE
Why is my is_prime function wrong?

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#39]
I'm trying to use a while loop to identify when a number's remainder is 0. But it always returns a 1. Where is the logic in my code wrong?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def reverse_str(s):
    # Please don't change me
    return s[::-1]

def is_palindromic(n):
    if str(n) == reverse_str(str(n)):
        return True
    else:
        return False
    pass

def is_prime(n):
    i = 2
    result = n % i
    while i < n and result is 1:
        i += 1
    return result

def next_palindromic_prime(n):
    pass

print(is_prime(9))

print(9 % 3 )



```

**Comment by jsymons** [comment]
You're not updating `result`.
Also `is_prime` is supposed to return `True` or `False`, so you'll need to add some logic for handling that.

**Comment by santiagobasulto** [comment]
@branhoff can you close this one if it's resolved? Thanks!
