### ISSUE TITLE
reversed range 

### ISSUE THREAD

**Issue by selmabensaid** [rmotr-curriculum/base-python-curriculum-questions#390]
Can you please help me understand why the reversed range is not working in the code below?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/advanced-nested-pyramids

**User code**:
```python
def advanced_nested_pyramid(height, char, order):
    pyramid=""
    if order=="ASC":
        
        
        for n in range (height):
            line =""
            for _ in range (n+1):
                line+=char
            line+="\n"
            pyramid+=line
            
    elif order=="DESC":
        
        for n in range (height):
            line=""
            for _ in range(n+1,0,-1):
                line+=char
            line+="\n"
            pyramid+=line
    return pyramid
    
print(advanced_nested_pyramid(5, '*', "DESC"))
```

**Comment by jsymons** [comment]
You want `height-n` instead of `n+1` on your internal loop. Using n+1 is just going to give you `n+1` characters per line, using `height-n` will instead give us starting from `height` chars and each following line will have one less char until we hit 0.
