### ISSUE TITLE
dict ---> list?

### ISSUE THREAD

**Issue by msingh060** [rmotr-curriculum/base-python-curriculum-questions#393]
Can you explain why something like this isn't working? I thought we could return max value in .values of a dict...

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/saving-the-largest-value

**User code**:
```python
def get_largest_numbers(d1, d2, d3):
    result = {}

    for value in d1.value():
        if type(value) is not int:
            result[d1] = None
        return result[d1] = max(d1.values())
    
    for value in d2.value():
        if type(value) is not int:
            result[d2] = None
        return result[d2] = max(d2.values())
            
    for value in d3.value():
        if type(value) is not int:
            result[d3] = None
       return result[d3] = max(d3.values())
    
    return result
```

**Comment by jsymons** [comment]
Your returns inside your for loops are going to break things. As soon as a `return` is encountered execution immediately stops and the function returns. This means anything inside the function past the return will not be executed, the return will even break out of loops.
