### ISSUE TITLE
length in nested dicts

### ISSUE THREAD

**Issue by msingh060** [rmotr-curriculum/base-python-curriculum-questions#395]
when we add the new values into the empty result dict with the values (number of cust) as len(customers) how is that returning an int? isn't it a newly defined variable in the for loop that is referring to a different value (in the key, value pair) each iteration of the loop?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/number-of-customers-per-state

**User code**:
```python
def number_of_customers_per_state(customers_dict):
    result = {}
    for state, customers in customers_dict.items():
        if customers:
            result[state] = len(customers)
        else:
            result[state] = 0 
    
    return result
```

**Comment by jsymons** [comment]
`result[state] = len(customers)` is going to set the value in `result` associated with the key `state` (state is just a variable, it's actual value will change each iteration) with the result of `len(customers)` (where customers is going to be the list that's associated with a particular state in `customers_dict`) which will be an int as `len` returns an int.
