### ISSUE TITLE
Continue...

### ISSUE THREAD

**Issue by msingh060** [rmotr-curriculum/base-python-curriculum-questions#396]
The if statements check to make sure that the provided info is not None AND they are not in the dictionary is that correct? If both those parameters are met then it moves onto the "continue" statement. If an animal not in the dict was passed would the code stop here ie: add nothing to the result list? Just struggling to see flow-wise how the code actually gets to the append line. Shouldn't the "if animal_type" be an elif instead?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-functions/multi-search

**User code**:
```python
def search_animals(list_of_animals, given_name = None, animal_type = None):
    result = []
    for animal in animals:
        if given_name:
            if given_name not in animal['given_name']:
                continue    
        if animal_type:
            if animal_type not in animal['animal_type'] and animal_type not in animal['street_name']:
                continue
        result.append(animal)
    return result



# Please keep this list of animals here (don't change it or remove it):
animals = [
    {
        "animal_type": "Raccoon",
        "street_name": "Trash Panda",
        "given_name": "Gizmo"
    },
    {
        "animal_type": "Snake",
        "street_name": "Danger Noodle",
        "given_name": "Spaghetti"
    },
    {
        "animal_type": "Snake",
        "street_name": "Danger Noodle",
        "given_name": "Nope"
    },
    {
        "animal_type": "Penguin",
        "street_name": "Formal Chicken",
        "given_name": "Mclovin"
    },
    {
        "animal_type": "Sting ray",
        "street_name": "Sea Pancake",
        "given_name": "Flap Flap"
    },
    {
        "animal_type": "Guinea Pig",
        "street_name": "Furry Potato",
        "given_name": "Alf"
    },
    {
        "animal_type": "Platypus",
        "street_name": "Duck Puppy",
        "given_name": "Bill"
    },
    {
        "animal_type": "Seagull",
        "street_name": "Beach Chicken",
        "given_name": "Santiago"
    },
    {
        "animal_type": "Ferret",
        "street_name": "Cat Snake",
        "given_name": "Will Ferret"
    }
]
# Please keep this list of animals here
```

**Comment by jsymons** [comment]
So either one of the keyword arguments (or both) can be passed in, so we need to not exclusively check one or the other in the case of both being passed, the outer if statements only trigger if that search term has been passed in as `None` is a falsey value. So the way we get to the append is if neither of the inner if statements trigger, as those cause the continue to happen. So basically if `given_name` is supplied and we find a match for it, or `animal_type` is supplied and we find a match for it, or both are supplied and we find something that matches both. Now when I say 'match' here I mean that the corresponding inner if statement evaluates `False`.
