### ISSUE TITLE
TypeError: an integer is required (got type datetime.date)

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#398]
Hi, getting a type error when trying to run the below code - any thoughts?

**Assignment**: http://learn.rmotr.com/python/base-python-track/modules-and-packages/nice-looking-date

**User code**:
```python
import datetime
from datetime import date

def format_date(a_date):
    d = datetime.date(a_date).strftime("%A, %B %e, %Y")
    return d

x=format_date(date(1964, 7, 31))
print(x)
```

**Comment by jsymons** [comment]
`a_date` is already a date object, so you can just call `strftime` directly on it.
