### ISSUE TITLE
NameError: name 'datetime' is not defined

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#399]
Getting a name error - looks like the package isn't being imported. Do I need to import within the function?

**Assignment**: http://learn.rmotr.com/python/base-python-track/modules-and-packages/nice-looking-date

**User code**:
```python
from datetime import date

def format_date(a_date):
    d = datetime.date(a_date).strftime("%A, %B %e, %Y")
    return d

x=format_date(date(1964, 7, 31))
print(x)
```

**Comment by jsymons** [comment]
You're doing `from datetime import date` which just imports `date` from datetime which you would just call as `date` to call `datetime.date` you would `import datetime` instead of `from datetime import date`
