### ISSUE TITLE
wrong syntax

### ISSUE THREAD

**Issue by selmabensaid** [rmotr-curriculum/base-python-curriculum-questions#400]
can you please help me understand what's wrong with my try/except syntax?

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/breaking-math

**User code**:
```python
def divide(a, b):
    try:
        return a/b 
    except ValueError as e:
        print ('ZeroDevision')
        
```

**Comment by jsymons** [comment]
Your except is trying to catch a `ValueError`, it needs to catch a `ZeroDivisionError` and then inside the except raise the `ValueError` instead
