### ISSUE TITLE
Dictionary Comprehension - count_words

### ISSUE THREAD

**Issue by tking99** [rmotr-curriculum/base-python-curriculum-questions#401]
Hello, Is there a way to use dictionary comprehension to make the count_words function more pythonic in my solution. I cant seem to find a way to set the keys as 'w' and assign +=1 to the values if keys is repeated through a single dictionary comprehension. 
Thanks 

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/analyze-string

**User code**:
```python
def count_words(a_string):
    words = a_string.split()
    word_count_dict = {}
    for w in words:
        word_count_dict.setdefault(w,0)
        word_count_dict[w] +=1 
    return word_count_dict
        

def get_list_of_duplicates(word_count_dict):
    sorted_list = [k for k,v in word_count_dict.items() if v > 1]
    return sorted_list
    
```

**Comment by jsymons** [comment]
`{word: a_string.count(word) for word in set(a_string.split())}`
