### ISSUE TITLE
zip function

### ISSUE THREAD

**Issue by tking99** [rmotr-curriculum/base-python-curriculum-questions#402]
Hello, Is it good practise to use the zip function for this problem and use a for loop to loop over the three dictionaries at the same time? Or is that not recommended? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/sum-of-dict-values

**User code**:
```python
def sum_of_dict_values(d1, d2, d3):
    sum_dict = {}
    for (k1,v1), (k2,v2),(k3,v3) in zip(d1.items(), d2.items(), d3.items()):
        if type(v1) != int or type(v2)!= int or type(v3)!=int:
            sum_dict[k1] = None
        else:
            sum_dict[k1] = (v1 + v2 + v3)
    return sum_dict
    

```

**Comment by jsymons** [comment]
So we can make the assumption here that the keys are the same across the dictionaries (otherwise we wouldn't be able to sum them), so given that you can just iterate over the keys from one:
```python
def sum_of_dict_values(d1, d2, d3):
    results = {}
    for key in d1:
        if type(d1[key]) != int or type(d2[key]) != int or type(d3[key]) != int)):
            results[key] = None
        else:
            results[key] = d1[key] + d2[key] + d3[key]
    return results
```
This results in something that's a bit cleaner than attempting to iterate over all the keys and values.
