### ISSUE TITLE
Cannot get KeyError to be raised

### ISSUE THREAD

**Issue by vchau76** [rmotr-curriculum/base-python-curriculum-questions#406]
I cannot get the KeyError exception to be raised.  From what I understand of my code, under the Try statement, it checks first to see if the key is present in the dictionary and if it is, I pop that key from the dictionary.  If the key is not present, but a default value is, it returns that default value.  All other cases it should throw the exception.  What am I doing wrong?

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/reimplement-pop

**User code**:
```python
def pop(dictionary, key, default_value=None):
    for k, v in dictionary.items():
        try:
            if k == key:
                return dictionary.pop(k,v)
            if default_value:
                return default_value
        except KeyError as err:
            raise err
```

**Comment by santiagobasulto** [comment]
Vinh! You're explicitly checking if the key exist. If the key doesn't exist, you're returning the value. Your code is actually very good, but it'll never raise an exception. Try removing the `if k == key:` part.

**Comment by vchau76** [comment]
So if I understand you correctly, if the second IF statement is called, it will always return the default value, whether that is what is in the parameter or the default value of 'None'.  Is this correct?

I tried removing the k == key part, but it seems that I need that or else it pops the first instance of the key/value pair.  I still cannot get it to work based off my code.

**Comment by vchau76** [comment]
I cleaned the code up a little but still can't get exception to be raised.  The first two tests pass (invalid key default, valid key) but not the invalid key with no default.

```
def pop(dictionary, key, default_value=None):
    try: 
        return dictionary.pop(key,default_value)
    except KeyError as err:
        raise err
```

**Comment by santiagobasulto** [comment]
@vchau76 the `pop` method will NEVER raise an exception, because that's how it's designed. Go back again to the regular `dictionary[key]` and try returning the `default` value inside your except block.
