### ISSUE TITLE
KeyError 'horse'

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#407]
Hi for the first test, I am receiving a KeyError when searching for horse in the dictionary. I think the issue is with my first if statement (which I am thinking is checking if it exists or not). If it doesn't exist, it should return the default value.

Not sure why it isn't working, any thoughts?

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/reimplement-pop

**User code**:
```python
def pop(dictionary, key, default_value=None):
    try:
        if dictionary[key]:
            entry = dictionary[key]
            del dictionary[key]
            return entry
        else:
            if default_value!=None:
                return default_value
    except:
        raise KeyError
        
```

**Comment by jsymons** [comment]
As per the discussion we had in mentor hours, eliminate your if statement and change the else into an if while moving it into the except
