### ISSUE TITLE
exceptions

### ISSUE THREAD

**Issue by msingh060** [rmotr-curriculum/base-python-curriculum-questions#408]
I am failing when the key doesn't exist but not sure why

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/reimplement-pop

**User code**:
```python
def pop(dictionary, key, default_value=None):
    try:
        removed = dictionary[key]
        del dictionary[key]
        return removed
        
    except keyError as e:
        if default_value:
            return default_value
        raise e

```

**Comment by santiagobasulto** [comment]
The code is fine, the only issue is that the exception should be `KeyError`, with a capital `K`. The rest is perfect!
