### ISSUE TITLE
too sweet test failing

### ISSUE THREAD

**Issue by msingh060** [rmotr-curriculum/base-python-curriculum-questions#409]
Not sure why the second test on my code is failing here

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/healthy-recipes-only

**User code**:
```python
# Define TooSweetException here
class TooSweetException(Exception):
    pass

# Define TooManyCalsException here
class TooManyCalsException(Exception):
    pass


def recipe_calculator(ingredients):
    """Calculates sweetness and calories of a recipe"""
    sucre = 0 
    k = 0 
    for ingredient in ingredients:
        k += ingredient['calories']
        sucre += ingredient['sweetness']
    
    if k > 800:
        raise TooManyCalsException("Too many cals!")
    if sucre > 8:
        raise TooSweetException('Too sweet!')

    return (sucre, k)
        
    

# Don't delete this!
UNIT_OF_CHOCOLATE = {
    'name': 'Chocolate',
    'calories': 300,
    'sweetness': 2
}

UNIT_OF_SUGAR = {
    'name': 'Sugar',
    'calories': 200,
    'sweetness': 4
}

UNIT_OF_BUTTER = {
    'name': 'Butter',
    'calories': 250,
    'sweetness': 1
}

UNIT_OF_WATER = {
    'name': 'Water',
    'calories': 0,
    'sweetness': 0
}

UNIT_OF_FLOUR = {
    'name': 'Flour',
    'calories': 100,
    'sweetness': 1
}

UNIT_OF_EGG = {
    'name': 'Egg',
    'calories': 50,
    'sweetness': 0
}

UNIT_OF_BACON = {
    'name': 'Bacon',
    'calories': 350,
    'sweetness': 3
}
```

**Comment by santiagobasulto** [comment]
It's pretty clear from the error message. The test is expecting a `TooSweetException` exception to be raised, but your code is raising `TooManyCalsException`. Check your logic there.

![image](https://user-images.githubusercontent.com/872296/55564030-6e47e280-56cd-11e9-8187-42116103eb42.png)

**Comment by msingh060** [comment]
is it really just a matter of changing the order of the if statements (I moved the sucre before k and it seems to pass the tests now)? I would have thought that an exception wouldn't be raised on the first if statement and it would just move onto the next. Am I thinking about this in the wrong way?
