### ISSUE TITLE
Help understanding why this wouldn't work

### ISSUE THREAD

**Issue by tlinc02** [rmotr-curriculum/base-python-curriculum-questions#411]
I'm trying to understand why this wouldn't work:
if a_boolean == True:
        return '1'

The error I get is:
tests.py:27: in test_true_value
    assert convert_bool_to_binary(True) == 1
E   AssertionError: assert '1' == 1
E    +  where '1' = convert_bool_to_binary(True)

Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/convert-boolean-to-binary

**User code**:
```python
def convert_bool_to_binary(a_boolean):
    #return 1 if a_boolean == True else 0
    if a_boolean == True:
        return '1'
```

**Comment by jsymons** [comment]
Your return statement should be `return 1` having the quotes around 1 makes it a string
