### ISSUE TITLE
Test Cases do not seem to complete

### ISSUE THREAD

**Issue by tlinc02** [rmotr-curriculum/base-python-curriculum-questions#413]
They just go round and never completes.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/help-a-string-get-lucky

**User code**:
```python
def get_lucky(poor_string, lucky_number):
    counter = 0
    while counter < lucky_number:
        poor_string += "7"
        counter + 1
```

**Comment by jsymons** [comment]
`counter + 1` should be `counter += 1`, without the = you aren't modifying the value of `counter` which means you have an infinite loop.
