### ISSUE TITLE
Logic to remove the third dash line row

### ISSUE THREAD

**Issue by YuchuanWeng** [rmotr-curriculum/base-python-curriculum-questions#417]
I failed to pass the tests. I think the issue is i have the third dash line row when i print it. Should i introduce a new variable or how could i output it simplier? Thank you

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/format-board

**User code**:
```python
def format_tic_tac_toe_board(first_row, second_row, third_row):
    count = 0
    res_first = ''

    
    for x in (first_row, second_row, third_row):
        for s in x:
            if count < 2:
                res_first += str(s)
                res_first += '  |  '
            else:
                res_first += str(s)
            count +=1
        res_first = res_first + "\n--------------\n"
        count = 0
    return res_first
```

**Comment by santiagobasulto** [comment]
Hey @YuchuanWeng! You don't need to take an "imperative" approach here, just use the `BOARD_TEMPLATE` defined variable.

As a summary, you can implement this whole lesson WITHOUT even using a single `for` or `while` loop.
