### ISSUE TITLE
Extra dash at end

### ISSUE THREAD

**Issue by zli715** [rmotr-curriculum/base-python-curriculum-questions#418]
I understand the solutions that were posted but I'm trying out different code and wondering why the output shows an extra dash after the 'me' at the end?

AssertionError: assert 'Pyt-hon- is- Aw-eso-me-' == 'Pyt-hon- is- Aw-eso-me'

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/insert-dashes-every-3-characters

**User code**:
```python
def insert_dashes(a_string):
    output = ''
    for i in range(0, len(a_string)-1, 3):
        output += a_string[i:i+3] + '-'
    return output
```

**Comment by jsymons** [comment]
`output += a_string[i:i+3] + '-'` is always going to leave a trailing '-' which you'll want to trim off.
