### ISSUE TITLE
Solution not being provided after failing over 10 times

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#42]
I am trying to access the solution for this assignment and it wont give me access.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-oop/country-methods

**User code**:
```python
class Country(object):
    # your methods here
    def population_density(self):
        return (self.population/self.area_in_km2)
         
    def area(self, unit='km2'):
        if unit == 'km2':
            return self.area_in_km2
        elif unit =='mi2': 
            return self.area_in_km2 * 0.3861
        elif unit == 'acres':
            return self.area_in_km2 * 247
        elif unit == 'hectares':
            return self.area_in_km2 * 100
        else:
            raise ValueError('InvalidAreaUnitException')
    
    def gdp_per_capita(self):
        return (self.total_gdp/self.population)


# vv Don't change these objects vv
usa = Country()
usa.name = 'United States of America'
usa.population = 325719178  # 325,719,178
usa.area_in_km2 = 9833520  # 9,833,520 km2
usa.total_gdp = 20199000000000  # 20.199 trillion

canada = Country()
canada.name = 'Canada'
canada.population = 35151728  # 35,151,728
canada.area_in_km2 = 9984670  # 9,984,670 km2
canada.total_gdp = 1836000000000  # 1.836 trillion
# ^^ Don't change these objects ^^
```

**Comment by jsymons** [comment]
Solutions shouldn't show up until you've either solved the problem or submitted at least 5 failed attempts. If you've done either of these and it's still not showing up, try refreshing the page.

**Comment by santiagobasulto** [comment]
@AndyDeNike you can also find the solutions by inspecting the source code of the assignment:
![image](https://user-images.githubusercontent.com/872296/37162486-237e2684-22d4-11e8-8a23-ed140a1148e6.png)


Here's the solution of this one: https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-15-intro-to-oop/lesson-8-country-methods/solutions/solution_.py
