### ISSUE TITLE
Comparison between the suggested solution and mine

### ISSUE THREAD

**Issue by YuchuanWeng** [rmotr-curriculum/base-python-curriculum-questions#421]
Except the code is cleaner in the suggested solution, is there any reason i shall not write the code in this way (below my code)? Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/count-in-even-odd-positions

**User code**:
```python
def count_in_position(a_string, a_char, position_type):
    total = 0
    for ind, char in enumerate(a_string):
        if position_type == 'even' and ind % 2 == 0:
            if char == a_char:
                total += 1
        elif position_type == 'odd' and ind % 2 != 0:
            if char == a_char:
                total += 1
    return total
```

**Comment by santiagobasulto** [comment]
This is perfect @YuchuanWeng! It's pretty common to have multiple solutions that provide the same results. Usually the variables to compare them are: readability, performance, extensibility, robustness, etc. This is a great solution!
