### ISSUE TITLE
Code appears to work when Run, but assert statements fail

### ISSUE THREAD

**Issue by roccocervantes** [rmotr-curriculum/base-python-curriculum-questions#424]
The code I have is attached. When I plug in the example rows in the assert statement and run the code it generates a board that looks appropriately formatted and accurate. However, when I press "submit solution" the assert statements fail, and the error is quite difficult to read. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/format-board

**User code**:
```python
def format_tic_tac_toe_board(first_row, second_row, third_row):
    tl = ""
    tm = ""
    tr = ""
    ml = ""
    mm = ""
    mr = ""
    bl = ""
    bm = ""
    br = ""
    # final_first = ""
    # final_second = ""
    # final_third = ""
    # divider = ""
    # divider = "--------------"
    # assembled_board = """"""
    tl = first_row[0]
    tm = first_row[1]
    tr = first_row[2]
    ml = second_row[0]
    mm = second_row[1]
    mr = second_row[2]
    bl = third_row[0]
    bm = third_row[1]
    br = third_row[2]
    final_board = ""
    final_board = """
    {}  |  {}  |  {}
    --------------
    {}  |  {}  |  {}
    --------------
    {}  |  {}  |  {}
    """.format(tl, tm, tr, ml, mm, mr, bl, bm, br)
    return final_board
    
first_row = 'XOX'
second_row = 'OXO'
third_row = 'OOX'

print(format_tic_tac_toe_board(first_row,second_row,third_row))
    
    
    
    # final_first = "{}  |  {}  |  {}".format(tl, tm, tr)
    # final_second = "{}  |  {}  |  {}".format(ml, mm, mr)
    # final_third = "{}  |  {}  |  {}".format(bl, bm, br)
    # assembled_board = final_first + "\n" + divider + "\n" + final_second + "\n" + divider +        "\n" + final_third
    # return assembled_board
```

**Comment by santiagobasulto** [comment]
Hello @roccocervantes! This assignment is A LOT easier than what it seems. You have to use in the `format` method, the individual positions you have, for example:

```python
final_board = """
    {}  |  {}  |  {}
    --------------
    {}  |  {}  |  {}
    --------------
    {}  |  {}  |  {}
    """.format('X', 'O', 'X', ... the others here...)
```

**Comment by roccocervantes** [comment]
Hi Santiago - thanks for the quick help. A bit confused, isn't this what I'm doing? I'm pulling the values of each "cell" of the table into a variable, and then I use the .format function to return the final board. I was playing around with dividers and such, but I commented that out.

**Comment by santiagobasulto** [comment]
@roccocervantes you're absolutely right, my bad. Let me check spaces and i'll get back to you.

**Comment by roccocervantes** [comment]
Thank you!

**Comment by santiagobasulto** [comment]
Yes, so, the problem is that your code contains "tabs" or whitespaces at the beginning of the string. This doesn't "look" so, but Python is very strict. For example, `'X'` is not the same as `'    X'` (note the whitespace).

So, the solution is just to define the template above, without any tabs:

```python
BOARD_TEMPLATE = """
{0}  |  {1}  |  {2}
--------------
{3}  |  {4}  |  {5}
--------------
{6}  |  {7}  |  {8}
"""


def format_tic_tac_toe_board(first_row, second_row, third_row):
    pass # your code
```

Don't use `final_board`, just use `BOARD_TEMPLATE` and it should work:

![image](https://user-images.githubusercontent.com/872296/56085784-a06ce900-5e1f-11e9-9b65-85d8b8937147.png)

**Comment by roccocervantes** [comment]
Ahh I see, got it. Thanks! That worked.
