### ISSUE TITLE
Reverse list method

### ISSUE THREAD

**Issue by naakaisa** [rmotr-curriculum/base-python-curriculum-questions#426]
Is it possible to use the list reverse method - list.reverse() in this case

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/reverse-a-list

**User code**:
```python
def reverse_a_list(list):
   return list.reverse()
```

**Comment by jsymons** [comment]
The problem with using `reverse` is that it's going to modify the original list that was passed in. Also, `reverse` doesn't return anything so if you wanted to use it you would have to do something like this:
```python
def reverse_a_list(a_list):
    a_list.reverse()
    return a_list
```
But again this is going to modify the original list, for example:
```python
my_list = [1, 2, 3]
my_reversed_list = reverse_a_list(my_list)
print(my_list == my_reversed_list)
```
Using the definition of `reverse_a_list` that we did using `reverse`, the print statement would output `True` as `reverse` is modifying our original list. It would be better to instead use slicing to return a new list that is a reverse of the original.
```python
def reverse_a_list(a_list):
    return a_list[::-1]
```
Or if you're dead set on using `reverse` first make a copy of the list and then reverse the copy:
```python
def reverse_a_list(a_list):
    reversed_list = list(a_list)
    reversed_list.reverse()
    return reversed_list
```
Both of these methods do not **mutate** the original list.
