### ISSUE TITLE
Cannot pass the last test

### ISSUE THREAD

**Issue by YuchuanWeng** [rmotr-curriculum/base-python-curriculum-questions#428]
What is missing in my code that it cannot run to the last pair/item in the dictionary? All the first four items can be converted. Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/dictionary-keys-and-values

**User code**:
```python
def invert_dict(a_dict):
    pair = {}
    for k, v in a_dict.items():
        pair = {v:k}
    return pair

```

**Comment by jsymons** [comment]
You're completely replacing your `pair` dictionary each iteration of your for loop.
Instead of `pair = {v:k}` do `pair[v] = k` as this will just assign that key/value pair to the dictionary instead of creating a new one, which is what is happening with your current code.
