### ISSUE TITLE
Answer will not pass test cases though it appears accurate

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#43]
^

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-oop/make-a-car-that-can-drive

**User code**:
```python
# empty
class Car(object):
    def __init__(self, electric):
        self.electric = electric

    def drive(self):
        if self.electric:
            return 'WHIRRRRRRR'
    return 'VROOOOM'
```

**Comment by jsymons** [comment]
Not sure if this was just a formatting issue when posting the question, but your second return statement should be indented one more level do that it is *inside* your drive method

**Comment by AndyDeNike** [comment]
Thank you for your lesson in paying attention to detail!
