### ISSUE TITLE
"Nonetype" object not iterable 

### ISSUE THREAD

**Issue by msingh060** [rmotr-curriculum/base-python-curriculum-questions#431]
I'm getting this error and I believe it means that my variable 'body' can't be iterated over in my for loop but not sure why. I don't think it is because I've already sorted it when defining the variable - any ideas?

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/sort-lines-in-text-file

**User code**:
```python
def sort_lines(filepath, sorting='asc'):
    with open(filepath, 'r') as fp:
        body = fp.readlines().sort()
    if sorting == 'asc':
        body
    else:
        body.sort(reverse=True)
        
    with open(filepath, 'w') as f:
        for line in body:
            f.write(line)

```

**Comment by jsymons** [comment]
You're getting `Nonetype` issues because of this line:
```python
body = fp.readlines().sort()
```
`sort()` doesn't return anything, it modifies a list in place. Your line is setting `body` to what is returned by `sort()`. Since `sort()` doesn't return anything you are effectively doing `body = None`.
