### ISSUE TITLE
Why are we saying result = 1 instead of result = 0?

### ISSUE THREAD

**Issue by tlinc02** [rmotr-curriculum/base-python-curriculum-questions#433]
Why are we saying result = 1 instead of result = 0?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/powers-of-2

**User code**:
```python

```

**Comment by jsymons** [comment]
I'm assuming you're talking about the posted solution. If we set result to 0 then our final answer would be 0 as anything multiplied by 0 is 0.
