### ISSUE TITLE
Strings - what's wrong here

### ISSUE THREAD

**Issue by MoodyG** [rmotr-curriculum/base-python-curriculum-questions#434]
Not sure what I've done wrong here...

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/all-strings

**User code**:
```python
def all_strings(a, b, c):
    if type(a) == str and type(b) == str and type(c) == str:
        return True
    return FALSE
    


# Run Code test. You can remove this:

print(type('hello'))
print(type(True))
print(type(123))
```

**Comment by jsymons** [comment]
Python is case sensitive. `False` is not the same thing as `FALSE`. You should be using `False`.

**Comment by MoodyG** [comment]
ugh.  Noob move.
