### ISSUE TITLE
Notebook for this lesson

### ISSUE THREAD

**Issue by tlinc02** [rmotr-curriculum/base-python-curriculum-questions#435]
Hi, I was trying to download the Notebook for this lesson, in the hope of getting the product list so I could try these steps,  but it errors out with this message:
"Sorry, something went wrong.  Reload?"

Can you repost the notebook please?
Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/nested-collections

**Comment by santiagobasulto** [comment]
Thanks @jsymons.

@tlinc02 this is an usual issue of Github. Just hit reload a couple of times and it'll work:

![image](https://user-images.githubusercontent.com/872296/57385210-ffecb900-717f-11e9-88c7-8b505c37247b.png)
