### ISSUE TITLE
can't figure out how to end code when the dash would result at end of string (fail second test)

### ISSUE THREAD

**Issue by MoodyG** [rmotr-curriculum/base-python-curriculum-questions#438]
My code is working for test with large string, but when I have the smaller one and it ends with a '-', I'm not sure how to ensure that the "-" doesn't show up at the end, at least I think that's my problem....

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/insert-dashes-every-3-characters

**User code**:
```python
def insert_dashes(a_string):
    a_string = str(a_string)
    return '-'.join(a_string[i:i+3] for i in range(0, len(a_string), 3))
        
  
```

**Comment by jsymons** [comment]
You can call `.rstrip("-")` on the resultant string to strip any trailing dashes.

**Comment by MoodyG** [comment]
Hmm, I've tried to add that .rstrip("-") in a number of places but with my return being a bit lengthy I still can't seem to pass test 2.  Can you be more specific about where in my code that would go?

Thanks.
