### ISSUE TITLE
dashes every third character in string - follow up question

### ISSUE THREAD

**Issue by MoodyG** [rmotr-curriculum/base-python-curriculum-questions#439]
My previous question related to the code for this question is:

My code is working for test with large string, but when I have the smaller one and it ends with a '-', I'm not sure how to ensure that the "-" doesn't show up at the end, at least I think that's my problem....

Assignment: http://learn.rmotr.com/python/base-python-track/strings/insert-dashes-every-3-characters

User code:

def insert_dashes(a_string):
    a_string = str(a_string)
    return '-'.join(a_string[i:i+3] for i in range(0, len(a_string), 3))

You indicated that I should add a .rstrip("-") on the result, but I've tried quite a bit to do that and can't pass the second test.  Because my return statement is a bit lengthy I'm having an issue determining the right place for the .rstrip.  Can you clarify placement in this code?

Thanks.

**Comment by jsymons** [comment]
```python
return '-'.join(a_string[i:i+3] for i in range(0, len(a_string), 3)).rstrip("-")
```
