### ISSUE TITLE
I completed the Answer but still have a question (DON'T READ IF YOU DON'T WANT THE ANSWER)

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#44]
So I completed the problem just using the .count() function. When I checked the solutions that was marked as correct. I'm a bit surprised, I figured we'd have to use some combination of a for loop and in if statement or something.

Is that really the recommended solution? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/how-many-times

**User code**:
```python
def how_many_times(a_string, a_word):
    pass
```

**Comment by santiagobasulto** [comment]
😁 Well, I think that one is actually the proposed answer: https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-17-week-1-quiz/lesson-2-how-many-times/solutions/solution_.py
