### ISSUE TITLE
Failing next palindromic prime test

### ISSUE THREAD

**Issue by MoodyG** [rmotr-curriculum/base-python-curriculum-questions#440]
can you check my function for next palindromic prime?  I'm stuck on why I'm failing this test.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def reverse_str(s):
    # Please don't change me
    return s[::-1]


def is_prime(n):
    if n in (2,3):
        return True
    if n % 2 == 0:
        return False
    i = 3
    while i < n - 1:
        if n % i == 0:
            return False
        i += 2
    return True


def is_palindromic(n):
    return str(n) == reverse_str((str(n)))
            
def next_palindromic_prime(n):
        testnum = n + 1 
        while is_palindromic(testnum) !=True and is_prime(testnum) !=True:
            testnum += 1     
        return testnum         





```

**Comment by jsymons** [comment]
Your while loop condition needs to either use `or` instead of `and` or be rewritten as such: `while not(is_palindrome(testnum) and is_prime(testnum))`. The reason for this is with how you currently have it if either of those become `True` your and statement fails.
