### ISSUE TITLE
Not sure how to count each instances

### ISSUE THREAD

**Issue by tjperry07** [rmotr-curriculum/base-python-curriculum-questions#446]
I am able to count the number of times each word occurs in the phrase, but I am not able to figure out how to count it only one. I get Python 3 times, good once. So my count is always four. I'm not sure how to get 2 back.

```
import re
def all_in_string(a_string, s1, s2, s3):
    string_to_split = re.findall(r"\w+|[^\w\s]", a_string) #split the string, including punctuation
    print(string_to_split)
    
    # split_the_string = a_string.lower().split(' ')
    # print(split_the_string)
    final_count = ''
    for string in string_to_split:
        if string == s1 or string == s2 or string == s3:
            final_count += string + " "
        final_count.split(" ")
        # elif string == s2:
        #     final_count += s2
        # elif string == s3:
        #     final_count += s3
        # else:
        #     print("Done")
    return final_count


phrase = "Python is good. Python is Wise. I like Python"


all_in_string(phrase, 'Python', 'good', 'Ruby')  # 2
```

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/all-in-string

**User code**:
```python
def all_in_string(a_string, s1, s2, s3):
    pass
```

**Comment by jsymons** [comment]
I think you're way over complicating things here. All you need to do here is have a counter and if `s1` is `in` `a_string` increase the counter by 1, then do the same check for `s2`, and then again for `s3`, there's no need to involve using regular expressions.
