### ISSUE TITLE
My code works but want to know if the solution is better

### ISSUE THREAD

**Issue by YuchuanWeng** [rmotr-curriculum/base-python-curriculum-questions#447]
In the solution, there is the __init__ method to set scarf_color and buttons_color parameter and in the class method "create_cookies", the Cookie class default attributes are passed in the cls object. Could you explain a bit the pros and cons of the solution or my code below?
Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/cookie-factory-with-default-values

**User code**:
```python
class Cookie(object):
    DEFAULT_SCARF_COLOR = 'Green'
    DEFAULT_BUTTONS_COLOR = 'Blue'

    @classmethod
    def create_cookies(cls, number_of_object, scarf_color=None, buttons_color=None):
        list_of_cookies = []
        cls.scarf_color = scarf_color or cls.DEFAULT_SCARF_COLOR
        cls.buttons_color = buttons_color or cls.DEFAULT_BUTTONS_COLOR
        
        for i in range(number_of_object):
            list_of_cookies.append(cls())
            
        return list_of_cookies
```

**Comment by jsymons** [comment]
So the `create_cookies` method is acting as a factory that creates x number of cookies with specified parameters, however we can also always create a cookie just by doing `new_cookie = Cookie()`. The advantage of implementing the default values in the `__init__` is that when we do create cookies via `Cookie` it will *also* apply the default values, by only doing the handling of defaults in the  `create_cookies` method the default values will only be used when calling that method.
