### ISSUE TITLE
Trying to find a solution other than print()

### ISSUE THREAD

**Issue by IsaiahDB** [rmotr-curriculum/base-python-curriculum-questions#449]
I have only solved this problem by using print() in the function because "\n" moves the second and third parameters to the next line. But when I try to solve the problem using return, the output shows "\n" and all three parameters returns on the same line. How can I solve this problem without using print()?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/format-board

**User code**:
```python

```

**Comment by jsymons** [comment]
The \n is actually fine, however I suspect you don't have enough of them. Can you show is a copy of your code?
