### ISSUE TITLE
I don't know why this isn't working

### ISSUE THREAD

**Issue by mikepeiman** [rmotr-curriculum/base-python-curriculum-questions#45]
This seems like a very simple task, I'd really like to understand why this approach is not working:

def which_type(var):
    this_type = type(var)
    print(this_type)
    return this_type

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/return-the-type-of-value

**User code**:
```python

```

**Comment by jsymons** [comment]
If you look at the tests they are expecting you to return *a string*. You need to cast your return value as a string.

**Comment by jsymons** [comment]
You can convert something to a string (assuming the object supports the conversion) by doing `str(something)`

**Comment by mikepeiman** [comment]
Great, thanks for the response! It works, and it's elegant, hurrah!

```
def which_type(var):
    this_type = str(type(var))
    print(this_type)
    return this_type

which_type("abc")
which_type(42)
which_type(True)
```

**Comment by santiagobasulto** [comment]
@mikepeiman Can I close this one?
