### ISSUE TITLE
Extra n

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#450]
Hi, why do you need to include an extra "(n)" at the end of the lambda function for this to run?

**Assignment**: http://learn.rmotr.com/python/base-python-track/functional-programming/temperature-conversion-using-list-comprehensions

**User code**:
```python
def to_fahrenheit(a_list):
    return [(lambda n:((n*(9/5)) + 32))(n) for n in a_list]
```

**Comment by jsymons** [comment]
The `(n)` is what is calling the lambda. Think of it this way:
```python
my_lambda = lambda n: n*(9/5)
my_lambda(n)
```
Lambdas are like functions without the formal definition stuff, but you still need to *call* them to use them.
