### ISSUE TITLE
Not sure why this code isn't working

### ISSUE THREAD

**Issue by nicktlc** [rmotr-curriculum/base-python-curriculum-questions#453]
During assert, 

it seems like it still returns -1 for the values of a,b,c if the word isnt found in a_string?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/positions

**User code**:
```python
def positions(a_string, first_word, second_word, third_word):
    a = "-"
    b = "-"
    c = "-"
    if (a_string.find(first_word)!=1):
        a = str(a_string.find(first_word))
    if (a_string.find(second_word)!=1):
        b = str(a_string.find(second_word))
    if (a_string.find(third_word)!=1):
        c = str(a_string.find(third_word))
    return ("{},{},{}".format(a,b,c))
```

**Comment by jsymons** [comment]
Your if statements should be checking if the result of `find` is `!= -1` instead of `!= 1`. `find` returns `-1` if the substring isn't found.
