### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by lefthandkick** [rmotr-curriculum/base-python-curriculum-questions#454]
This works perfectly in vscode?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/format-board

**User code**:
```python
def format_tic_tac_toe_board(first_row, second_row, third_row):
    fr = list(first_row)
    sr = list(second_row)
    tr = list(third_row)
    
    full_board = """
    {0}  |  {1}  |  {2}
    --------------
    {3}  |  {4}  |  {5}
    --------------
    {6}  |  {7}  |  {8}
    """

    return full_board.format(fr[0], fr[1], fr[2], sr[0], sr[1], sr[2], tr[0], tr[1], tr[2])

```

**Comment by jsymons** [comment]
This is because your multi line string is indented. The catch with multi line strings is that **everything** between the `"""` becomes part of the string, including the whitespace.
