### ISSUE TITLE
Why do we need to iterate over line?

### ISSUE THREAD

**Issue by okurtphed** [rmotr-curriculum/base-python-curriculum-questions#455]
My understanding is data on my code is a list type and I need to iterate over per line to write. Is this correct? Just wondering if can we simply copy the content?

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/sort-lines-in-text-file

**User code**:
```python
def sort_lines(filepath, sorting='asc'):
    with open(filepath) as fp:
        data = fp.readlines()
        if sorting == 'desc':
            data.sort(reverse = True)
        else:
            data.sort()
            
    with open(filepath, 'w') as fp:
        fp.write(data)
```

**Comment by jsymons** [comment]
If you want to just do a single write you need to convert that list into a string. You can do this by doing `''.join(data)`, so your write would be `fp.write(''.join(data))` as this will join all the individual lines in your list into a single string.
