### ISSUE TITLE
Empty ipynb files

### ISSUE THREAD

**Issue by okurtphed** [rmotr-curriculum/base-python-curriculum-questions#457]
Notebook files are great for quick review but the ones under intro-to-databases/video_resources/  named "4 - SELECT Part 2.ipynb" and "5 - Insert, Delete, Update.ipynb" are empty. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/database-handling/python-and-sqlite

**Comment by santiagobasulto** [comment]
thanks for pointing it out Omer! I'll check what's going on.
