### ISSUE TITLE
How can I print my variables into the correct format?

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#46]
I've returned single variables in the other problems, but I'm not sure how to return multiple variables as a combined string.

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/positions

**User code**:
```python
def positions(a_string, first_word, second_word, third_word):
    first_word_counter = 0
    second_word_counter = 0
    third_word_counter = 0
    #solution = %, %, %
    for word in a_string:
        if a_string[first_word_counter:len(first_word) + first_word_counter] == first_word:
            return first_word_counter
        first_word_counter += 1
    for word in a_string:
        if a_string[second_word_counter:len(second_word) + second_word_counter] == second_word:
            return second_word_counter
        second_word_counter += 1 
    for word in a_string:
        if a_string[third_word_counter:len(third_word) + third_word_counter] == third_word:
            return third_word_counter
        third_word_counter += 1 
    if first_word_counter == len(a_string):
        first_word_counter = '-'
    if second_word_counter == len(a_string):
        second_word_counter = '-'
    if third_word_counter == len(a_string):
        third_word_counter = '-'
    return solution
    pass
               
phrase = "Python is good. Python is Wise. I like Python"

print(positions(phrase, 'Python', 'is', 'good'))

print('%,%,%'{'0','7', '-'})
```

**Comment by jsymons** [comment]
So you need to build a string that's appropriately formatted and return that. I would look at using `format`.
Also a side note, remember that when using `return` in loops and such that the first time your code encounters the return it will return and the rest of your code won't execute.

**Comment by branhoff** [comment]
Thanks for the advice Jsymons. I got rid of the returns until the end. I tried using the .format but I'm not sure I'm doin it right ( see below)

 solution = ("{},{},{}").format(first_word_counter, second_word_counter, third_word_counter)

I am getting the error "Unexpected error when parsing"

**Comment by jsymons** [comment]
Can you post your updated code so I can see if I can tell what's going on with it?

**Comment by branhoff** [comment]
How Do I do that? I tried to copy and past it, but it loses the formatting.

**Comment by jsymons** [comment]
https://guides.github.com/features/mastering-markdown/
Github comments are done in Markdown, see the above link for info on Markdown formatting

**Comment by branhoff** [comment]
[Positions-BH.txt](https://github.com/rmotr-curriculum/base-python-curriculum-questions/files/1803176/Positions-BH.txt)

I'll have to study this markdown later perhaps. I still am not seeing an easy way to just copy and paste my code like I can when I initially ask a question. Here' s a link to a text file.

**Comment by jsymons** [comment]
```python
def positions(a_string, first_word, second_word, third_word):
    first_word_counter = 0
    second_word_counter = 0
    third_word_counter = 0
    solution = ("{},{},{}").format(first_word_counter, second_word_count, third_word_counter)
```
You're referencing  `second_word_count` when you've called the variable `second_word_counter`
Also the format command should be run *after* you've found all the positions, as at this point all the counters are just `0`.
```python
    for word in a_string:
```
So you're iterating over the characters in the string but not doing anything with them.
I think this is serving to overcomplicate your code. I would suggest looking at the `find` string method (https://www.tutorialspoint.com/python/string_find.htm) as it will probably make your life easier over having to iterate and examine slices. Also, your if statement below is essentially doing 'if the word is here do nothing' which will result in your code eventually returning as if it didn't find anything.
```python
        if a_string[first_word_counter:len(first_word) + first_word_counter] == first_word:
            first_word_counter = first_word_counter
        first_word_counter += 1
    for word in a_string:
        if a_string[second_word_counter:len(second_word) + second_word_counter] == second_word:
            second_word_counter = second_word_counter
        second_word_counter += 1 
    for word in a_string:
        if a_string[third_word_counter:len(third_word) + third_word_counter] == third_word:
            third_word_counter = third_word_counter
        third_word_counter += 1 
    if first_word_counter == len(a_string):
        first_word_counter = '-'
    if second_word_counter == len(a_string):
        second_word_counter = '-'
    if third_word_counter == len(a_string):
        third_word_counter = '-'
    return solution
```
The pass here isn't required. Pass is just for empty functions/methods so they don't throw an error.
```python
    pass
               
phrase = "Python is good. Python is Wise. I like Python"

print(positions(phrase, 'Python', 'Wise', 'like') 
```

**Comment by branhoff** [comment]
Sincere thanks that helped a lot
