### ISSUE TITLE
why `return 1` does not work here

### ISSUE THREAD

**Issue by code-kopilka** [rmotr-curriculum/base-python-curriculum-questions#463]
Why return 1 here does not return just number 1?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/the-power-of-while-loops

**User code**:
```python
def feel_the_power(initial_number, power):
    count = 1
    
    while count < power:
        if power == 0:
            return 1
        else: 
            initial_number *= power
            count += 1
    
    return initial_number
    
result = feel_the_power(3, 0)
print(result)
```

**Comment by jsymons** [comment]
Your while loop never executes when `power` is 0 because since `count` is 1 the `while count < power` is never true since 1 is greater than 0. You should instead move your if statement outside of the while loop.
