### ISSUE TITLE
even positions

### ISSUE THREAD

**Issue by nanatetteh** [rmotr-curriculum/base-python-curriculum-questions#464]
revisiting this exercise. are even positions not considered to be 0,2,4,6...and so fort ? it seems the odd positions are returned in the solution instead of the even positions.

here is what i wrote
def chars_in_even_positions(a_string):
    result = ''
    for i in range(len(a_string)):
        if i % 2 == 0:
            result += a_string[i]
    return result
    
but it only works when i change the If statement to (if i != 0:) 
What am i missing?????

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/characters-in-even-positions

**User code**:
```python

```

**Comment by jsymons** [comment]
What you actually want is `if (i + 1) % 2 == 0:`. The thing to remember is that while we might jump to "even index means even position" this is not in fact the case. Index 0 is the 1st position, 1 is the second position, 2 is the third position, and so on.  We're asking for the elements in even positions, so the 2nd, 4th, 6th, etc. elements.
