### ISSUE TITLE
I dont see the required lesson for this exercise. 

### ISSUE THREAD

**Issue by chinnappa-raju** [rmotr-curriculum/base-python-curriculum-questions#465]
Is the requirement lesson for this exercised covered somewhere before we can attempt this exercise. I went through all the prep work, i dont see something relevant to check if the string contains a valid number 

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/valid-passwords

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
Checking this now @chinnappa-raju

**Comment by santiagobasulto** [comment]
@chinnappa-raju This lesson deals with 2 important topics: data types and operators. All the lessons from operators are valid ones. For example, arithmetic operators (`>`, `>=`, `<`, etc) and boolean operators (`or`, `and`, etc).
