### ISSUE TITLE
class object creation

### ISSUE THREAD

**Issue by nanatetteh** [rmotr-curriculum/base-python-curriculum-questions#467]
why does this fail ?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/cookie-factory

**User code**:
```python
# empty
class Cookie(object):
    
    @classmethod
    def create_cookies(cls, num):
        cookie = []
        for i in range(num):
            cookie[i]= Cookie()
        return cookie
        
        
```

**Comment by nanatetteh** [comment]
OK. I think I see my error. confusing the cookie list type with a dictionary type.

class Cookie(object):
    
    @classmethod
    def create_cookies(cls, num):
        cookie = []
        for i in range(num):
            instance = Cookie()
            cookie.append(instant)
        return cookie

this worked!

**Comment by nanatetteh** [comment]
correction:
* cookie.append(instance)

**Comment by jsymons** [comment]
This is correct, using `[index]` on a list only works for retrieving or replacing values, you can't add new items to the list that way as you'll get an `IndexError`. The proper way is to use `append` as you figured out.
