### ISSUE TITLE
Submit solution button not working

### ISSUE THREAD

**Issue by chinnappa-raju** [rmotr-curriculum/base-python-curriculum-questions#468]
I submitted the solution for this exercise few mins back, but still i see it is being submitted. I see the revolver going on and on. Refreshing didnt help either. I lost the code in fact but had it copied to paste it again

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python

```

**Comment by jsymons** [comment]
Is this issue still occurring or is the server working ok now?
