### ISSUE TITLE
Variations of assert

### ISSUE THREAD

**Issue by topher-allen** [rmotr-curriculum/base-python-curriculum-questions#469]
Can assert only be used to test numerical return values? Could it be used to compare strings/chars, etc?

**Assignment**: http://learn.rmotr.com/python/base-python-track/getting-started/reading-tests

**Comment by jsymons** [comment]
assert statements ultimately evaluate to a boolean (true/false). If true nothing happens, if false it raises an AssertionError (this is what causes test to fail)
