### ISSUE TITLE
Stacking text Outputs

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#47]
I'm able to output the first row successfully, but I'm not sure how to make the second and third rows print on top of each other. Is there any materials to reference that explain this concept?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/format-board

**User code**:
```python
# Example. Use it as a base to build your own template.
BOARD_TEMPLATE = """
O  |  O  |  X
--------------
X  |  X  |  O
--------------
O  |  X  |  O
"""


def format_tic_tac_toe_board(first_row, second_row, third_row):
    board_output =  ('{}  |  {}  |  {}').format(str(first_row[0]), str(first_row[1]), str(first_row[2]))
    return board_output
    pass

print(format_tic_tac_toe_board('OOX', 'XXO', 'XOX'))
    
```

**Comment by jsymons** [comment]
We present you with the `BOARD_TEMPLATE` for a reason. I would make a copy of that and edit it to work with `format`. Using a multi-line string means you don't have to worry about inserting newline characters and splicing it all together.
