### ISSUE TITLE
float vs decimal

### ISSUE THREAD

**Issue by topher-allen** [rmotr-curriculum/base-python-curriculum-questions#470]
I understand that there is a risk for precision errors when using floats, but what (if any?) are the best situations to use them instead of decimals? Also, do decimals automatically truncate to whatever number of significant figures is necessary? Eg: 3.0 + 1.0  = 4 (not 4.0?)

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-data-types/intro-to-data-types

**Comment by jsymons** [comment]
Floats tend to be faster than decimals, the precision comes at a cost, you don't always need that precision though.  Decimals do automatically truncate, however what you get isn't strictly `4` (as that would be an integer) but `Decimal(4)`. When using decimals you can't mix in floats, for example if I had:
```python
from decimal import Decimal
d1 = Decimal(3.0)
d2 = 1.0
d3 = d1 + d2
```
Python would throw an error, you can't add decimals and floats. You could add decimals and integers just fine, just not floats.
