### ISSUE TITLE
What is wrong here?

### ISSUE THREAD

**Issue by code-kopilka** [rmotr-curriculum/base-python-curriculum-questions#471]
I know of the solution where I could use .count() function but I want to try this option as well and can't understand why it is failing. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/how-many-times

**User code**:
```python
def how_many_times(a_string, a_word):
    counter = 0
    for each_word in a_string:
        if a_word == each_word:
            counter += 1
    
    return counter
```

**Comment by jsymons** [comment]
Iterating over a string doesn't give you individual words, it gives you individual characters. You'd want to try something more doing the lines of `for each_word in a_string.split()` but even this isn't going to be a perfect solution as it's just going to break up the string based on spaces, it's not going to take punctuation into account.
