### ISSUE TITLE
Doesn't pass the "Given Name and Animal Type" test, but passes the other three

### ISSUE THREAD

**Issue by joetynan** [rmotr-curriculum/base-python-curriculum-questions#475]
When I execute this code against this particular assertion, it returns an empty list. But I thought since the if statement is for it to return any dict that has both given_name AND animal_type, it should return only those list values that have both in them.  Why is it not returning the correct dict to the list, since it's the only value (Snake/DangerNoodle/Nope) that matches both keys?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-functions/multi-search

**User code**:
```python
def search_animals(animals, given_name = '', animal_type = ''):
    animal_list = []
    if given_name == '' and animal_type == '':
        animal_list = animals
    else:
        for count in range(0,len(animals)): 
            for Key,Value in animals[count].items():
                if animal_type in Value and given_name in Value:
                    animal_list.append(animals[count])
                #print(animals[count])
        #print(animal_list)
    return animal_list
```

**Comment by jsymons** [comment]
So your code isn't quite doing what you think it's doing. Nor is it doing what the assignment is requesting. 

What the assignment is requiring is that if they enter `given_name` that value has to be within the `given_name` of the animal. If they supply `animal_type` that value has to be within **either** the `animal_type` or `street_name` of the animal. If they supply both then what they supplied for `given_name` has to match `given_name` **and** what they supplied for `animal_type` has to match **either** `animal_type` and `street_name`.

What your code does is if they supply `given_name` that has to match **any** of `given_name`, `animal_type`, or `street_name` and in fact if it matches more than one of those the animal gets added once for each match. Same goes for if they provide `animal_type`, it only has to match one of **any** of the three fields. So for example, with the given data if somebody searched with a `given_name` of `"Chicken"` it would match `Penguin` even though it shouldn't as `Penguin`'s `given_name` is `"Mclovin"`. It gets even more complex when they pass in both search terms, then it will only match if **both** of the search terms are in **a single field**.

So I would suggest 1) don't use a nested for loop, 2) you need to rethink your conditions for adding an item to `animal_list`. If you need further help feel free to re-open this or join the mentor session or ask on Slack.

**Comment by joetynan** [comment]
oh, I see that now! And it's returning an empty list for this case because the if statement is looping through all the dictionary items and checking to see if both animal_type AND given_name match the key it's looking at. It "worked" with the other three tests because none of those tests supplied values for both animal_type and given_name.
