### ISSUE TITLE
Quotient Rule

### ISSUE THREAD

**Issue by snyderjamie** [rmotr-curriculum/base-python-curriculum-questions#477]
This might be that you just need to check each variable separately, but I am not sure why all the test but test with number doesn't work.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/all-strings

**User code**:
```python
def all_strings(a, b, c):
    if type(a and b and c) == str:
        return True
    else:
        return False
```

**Comment by jsymons** [comment]
You need to check each variable separately. By using `and` you're turning it into a boolean expression which is ultimately going to resolve as either `True` or `False` which means your `type` is always going to come back as a boolean.
