### ISSUE TITLE
what is wrong here?

### ISSUE THREAD

**Issue by code-kopilka** [rmotr-curriculum/base-python-curriculum-questions#478]
I have provided the while loop version of the solution, but can't understand why the 'for loop' of solving it is not working

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/subtract-reversed

**User code**:
```python
# def subtract_reversed(a_list):
#     if len(a_list) == 0:
#         return 0
    
#     result = a_list[-1]
#     index = 2
#     while index <= len(a_list):
#         elem = a_list[-1 * index]
#         result -= elem
#         index += 1
        
#     return result
    

def subtract_reversed(a_list):
    if len(a_list) == 0:
        return 0
        
    result = a_list[-1]
    for number in a_list:
        int_list = int(number)
        result -= int_list
        
    return result
```

**Comment by jsymons** [comment]
Your for loop solution is going to subtract the last element of the list. This is going to put your result of t. For example if your list was `[1,2,3,4,5]` your implementation works basically result in `5 - 1 - 2 - 3 - 4 - 5`
