### ISSUE TITLE
Differences in code solutions

### ISSUE THREAD

**Issue by topher-allen** [rmotr-curriculum/base-python-curriculum-questions#479]
Hi, I'm passing all of the tests, and my code makes intuitive sense to me, but I noticed that the solution seems like it took a pretty different approach. Is there any specific defect/disadvantage to my approach?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/largest-key

**User code**:
```python
def longest_key(a_dict):
    max = ""
    for key in a_dict:
        if len(key) > len(max):
            max = key
        return max
```

**Comment by jwinf843** [comment]
The solution has a bit of extra logic in it, but it seems like your solution works just as well. There will sometimes be cases where you can find a solution that is different, or even better than the solutions posted in the exercises themselves!
