### ISSUE TITLE
My code keeps running 

### ISSUE THREAD

**Issue by bryanalmeida525** [rmotr-curriculum/base-python-curriculum-questions#481]
I am trying to do a loop for the years to calculate but when it runs the assert It just seems to keep running and not letting me know if it's right. 

Am i running an infinite loop? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/population-growth

**User code**:
```python
def population_growth(initial_pop, annual_growth_rate, target_pop):
    years = 0
    pop_cal=initial_pop*(annual_growth_rate+1)
    
    if annual_growth_rate == 0: 
        return 'invalid growth rate'
    while pop_cal<=target_pop: 
        pop_cal=pop_cal*years
        years +=1
    return years 
```

**Comment by jsymons** [comment]
You are running an infinite loop. `years` is initialized to 0, and in your loop you set `pop_cal = pop_cal * years` which on the first iteration makes `pop_cal`  0. Then on all the subsequent loops anything multiplied by 0 is 0, therefore your while condition is never met.
