### ISSUE TITLE
Is there another approach?

### ISSUE THREAD

**Issue by danis-developments** [rmotr-curriculum/base-python-curriculum-questions#482]
I chose to use an inner list comprehension to generate a list of all of the terms each number in a_list could be divided by and then compare the length of that list to the length a_list_of_terms. I'm wondering if there's another approach here.

**Assignment**: http://learn.rmotr.com/python/base-python-track/functional-programming/divisible-numbers-comprehension-with-multiple-terms

**User code**:
```python
def divisible_numbers(a_list, a_list_of_terms):
    return [n for n in a_list if len(a_list_of_terms)==len([x for x in a_list_of_terms if n % x == 0])]
```

**Comment by santiagobasulto** [comment]
This is correct @dansdevelopments! It's a good example on the user's decision on "when something should be broken down into multiple parts". There's nothing to add to this one, I think it's perfect.

Anybody else has feedback?
