### ISSUE TITLE
Is there another approach to take here?

### ISSUE THREAD

**Issue by danis-developments** [rmotr-curriculum/base-python-curriculum-questions#483]
No problem, just wondering if there's an alternate way to tackle this.

**Assignment**: http://learn.rmotr.com/python/base-python-track/functional-programming/divisible-numbers-comprehension-with-multiple-terms

**User code**:
```python
def divisible_numbers(a_list, a_list_of_terms):
    return [n for n in a_list if len(a_list_of_terms)==len([term for term in a_list_of_terms if n % term == 0])]
```

**Comment by santiagobasulto** [comment]
The alternate way would be to check with a truth test, something like:

```python
[n for n in a_list if all([n % term for term in a_list_of_terms])]
```
This is not tested :P
