### ISSUE TITLE
Does given solution actually meet the requirements?

### ISSUE THREAD

**Issue by danis-developments** [rmotr-curriculum/base-python-curriculum-questions#484]
let's say that a_string = "Hello, Dave"
the test "if a_string in  line" would match the lines
"Hello, Dave"
"Hello, Dave..."
"I didn't expect to see you today. Hello, Dave."

wouldn't "if a_string == line.rstrip()" or "if a_string == line.rstrip('\n')" be better?

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/find-line-with-string

**User code**:
```python
def which_line(filepath, a_string):
    with open(filepath) as fp:
        read_data = fp.readlines()
        for line_num, line in enumerate(read_data):
            if a_string in line:
                return line_num + 1
        return None
```

**Comment by santiagobasulto** [comment]
@dansdevelopments the exercise doesn't specify where the `a_string` should be, so the `in` operator makes sense.

One small comment, you can set a `start` to enumerate, to make it start in 1 by default:

```python
for line_num, line in enumerate(read_data, 1):
    if a_string in line:
        return line_num
    return None
```

**Comment by jsymons** [comment]
Just to clarify further. The exercise does not state to find the line that is `a_string` but the line where `a_string` occurs, therefore it *should* match against all of those.
