### ISSUE TITLE
using cls() as an element

### ISSUE THREAD

**Issue by chinnappa-raju** [rmotr-curriculum/base-python-curriculum-questions#486]
What is the significance of using cls() as an element here in append?
We created an empty array Cookies and what we're trying to append here to this array?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/cookie-factory

**User code**:
```python
class Cookie(object):
    @classmethod
    def create_cookies(cls, number):
        cookies=[]
        for i in range(number):
            cookies.append(cls())
        return cookies
```

**Comment by jsymons** [comment]
So `create_cookies` is a **class method**, thus `cls` is going to point at our class (`Cookie`). So when we're doing `cookies.append(cls())` it's like doing `cookies.append(Cookie())`
