### ISSUE TITLE
Should  these attributes be hard coded?

### ISSUE THREAD

**Issue by chinnappa-raju** [rmotr-curriculum/base-python-curriculum-questions#488]
Attributes such as actor, brand, style are hard coded as dictionary elements or we receive a dictionary that is dynamic with any element?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/dict-to-object

**User code**:
```python

```

**Comment by jwinf843** [comment]
Don't hardcode them! Try to create them dynamically given the dictionary being passed in the test!
