### ISSUE TITLE
Order of if statements

### ISSUE THREAD

**Issue by snyderjamie** [rmotr-curriculum/base-python-curriculum-questions#489]
The block from 12-18 is identical to 22-28 except for the order of the if statements. The first block (12-18) will not pass the position test, however if I move the if symbol statement to the end of the block of code (22-28), all test pass. Why does the order of the if statements matter? Is there logic that I am missing here? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/exceptions/nice-moves

**User code**:
```python
# Define InvalidSymbolException here
class InvalidSymbolException(Exception):
    pass

# Define InvalidPositionException here
class InvalidPositionException(Exception):
    pass



### This code will not pass the position test ###
def validate_tic_tac_toe_move(symbol, position_x, position_y):
    if symbol != 'O' or symbol != 'X':
        raise InvalidSymbolException
    if position_x > 2:
        raise InvalidPositionException
    if position_y > 2:
        raise InvalidPositionException


### This code will pass all the tests ###
def validate_tic_tac_toe_move(symbol, position_x, position_y):
    if position_x > 2:
        raise InvalidPositionException
    if position_y > 2:
        raise InvalidPositionException
    if symbol != 'O' or symbol != 'X':
        raise InvalidSymbolException

```

**Comment by jsymons** [comment]
The root cause is actually your one if statement:
```python
    if symbol != 'O' or symbol != 'X':
        raise InvalidSymbolException
```
This is essentially going to raise an `InvalidSymbolException` whenever the if statement is encountered since `symbol` cannot be both `'O'` and `'X'`, which is what would be needed for the if to evaluate false. You should either use `and` instead of `or` here or you could instead do something like:
```python
if symbol not in ('X', 'O'):
```
