### ISSUE TITLE
What does it mean to return a 'set'?

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#49]
My code is written currently to return a new dictionary with the values, but the instructions say to return a set. I know there is an intro to sets after these exercises. Am I supposed to have watched that first?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/search-keys-for-value

**User code**:
```python
def search_keys_for_value(a_dictionary, search_term):
    d = {}
    for keys, values in a_dictionary.items():
        if values == search_term:
            d[keys] = values
    return d
    pass

a_dict = {
        "name": "billy",
        "age": 12,
        "fav_num": 12
    
}

print(search_keys_for_value(a_dict, 12))
```

**Comment by santiagobasulto** [comment]
Hey Brandon! Seems like @jsymons found the issue with the ordering lesson too here: https://github.com/rmotr-curriculum/base-python-curriculum/issues/18

We'll check and let you know, thanks for the heads up.

**Comment by santiagobasulto** [comment]
@branhoff you were right. The assignment was in the correct place, it should have been after the sets lesson. Thanks again
