### ISSUE TITLE
My code is marked as completed but it is not showing as completed on the Dashboard.

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#50]
My code is marked as completed but it is not showing as completed on the Dashboard.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/search-keys-for-value

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
@branhoff thanks for reporting it, I'll take a look into it.

**Comment by santiagobasulto** [comment]
@branhoff just found the issue, we'll fix soon. Thanks again for reporting.

**Comment by santiagobasulto** [comment]
@branhoff resolved!
