### ISSUE TITLE
Splitting string does not take into account punctuation

### ISSUE THREAD

**Issue by mikepeiman** [rmotr-curriculum/base-python-curriculum-questions#52]
I used pythontutor.com to understand why this was not working. It is indeed operating correctly, except that the string did not split "good" it split out "good." with the period. How should I take this into account?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/all-in-string

**User code**:
```python
def all_in_string(a_string, s1, s2, s3):
    split_string = a_string.split()
    keyword_list = [s1,s2,s3]
    print(keyword_list)
    counter = 0
    for word in keyword_list:
        if word in split_string:
            counter += 1
            print(word)
            print(counter)
    return counter

print(all_in_string("Python is good. Python is Wise. I like Python",'Python', 'good', 'Ruby'))
```

**Comment by jsymons** [comment]
You should look at using `strip` to remove unwanted characters from the start and end of the string. https://www.tutorialspoint.com/python/string_strip.htm

**Comment by mikepeiman** [comment]
Even better, simpler - I didn't need .split() at all. New code:

def all_in_string(a_string, s1, s2, s3):
    keyword_list = [s1,s2,s3]
    print(keyword_list)
    counter = 0
    for el in keyword_list:
        if el in a_string:
            counter += 1
            print(el)
            print(counter)
    return counter

print(all_in_string("Python is good. Python is Wise. I like Python",'Python', 'good', 'Ruby'))

**Comment by jsymons** [comment]
Yes, the only caveat to that is that `in` will perform a *substring match* on a string. It doesn't matter for this assignment but matters when you're trying to match exact words. For example `if 'he' in 'They are a hero.':` would be true.
