### ISSUE TITLE
Tests failing but I'm not sure why

### ISSUE THREAD

**Issue by mikepeiman** [rmotr-curriculum/base-python-curriculum-questions#53]
Two issues: when I use the row data from either test, I seem to get matching output, yet the test still fails. Secondly, when I leave the variables as empty strings, my code errors. What to do?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/format-board

**User code**:
```python
# Example. Use it as a base to build your own template.
BOARD_TEMPLATE = """
O  |  O  |  X
--------------
X  |  X  |  O
--------------
O  |  X  |  O
"""
first_row = 'XO-'
second_row = 'O--'
third_row = 'O-X'

def format_tic_tac_toe_board(first_row, second_row, third_row):
    rows = [first_row, second_row, third_row]
    formatted_rows = ""
    for row in rows:
        if row != rows[-1]:
            formatted_row = ('{}  |  {}  |  {}'.format(row[0], row[1], row[2]))
            formatted_row += '\n--------------\n'
        else:
            formatted_row = ('{}  |  {}  |  {}'.format(row[0], row[1], row[2]))
            
        formatted_rows += formatted_row
    return formatted_rows

board = format_tic_tac_toe_board(first_row, second_row, third_row)

print(board)
```

**Comment by mikepeiman** [comment]
Based on my weak understanding of the failing test response, I'm guessing that this might need to be expressed as a multiline string, rather than using newline characters. Am I on the right track?

**Comment by jsymons** [comment]
It can be done with newlines or multiline. Multiline might be a little easier. I think the issue you're having here looks like you're missing the trailing newline character. It's something people frequently get caught up on. If you look at the multiline that we're testing against the triple quotes are on a new line after the board, this means the multiline captures that newline character.

**Comment by mikepeiman** [comment]
I didn't follow that Jason. What specifically should I change in my code? Note that this code does output the tic-tac-toe grid properly.

**Comment by jsymons** [comment]
Ok, couldn't explain it as well earlier as I was on mobile...
Here's how a multiline string essentially works:
```python
my_string = """
Line 1
Line 2
Line 3
"""
```
If I were to write that as a normal string it would be:
```python
my_string = "\nLine 1\nLine 2\nLine 3\n"
```
Every time you would have to hit enter between the `"""` python will convert it to a newline character.
So let's look at what we're testing against:
```python
expected_board = """
X  |  O  |  X
--------------
O  |  X  |  O
--------------
O  |  O  |  X
"""
```
Now let's see where the newlines are in it:
```python
expected_board = """ # new line
X  |  O  |  X # new line
-------------- # new line
O  |  X  |  O # new line
-------------- # new line
O  |  O  |  X # new line
"""
```
Your code isn't taking into account the newline at the start of the string (right after the `"""`) or the one at the end of the string (at the end of the board output)
If we were to convert your output into a multiline string it would look like this:
```python
formatted_rows = """X  |  O  |  X
--------------
O  |  X  |  O
--------------
O  |  O  |  X"""
```
I hope that clears things up a bit.

**Comment by mikepeiman** [comment]
Boom, more than makes sense, added those newlines and it passed immediately. Thanks! That difference was not visually obvious to me, I guess it comes with familiarity with code.
