### ISSUE TITLE
Code is looping in list building letter by letter string

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#54]
Where exactly has my logic gone wrong in my for loop? It's at least correct in that it's only pulling in keys with values greater than 1, but it's splicing those values into their individual letters.

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/analyze-string

**User code**:
```python
def count_words(a_string):
    l = a_string.split()
    word_count_dict = {}
    for word in l:
        word_count_dict[word] = l.count(word)
    return word_count_dict
    pass


def get_list_of_duplicates(word_count_dict):
    l = []
    count = 2
    for key in word_count_dict:
        temp = word_count_dict.get(key)
        if temp == count:
            l += key
        else:
            count += 1
    return l 
        
    pass

print(count_words("""Happy Python Programming Programming Programming Happy Me"""))

print(get_list_of_duplicates(count_words("""Happy Python Programming Programming Programming Happy Me""")))
```

**Comment by jsymons** [comment]
You should be using `l.append(key)` instead of `l += key`. Using `l += key` is the same as doing `l.extend(key)`, in which case it treats `key` as an iterable and adds all the values in the iterable to `l`, which is why you're getting individual characters instead of words.
