### ISSUE TITLE
Provide resources for videos

### ISSUE THREAD

**Issue by mikepeiman** [rmotr-curriculum/base-python-curriculum-questions#55]
It would be great to provide links to all the examples used in the videos, so students have the option of walking through and experimenting themselves if they want. I learn better when I can get my hands on the same thing that's being demonstrated. Even though it's dead-simple, just to provide a link to that Jupyter notebook for example. I have a hard time learning by simply sitting and listening.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/intro-to-dictionaries

**Comment by santiagobasulto** [comment]
👍 Adding them at the moment. Thanks Mike!

**Comment by sosagago** [comment]
Where exactly can I find this jupyter notebook?
