### ISSUE TITLE
Poor semantics

### ISSUE THREAD

**Issue by mikepeiman** [rmotr-curriculum/base-python-curriculum-questions#57]
The lesson name and function name "common_values" suggests values which would be common to both sets, which is an issue of intersection, not union. 

It feels like this is meant to be "tricky", but I would suggest to make the meaning as clear as possible as we (students) are trying to clearly understanding new terms, symbols and operations here. Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/common-values

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
Hello Mike, it's actually a union operation. For example, in the first test:

```python
common_values((4, 5, 6, 7), (1, 2, 3)) == {1, 2, 3, 4, 5, 6, 7}
```

`1` is only in the second tuple, but it's still there. Maybe we can improve the readme? What do you think @jasonmeeks?

**Comment by santiagobasulto** [comment]
Just to clarify: https://repl.it/@santiagobasulto/NextJitteryTab

**Comment by santiagobasulto** [comment]
@jasonmeeks Can you confirm?

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
