### ISSUE TITLE
unhashable type 'dict'

### ISSUE THREAD

**Issue by mikepeiman** [rmotr-curriculum/base-python-curriculum-questions#58]
My dictionary works nicely without the initial test, but I need to handle the non-int type scenario, and I'm getting that error. Hints?

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/sum-of-dict-values

**User code**:
```python
'''
submitting failing solution to keep track of my learning process. I've solved it,
but I like the process I used with print statements to figure this out
'''

d1 = {
    'a': 10,
    'b': 30,
    'c': 5
}

d2 = {
    'a': 7,
    'b': 22,
    'c': 90
}

d3 = {
    'a': 5,
    'b': 1,
    'c': 'hello'
}

def sum_of_dict_values(d1, d2, d3):
    sum_a = 0
    sum_b = 0
    sum_c = 0
    sum_dict = {}
    for term in d1, d2, d3:
        if type(term) != int:
            sum_dict.update({term: None})
        if isinstance(term['a'], int):
            sum_a += term['a']
            sum_dict.update({'a': sum_a})
        if isinstance(term['b'], int):
            sum_b += term['b']
            sum_dict.update({'b': sum_b})
        if isinstance(term['c'], int):
            sum_c += term['c']
            sum_dict.update({'c': sum_c})
    return sum_dict

print(sum_of_dict_values(d1,d2,d3))


        
```

**Comment by jsymons** [comment]
So you're first if statement is always going to trigger, as `d1`, `d2`, and `d3` are dictionaries and not int. What I would do instead of using that if statement is instead add an else to your other if's, that will trigger if the particular if statement doesn't (ie. a value is not an int)
Example:
```python
if isinstance(term['a'], int):
    sum_a += term['a']
else:
    sum_a = None
 sum_dict.update({'a': sum_a})
```
The only thing is then you would also need to check if the sum is already None, ie:
```
if isinstance(term['a'], int) and sum_a is not None:
```

You may instead want to look over iterating over the keys instead of the dictionaries, it may lend itself to a cleaner solution.

**Comment by code-kopilka** [comment]
why do we need to iterate over the keys instead of values? The task says "If there is a non-integer as a *value*, set the value to None for that key", we need to make sure the value is non-integer, not the key.

**Comment by jsymons** [comment]
The keys will be identical across all dictionaries, so therefore for example you can do the following:
```python
results ={}

for key in d1:
    if type(d1[key]) == int and type(d2[key]) == int and type(d3[key]) == int:
        results[key] = d1[key] + d2[key] + d3[key]
    else:
        results[key] = None
return results
