### ISSUE TITLE
Access to Jupyter Notebooks

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#59]
Is there somewhere I can access your Jupyter Notebooks for these lecture tutorials?  Thanks.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/application-json-files

**Comment by santiagobasulto** [comment]
Yes Andrew! I've updated the lesson with the link, but it's also here: https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-10-collections-part-3/lesson-4-application-json-files/JSON%20Example.ipynb

**Comment by mikepeiman** [comment]
Thanks for adding the links! It's really nice & useful to be able to follow along and play with the code.
