### ISSUE TITLE
I've come to the string_printing_methods lesson

### ISSUE THREAD

**Issue by databaseadmins** [rmotr-curriculum/base-python-curriculum-questions#6]
I've come to this lesson but there is no text or video.  Should there be?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-data-types/string-printing-methods

**Comment by santiagobasulto** [comment]
Hello @databaseadmins 👋 ! That lesson shouldn't be enabled yet. Thanks for pointing it out.

**Comment by useraddmario** [comment]
Should this still be disabled?  We have class in a couple days and I thought we needed to do this before class.
