### ISSUE TITLE
Materials?

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#60]
Are the documentation mentioned in this lesson posted somewhere?

**Assignment**: http://learn.rmotr.com/python/base-python-track/modules-and-packages/most-common-stdlib-modules

**Comment by santiagobasulto** [comment]
Yes, right here: https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-13-modules-and-packages/lesson-3-most-common-stdlib-modules/Python%20stdlib%20Modules.ipynb

I also updated the lesson in learn.rmotr.com. Thanks 👍!
