### ISSUE TITLE
Seems to produce an extra iteration of argument

### ISSUE THREAD

**Issue by mikepeiman** [rmotr-curriculum/base-python-curriculum-questions#61]
I'm not understanding why this code seems to produce an extra level of iteration; the print statements seems to reflect the correct depth of loop.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/identity-matrix

**User code**:
```python
def identity_matrix(size):
    matrix = []
    matrix_row = []
    for row in range(1,size+1):
        print("outer loop row - " + str(row))
        for i in range(1, size+1):
            print("    inner loop char - " + str(i))
            matrix_row.append(i)
    #     matrix_row[:row] = "1"
        matrix.append(matrix_row)
    return matrix


print(identity_matrix(5))
```

**Comment by santiagobasulto** [comment]
Hey Mike, I think you should define `matrix_row` inside the first for loop, so it's reset with every row.

**Comment by mikepeiman** [comment]
You solved it, thanks!
