### ISSUE TITLE
Why doesnt 'import datetime' include 'date' and proudce NameError?

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#62]
In this case wouldnt 'import datetime' include all modules within 'datetime' including 'date'? 

**Assignment**: http://learn.rmotr.com/python/base-python-track/modules-and-packages/celebrate-if-friday

**User code**:
```python
# Import the library here!
import datetime

def celebrate_if_friday(date):
    if date.strftime('%A') == 'Friday':
        return "YES!"
    return "Aww"
```

**Comment by jsymons** [comment]
It does, but within the `datetime` namespace. You need to refer to `date` as `datetime.date`. If you want to refer to it only by `date` you would need to do `from datetime import date`

**Comment by AndyDeNike** [comment]
so within the confines of the test, which has a 'date()' parameter, is there anyway to refer to it as datetime.date ?

**Comment by jsymons** [comment]
You can't alter the tests, which means as I said, if you want to access date without it being in the datetime namespace you need to use `from datetime import date` the other alternative is to use `from datetime import *` which would import *everything* from `datetime` into the current namespace. The former is the preferred method.

**Comment by AndyDeNike** [comment]
thanks, well put!
