### ISSUE TITLE
Easier Method

### ISSUE THREAD

**Issue by f-mac** [rmotr-curriculum/base-python-curriculum-questions#66]
Wouldn't it be easier to use this code?

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/no-uppercase-allowed

**User code**:
```python
def neutralize_uppercase(stringy):
    if stringy == stringy.lower():
        return stringy
    else:
        return ''
```

**Comment by jsymons** [comment]
Yes, however part of the purpose of this exercise is to get more loop practice.

**Comment by santiagobasulto** [comment]
+1 to @jsymons comment. @f-mac your solution works and I'd even say it's the preferred one. But the idea is to manually check it with a for loop to practice them. Can I close this one?

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
