### ISSUE TITLE
Just offering a couple of different solutions, one is list comprehension

### ISSUE THREAD

**Issue by mikepeiman** [rmotr-curriculum/base-python-curriculum-questions#67]
Just wanted to share these two solutions as they differ from given solution, and it was a challenge to work out the second one with list comp and lambda! :D

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/get-filename-with-max-lines

**User code**:
```python

'''
v1.0

def max_lines(*file_names):
    files_dict = {}
    for file_name in file_names:
        file_open = open(file_name, 'r')
        file_length = len(file_open.readlines())
        files_dict[file_name] = file_length
    return max(files_dict)
'''
'''
v2.0
def max_lines(*file_names):
    for fn in file_names:
        file_dict = dict([(fn, lambda file_length: len(open(fn), file_names)) for fn in file_names])
    return max(file_dict)
'''
```

**Comment by AndyDeNike** [comment]
@mikepeiman , would you be able to put into words, how the sequence of v2.0 functions ?  Very clean solution, no rush on explanation but this is so concise.  I'm a little unsure how specifically the line 'file_dict = dict([(fn, lambda file_length: len(open(fn), file_names)) for fn in file_names])' works.

As a side quesiton: *file_names (*args) is a tuple full of the individual files names/file types, as strings?  Just making sure

**Comment by danis-developments** [comment]
I considered doing a list comprehension similar to this, but decided not to as it didn't allow me to use the with context block. Am I wrong to be concerned about opening these files without closing them inside of a list comprehension?

**Comment by danis-developments** [comment]
I wrote this solution as an example of using a list comprehension with a "with" block for safety and a guard clause for efficiency in the case we only get one file. any suggestions or  comments would be great!


```python
def max_lines(*file_names):
    if len(file_names) == 1:
        return file_names[0]
        
    def num_file_lines(file_name):
        with open(file_name) as fp:
            return len(fp.readlines())
    
    line_counts = list([num_file_lines(file) for file in file_names])
    return file_names[line_counts.index(max(line_counts))]
```
