### ISSUE TITLE
"PRINT "

### ISSUE THREAD

**Issue by VisionMaker** [rmotr-curriculum/base-python-curriculum-questions#68]
Why do we use PRINT  if I can just ask for the value of Z right away ?

**Assignment**: http://learn.rmotr.com/python/base-python-track/getting-started/variables-and-assignments

**Comment by santiagobasulto** [comment]
What do you mean @VisionMaker? We usually use `print` to provide output in different environments.

**Comment by jsymons** [comment]
To expand upon what Santiago said, we usually aren't running our code in an interactive terminal, so the only way we can see information from our program is to output it in one way or another. `print` is one way to do this.

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
