### ISSUE TITLE
"Def"function and Return

### ISSUE THREAD

**Issue by VisionMaker** [rmotr-curriculum/base-python-curriculum-questions#69]
Why def ?  (Could you describe it for me ?)
In human language what would be Return ?

**Assignment**: http://learn.rmotr.com/python/base-python-track/getting-started/reading-tests

**Comment by santiagobasulto** [comment]
`def` is the keyword used to write a function. When Python reads `def`, it knows that you're starting to _define_ a function. `return` is the "returned" value created by that function, is the ultimate goal of the function. For example: "write a function that takes a list of sales, and **returns the growth vs previous year**". The outcome, the result of that function is what's returned from that function.

Makes sense?

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
