### ISSUE TITLE
1 success 3 fail

### ISSUE THREAD

**Issue by databaseadmins** [rmotr-curriculum/base-python-curriculum-questions#7]
I don't have any clue why -- 

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/valid-passwords

**User code**:
```python
# #### Don't change these passwords #### #
password_1 = 'Jhx85a'
password_2 = 'ajd2819adkBjld'
password_3 = '81$br&j#'
password_4 = 'kp03%$Ji19Br!rdV'
# #### Don't change these passwords #### #

# == Your Code Below == ##

## Is Long Enough
# Has at least 12 chars
is_long_enough_pwd_1 = len(password_1) >= 12  # False
is_long_enough_pwd_2 = len(password_2) >= 12
is_long_enough_pwd_3 = len(password_3) >= 12
is_long_enough_pwd_4 = len(password_4) >= 12

## Has at least one of the following numbers: 0, 1, 2, 3
has_one_number_pwd_1 = password_1 in [0, 1, 2, 3]
has_one_number_pwd_2 = password_2 in [0, 1, 2, 3]
has_one_number_pwd_3 = password_3 in [0, 1, 2, 3]
has_one_number_pwd_4 = password_4 in [0, 1, 2, 3]

## Has at least one of these characters, v, V, r, R, b, B.
has_required_character_pwd_1 = password_1 in ['v', 'V', 'r', 'R', 'b', 'B']
has_required_character_pwd_2 = password_2 in ['v', 'V', 'r', 'R', 'b', 'B']
has_required_character_pwd_3 = password_3 in ['v', 'V', 'r', 'R', 'b', 'B']
has_required_character_pwd_4 = password_4 in ['v', 'V', 'r', 'R', 'b', 'B']

## Has at least one symbol: $%#&
at_least_one_symbol_pwd_1 = password_1 in ['$', '%', '#', '&']
at_least_one_symbol_pwd_2 = password_2 in ['$', '%', '#', '&']
at_least_one_symbol_pwd_3 = password_3 in ['$', '%', '#', '&']
at_least_one_symbol_pwd_4 = password_4 in ['$', '%', '#', '&']
```

**Comment by santiagobasulto** [comment]
Hello @databaseadmins! You're "inverting" the order of the checks. Given the password `pwd = 'kp03%$Ji19Br!rdV'` you want to check **if `$` is in that given password `pwd` or if `%` is in `pwd`. So, it's going to be something like:

```python
pwd = 'kp03%$Ji19Br!rdV'
has_symbol = '$' in pwd or '%' in pwd
```
Makes sense?

**Comment by santiagobasulto** [comment]
Btw, try running individual tests:

![image](https://user-images.githubusercontent.com/872296/35674559-c3a6833a-0723-11e8-90dd-34069f701113.png)

**Comment by databaseadmins** [comment]
When I add this to my code editor and "run it" I'm getting failures.   When I run it independently in idle it's fine   
********Code editor fails****************************
is_long_enough_pwd_1 = len(password_1) >= 12  # False
is_long_enough_pwd_2 = len(password_1) >= 12
is_long_enough_pwd_3 = len(password_1) >= 12
is_long_enough_pwd_4 = len(password_1) >= 12

## Has at least one of the following numbers: 0, 1, 2, 3
has_one_number_pwd_1 = '0' in password_1 or '1' in password_1 or '2' in password_1 or '3' in password_1
has_one_number_pwd_2 = '0' in password_2 or '1' in password_2 or '2' in password_2 or '3' in password_2
has_one_number_pwd_3 = '0' in password_3 or '1' in password_3 or '2' in password_3 or '3' in password_3
has_one_number_pwd_4 = '0' in password_4 or '1' in password_4 or '2' in password_4 or '3' in password_4

## Has at least one of these characters, v, V, r, R, b, B.
has_required_character_pwd_1 = ?
has_required_character_pwd_2 = ?
has_required_character_pwd_3 = ?
has_required_character_pwd_4 = ?

## Has at least one symbol: $%#&
at_least_one_symbol_pwd_1 = ?
at_least_one_symbol_pwd_2 = ?
at_least_one_symbol_pwd_3 = ?
at_least_one_symbol_pwd_4 = ?


************pycharm success**********************************************************
has_one_number_pwd_1 = '0' in password_1 or '1' in password_1 or '2' in password_1 or '3' in password_1
has_one_number_pwd_2 = '0' in password_2 or '1' in password_2 or '2' in password_2 or '3' in password_2
has_one_number_pwd_3 = '0' in password_3 or '1' in password_3 or '2' in password_3 or '3' in password_3
has_one_number_pwd_4 = '0' in password_4 or '1' in password_4 or '2' in password_4 or '3' in password_4


def test_at_least_one_number(foo):
    assert has_one_number_pwd_1 is False
    assert has_one_number_pwd_2 is True
    assert has_one_number_pwd_3 is True
    assert has_one_number_pwd_4 is True


test_at_least_one_number(has_one_number_pwd_1)  #and the three others

**Comment by santiagobasulto** [comment]
Are you also including the `?` below? Those will prevent Python from even "compiling" your code.

**Comment by databaseadmins** [comment]
yeah i don't do those -- that would require too much work to type those out only to discover they're wrong.

**Comment by santiagobasulto** [comment]
I'm using your code and it works:

![image](https://user-images.githubusercontent.com/872296/35683923-275d834a-0744-11e8-880d-1d4dd98b6b49.png)

Want to do a quick Hangout? Ping me on Slack.

**Comment by santiagobasulto** [comment]
@databaseadmins have you solved this one? Should I close it?

**Comment by santiagobasulto** [comment]
@databaseadmins closing this for now, reopen if you still find the issues.

**Comment by bluelou** [comment]
Hint:
pass_num = [0, 1, 2, 3]
## Has at least one of the following numbers: 0, 1, 2, 3
has_one_number_pwd_1 = password_1 in pass_num
