### ISSUE TITLE
Assert

### ISSUE THREAD

**Issue by VisionMaker** [rmotr-curriculum/base-python-curriculum-questions#70]
Could you give some expla.. about the assert ?

**Assignment**: http://learn.rmotr.com/python/base-python-track/getting-started/reading-tests

**Comment by jsymons** [comment]
I'm simplest terms the `assert` statement checks if rest of the line evaluates to either `True` or `False`, if it evaluates to `True` the test passes, if it evaluates to `False` the test fails.

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
