### ISSUE TITLE
brace (curly bracket)

### ISSUE THREAD

**Issue by VisionMaker** [rmotr-curriculum/base-python-curriculum-questions#71]
Why having the curly brackets for the line 4 ? I thought that it was for dictionnaries. :)

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-data-types/string-length

**User code**:
```python
language = "Python"
name = "Guido Van Rossum"

string_template = "{name} is the creator of {language}"
text = string_template.format(name=name, language=language)

length_of_language = ?
length_of_name = ?
length_of_text = ?
```

**Comment by jsymons** [comment]
In this case the curly braces are **within a string**. This is a special way of templating a string for use with the `format` method that allows us to replace the curly braces with something else.

Example:
```python
template = "Hello {name}!"
hello_world = template.format(name="world")
hello_bob = template.format(name="Bob")
```
This would result in `hello_world"` being `"Hello world!"` and `hello_bob` being `"Hello Bob!"`

The takeaway here is that standard code syntax is ignored when it's contained within a string.

Hope that clears things up.

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.

**Comment by sqrus** [comment]
Was this a code challenge, because i do not see this from training program.
