### ISSUE TITLE
format meaning

### ISSUE THREAD

**Issue by VisionMaker** [rmotr-curriculum/base-python-curriculum-questions#72]
tring_template = "{name} is the creator of {language}"
text = string_template.format(name=name, language=language)
Why is it that we use format ? and defining name=name and language=language ?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-data-types/string-length

**User code**:
```python
language = "Python"
name = "Guido Van Rossum"

string_template = "{name} is the creator of {language}"
text = string_template.format(name=name, language=language)

print len ("language) 
print len ("name") 
print len ("text")
```

**Comment by jsymons** [comment]
If you look at the response to your previous question (https://github.com/rmotr-curriculum/base-python-curriculum-questions/issues/71) I go into how `format` works. If you need me to go into further detail let me know.

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
