### ISSUE TITLE
4>=3 , True ?

### ISSUE THREAD

**Issue by VisionMaker** [rmotr-curriculum/base-python-curriculum-questions#73]
Hi why is this bool True if 4 is not equal to 3 ? ( even tough it is sup to 3) - is it because these signs >= mean either one or the other can be True so the whole is True ?

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/comparison-operators

**Comment by jsymons** [comment]
`x >= y` will evaluate to `True` if `x` is greater than or equal to `y`

**Comment by santiagobasulto** [comment]
Yeah, we talked about this one. Closing it.
