### ISSUE TITLE
Increment

### ISSUE THREAD

**Issue by VisionMaker** [rmotr-curriculum/base-python-curriculum-questions#74]
What is exactly INCREMENT ? would it be to add something or else ?

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/assignment-operators

**Comment by jsymons** [comment]
Incrementing example:
```python
x = 0
x += 1
```
This *increments* `x` by 1. `x += 1` is shorthand for writing `x = x + 1`

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
