### ISSUE TITLE
two print (s) ? (Case with '$')

### ISSUE THREAD

**Issue by VisionMaker** [rmotr-curriculum/base-python-curriculum-questions#75]
I saw that there is two prints one after the other - running it in Python it doesn't work for my code
could you give me some clues about it ?

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/other-boolean-operators

**Comment by jsymons** [comment]
We would need to see your code to give you an idea as to what might be going on.

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
