### ISSUE TITLE
average

### ISSUE THREAD

**Issue by VisionMaker** [rmotr-curriculum/base-python-curriculum-questions#76]
When I run the code on my computer it woks. Might be the link with the source code ?

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/write-an-equation

**User code**:
```python
# Write the equation to calculate this average in one line
(3+5+7)/2

```

**Comment by jsymons** [comment]
Resolved this issue via Slack, please close.

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
