### ISSUE TITLE
Why is it not working ?

### ISSUE THREAD

**Issue by VisionMaker** [rmotr-curriculum/base-python-curriculum-questions#79]
# Complete the following operations
print('pro' in 'programming') 

print('w' in 'bridge')
 this should be working and give me good results isn't it  ?

thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/in-or-out

**User code**:
```python
# Complete the following operations
print('pro' in 'programming') 

print('w' in 'bridge')
```

**Comment by jsymons** [comment]
You're `print`ing instead of assigning values to variables.

**Comment by santiagobasulto** [comment]
yep, just as a reference, it should be `pro_in_programming = 'pro' in 'programming'`
