### ISSUE TITLE
I'm not clear on what you're asking us to do.

### ISSUE THREAD

**Issue by databaseadmins** [rmotr-curriculum/base-python-curriculum-questions#8]
This doesn't make sense to me.   

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/inverting-booleans

**User code**:
```python
burger = False

# Flip this burger using not
burger_flipped = not(burger)


number = 5

# Create an inequality checking if number is greater than 3, then invert the result (all on one line)!
result = 
```

**Comment by santiagobasulto** [comment]
Maybe we can improve the description here a little bit. `burger_flipped` should be just `not burger`. Result should be `not (result > 3)`.

What do you say @jasonmeeks?

**Comment by databaseadmins** [comment]
It was the result > 3 that wsn't making sense -- couldn't grasp what you're asking for -- I see it but still couldn't ask it myself as a question.

**Comment by santiagobasulto** [comment]
Yes, definitively, we'll probably fix it or rephrase it. Thanks Burt!

**Comment by code-kopilka** [comment]
the question has not yet been rephrased :)
