### ISSUE TITLE
I want to review the assertion lesson

### ISSUE THREAD

**Issue by databaseadmins** [rmotr-curriculum/base-python-curriculum-questions#80]
I want to go back over the lesson on how to use the assert for testing such as on this test case.  Can you point me to the lesson?  thnkx.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-functions/increment-parameter-by-one

**User code**:
```python
# Your code here:
```

**Comment by jsymons** [comment]
We went over this during mentor help session. This safe to close or do you need further help?

**Comment by databaseadmins** [comment]
This can be closed -- thank you for helping
