### ISSUE TITLE
video of courses

### ISSUE THREAD

**Issue by VisionMaker** [rmotr-curriculum/base-python-curriculum-questions#81]
I was looking for the video with first the theorical part and have the practice after

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/convert-boolean-to-binary

**User code**:
```python
def convert_bool_to_binary(a_boolean):
    pass
```

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
