### ISSUE TITLE
Grade letters

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/base-python-curriculum-questions#82]
I am not understanding where I am making the mistake with this code (the test for Grade letter 'A' and 'B' passes:

def get_grade_letter(score):
    if score >= 90:
        return 'A'
    elif score <= 89 or score >= 80:
        return 'B'
    elif score <= 79 or score >= 70:
        return 'C'
    elif score <= 69 or score >= 60:
        return 'D'
    elif score < 60:
        return 'F'
    

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/get-grade-letter

**User code**:
```python
def get_grade_letter(score):
    if score >= 90:
        return 'A'
    elif score <= 89 or score >= 80:
        return 'B'
    elif score <= 79 or score >= 70:
        return 'C'
    elif score <= 69 or score >= 60:
        return 'D'
    elif score < 60:
        return 'F'
    
pass
```

**Comment by jsymons** [comment]
The issue is your `or` statements. Say we pass in a `score` of 32. When we get to your first `elif` we find that `score <= 89` is `True`, so it returns `'B'`

**Comment by santiagobasulto** [comment]
yep, just to add to that, it should be an `and` instead of an `or`. Or you could invert all the conditions 😜
