### ISSUE TITLE
equal

### ISSUE THREAD

**Issue by VisionMaker** [rmotr-curriculum/base-python-curriculum-questions#84]
the  part (age>14 would it not be great as well to put >=14 ? - Can I put other conditions ? If yes how ? (I mean other "if" if he is >14 he can drive, have a gift, have miles saved, have a discount, have a discount if he is with maany friends and so on

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/if-statements

**Comment by santiagobasulto** [comment]
You could use an `or`. For example: `age> 14 or miles_saved > 1000`.
