### ISSUE TITLE
convert boolean to binary

### ISSUE THREAD

**Issue by deboragaleano** [rmotr-curriculum/base-python-curriculum-questions#87]
My code passed but still not sure about the second part, maybe the "else" is not correct there. I tried adding a second line for "False" (with "or", "and", "if") but nothing worked. You can only have one return, right? I mean, I wanted to put everything in one line but I couldn't figure out. Thanks for your help!

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/convert-boolean-to-binary

**User code**:
```python
def convert_bool_to_binary(a_boolean):
    return 1 if a_boolean == True else 0 
    
true= print(convert_bool_to_binary(True))
```

**Comment by jsymons** [comment]
You can have more than one `return` statement, you just have to understand that the first one the code encounters will be the only one that executes.

For example, this is fine:
```python
def is_greater_than_10(a_number):
    if a_number > 10:
        return True
    return False
```
However with the following the second return will **never** execute:
```python
def return_test():
    return "I return"
    return "I never execute"
```
Another simple way to do your return as a single line would be:
```python
return int(a_boolean)
```
