### ISSUE TITLE
i get the correct result but the sys says my code is failing 

### ISSUE THREAD

**Issue by mohabouh** [rmotr-curriculum/base-python-curriculum-questions#89]
def population_growth(initial_pop, annual_growth_rate, target_pop):
    if annual_growth_rate <= 0:
        
        return 'Invalid growth rate'
      
    else:
        y = initial_pop
        c = 0
        while y < target_pop:
            y = y * (1 + annual_growth_rate)
            c += 1
        return c
        
  
print(population_growth(5000, 0.1, 20000))

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/population-growth

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
Hey Hello! What's your issue? Glancing through the code I think you might want to change the `<` operator for a `<=`. But please describe the error you're having.
