### ISSUE TITLE
Intro to functions and invoking functions not showing progress

### ISSUE THREAD

**Issue by databaseadmins** [rmotr-curriculum/base-python-curriculum-questions#9]
This is the same thing that was going on with the password section.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-functions/intro-to-functions

**Comment by martinzugnoni** [comment]
On it! Will let you know when it's fixed.

**Comment by databaseadmins** [comment]
I'm working on control flow right now if you want to watch in real time to see if that helps debugging.  Cheers.

**Comment by martinzugnoni** [comment]
Nice. We are working on it right now as well. Will ping you with news.

**Comment by databaseadmins** [comment]
This is still not showing progress -
