### ISSUE TITLE
Not sure where to go

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/base-python-curriculum-questions#91]
I feel that I am missing a portion of the code, but unsure where to go next 

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/knock-3-times

**User code**:
```python
def knock_three_times():
    output = 0
    while output < 4:
        print("Knock Knock")
        output += 1
```

**Comment by jsymons** [comment]
Your while loop is iterating **4** times. First iteration `output` is `0`, next it's `1`, then `2`, then `3`. At this point your while condition is no longer true and execution stops. You either need to start output at 1 or take into account that it's starting at 0 and adjust your while condition.
