### ISSUE TITLE
Scruffy answer

### ISSUE THREAD

**Issue by kufopi** [rmotr-curriculum/base-python-curriculum-questions#93]
I would like to see your suggested solution to this

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/insert-dashes-every-3-characters

**User code**:
```python
def insert_dashes(a_string):
    
    check = ""
    count=0
    while count<len(a_string):

        if ((count >0) and (count%3==0) ):
            check+="-"
        check += a_string[count]
        count+=1
        
    if len(a_string)%6==0:
        check=check+"-"


    return check
```

**Comment by santiagobasulto** [comment]
Hey @kufopi ! I think you're pretty close to ideal. Maybe a little bit of "readability" might help (for example, putting spaces between assignments and operators like `check += "-"`). And then, if you check carefully, the conditions `%3` and `%6` are kind of similar. I think you can check only for `%3`.

Anyway, great work! This would be my suggested solution:

```python
def insert_dashes(a_string):
    counter = 1
    res = ""
    while counter <= len(a_string):
        char = a_string[counter - 1]
        res += char
        if counter % 3 == 0:
            res += '-'
        counter += 1
    return res
```
