### ISSUE TITLE
not sure about the body of the function

### ISSUE THREAD

**Issue by deboragaleano** [rmotr-curriculum/base-python-curriculum-questions#94]
I know the code doesn't work and though I tried to figure out, I couldn't do it. Would appreciate your help! Thanks so much!

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/string-of-numbers

**User code**:
```python

```

**Comment by jsymons** [comment]
Could you please post your code so we can help you with what's wrong with it? Thanks.

**Comment by deboragaleano** [comment]
sorry! I thought it went with the question. I know that this code is just asking to concatenate two strings but not sure how to actually do what's being asked in the exercise:  

def string_of_numbers(length):
    
    count = 1
    num= 5
    result_string= str(length) + str(num)
    
    while num > length:
        return result_string 
    
    count += 1 

print (string_of_numbers(2))

**Comment by santiagobasulto** [comment]
@debygalser this might help 😄 https://youtu.be/i5Ve2ePni00

**Comment by santiagobasulto** [comment]
@debygalser can I close this one?

**Comment by deboragaleano** [comment]
yes! thank you so much!

**Comment by santiagobasulto** [comment]
yw :)
