### ISSUE TITLE
I can't get to the solutions section -- please fix.

### ISSUE THREAD

**Issue by databaseadmins** [rmotr-curriculum/base-python-curriculum-questions#95]
I'm trying to get to the solutions but it's not working.  

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/all-in-string

**User code**:
```python

```

**Comment by jsymons** [comment]
If you've already completed the problem just reload the page and you should be able to click on the solutions link at the top. If that area is showing up blank please let us know.

**Comment by databaseadmins** [comment]
This seems to be a problem with most of the challenges - we can't get to the solutions even after repeated attempts.  In that case I was trying to see how to proceed because I was stuck.

**Comment by jsymons** [comment]
After about 5 solution submission attempts you should also be able to view the solution (this may require a page reload). Aside from that you can click the GitHub icon at the bottom of the page which links to the project's repo on GitHub which also contains the solution.
