### ISSUE TITLE
Is this an accurate way of writing magic methods? 

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#96]
I notice in the given solution, many of the equality methods use an 'If (condition): return True, else: return false' format.  I am wondering if simply returning it is not accurate (though I am passing the tests).  If you could explain this logic please!

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/going-the-distance

**User code**:
```python
def __eq__(self, other):
        return self.convert_to_meters(self.unit) == other.convert_to_meters(self.unit)

    def __ne__(self, other):
        return not self == other

    def __lt__(self, other):
        return self.convert_to_meters(self.unit) < other.convert_to_meters(self.unit)

    def __le__(self, other):
        return self.convert_to_meters(self.unit) <= other.convert_to_meters(self.unit)

    def __gt__(self, other):
        return self.convert_to_meters(self.unit) > other.convert_to_meters(self.unit)

    def __ge__(self, other):
        return self.convert_to_meters(self.unit) >= other.convert_to_meters(self.unit)
```

**Comment by santiagobasulto** [comment]
Your solution is not just accurate, but also recommended. We tend to put `if` statements to make it a little bit more clear. Student sometime have trouble understanding the expression and the return all together. Amazing work 👍 .
