### ISSUE TITLE
Confused or Confusing assignment

### ISSUE THREAD

**Issue by kufopi** [rmotr-curriculum/base-python-curriculum-questions#97]
Really can't my head around what to do. Is it to recreate the board given the three parameters?.
BTW forgive my naming convention i was getting frustrated

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/format-board

**User code**:
```python
# Example. Use it as a base to build your own template.
BOARD_TEMPLATE = """
O  |  O  |  X
--------------
X  |  X  |  O
--------------
O  |  X  |  O
"""


def format_tic_tac_toe_board(first_row, second_row, third_row):
    row = ""
    more0 = ""
    row3 = ""
    more1 = ""
    rowe = ""
    rowk = ""
    more2 = ""
    num = 0
    more = []
    while num < 3:

        for k in range(0,3):
            row +=first_row[k] +" | "
            row3 +=second_row[k] +" | "
            rowk +=third_row[k]+" | "

        more0 = row[0:14]
        more.append(more0)
        more1 = row3[0:14]
        more.append(more1)
        more2 = rowk[0:14]
        more.append(more2)



        print(more[num])
        if num <2:
            print('-' * 10)
        num+=1
```

**Comment by jsymons** [comment]
Yes, given the three parameters you need to recreate and **return** the board as a string. It is advised to use a multi-line string w/ the `format` method to make your life easier, otherwise you will have to pay close attention to where newline characters (`'\n'`) should be inserted.

**Comment by jsymons** [comment]
If you need more guidance on this, please let me know.
