### ISSUE TITLE
Defining variables 

### ISSUE THREAD

**Issue by swb304** [rmotr-curriculum/base-python-curriculum-questions#98]
int_string = ''

I'm not clear on why the above works in my code below but didn't work when I defined it this way:

int_string = str

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/string-of-numbers

**User code**:
```python
def string_of_numbers(length):
    count = 1
    int_string = ''
    while count <= length:
        int_string += str(count)
        count += 1 
    return int_string
    
print(string_of_numbers(5))
```

**Comment by santiagobasulto** [comment]
@swb304 does this help 😉 https://youtu.be/i5Ve2ePni00
