### ISSUE TITLE
the "run code" button is not working 

### ISSUE THREAD

**Issue by deboragaleano** [rmotr-curriculum/base-python-curriculum-questions#99]
I'm trying to test the code but not sure why it's frozen. Am I close to the right answer though? Thank you!

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/no-uppercase-allowed

**User code**:
```python
def neutralize_uppercase(stringy):
    valid = False
    
    while not valid:
        if len(stringy) == stringy.upper():
            print("")
        else: 
            print(stringy)

print(neutralize_uppercase("jssU"))
```

**Comment by jsymons** [comment]
You've created an infinite loop. Your while loop condition will never not be True as you never modify valid, thus the loop executes forever.

Also remember you ultimately need to return, not print. The tests operate on the return value.

**Comment by santiagobasulto** [comment]
Oh no! Infinite loops 😱 !
